// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InviteRole.
const (
	InviteRoleAdmin  InviteRole = "admin"
	InviteRoleMember InviteRole = "member"
	InviteRoleViewer InviteRole = "viewer"
)

// Valid indicates whether the value is a known member of the InviteRole enum.
func (e InviteRole) Valid() bool {
	switch e {
	case InviteRoleAdmin:
		return true
	case InviteRoleMember:
		return true
	case InviteRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	En Locale = "en"
	Uk Locale = "uk"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case En:
		return true
	case Uk:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
	RoleOwner  Role = "owner"
	RoleViewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleMember:
		return true
	case RoleOwner:
		return true
	case RoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for UserProviders.
const (
	UserProvidersGithub UserProviders = "github"
	UserProvidersGoogle UserProviders = "google"
)

// Valid indicates whether the value is a known member of the UserProviders enum.
func (e UserProviders) Valid() bool {
	switch e {
	case UserProvidersGithub:
		return true
	case UserProvidersGoogle:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderGithub Provider = "github"
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderGithub:
		return true
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGithub OauthCallbackParamsProvider = "github"
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case OauthCallbackParamsProviderGithub:
		return true
	case OauthCallbackParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthStartParamsProvider.
const (
	OauthStartParamsProviderGithub OauthStartParamsProvider = "github"
	OauthStartParamsProviderGoogle OauthStartParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthStartParamsProvider enum.
func (e OauthStartParamsProvider) Valid() bool {
	switch e {
	case OauthStartParamsProviderGithub:
		return true
	case OauthStartParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// AuthProviders defines model for AuthProviders.
type AuthProviders struct {
	Github bool `json:"github"`
	Google bool `json:"google"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Required when the account already has a password
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     string  `json:"newPassword"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	// Email Email address (validated server-side)
	Email string     `json:"email"`
	Role  InviteRole `json:"role"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken struct {
	Token string `json:"token"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email string `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: auth.invalid_credentials
		Code    string                  `json:"code"`
		Fields  *[]FieldError           `json:"fields,omitempty"`
		Message string                  `json:"message"`
		Meta    *map[string]interface{} `json:"meta,omitempty"`
	} `json:"error"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Example: min_length
	Code   string                  `json:"code"`
	Field  string                  `json:"field"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// Invite defines model for Invite.
type Invite struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      InviteRole         `json:"role"`
}

// InvitePreview defines model for InvitePreview.
type InvitePreview struct {
	Accepted      bool       `json:"accepted"`
	Email         string     `json:"email"`
	Expired       bool       `json:"expired"`
	InviterName   *string    `json:"inviterName"`
	Role          InviteRole `json:"role"`
	WorkspaceName string     `json:"workspaceName"`
}

// InviteRole defines model for InviteRole.
type InviteRole string

// Locale defines model for Locale.
type Locale string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Member defines model for Member.
type Member struct {
	JoinedAt time.Time  `json:"joinedAt"`
	Role     Role       `json:"role"`
	User     MemberUser `json:"user"`
}

// MemberUser defines model for MemberUser.
type MemberUser struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email address (validated server-side)
	Email    string  `json:"email"`
	Locale   *Locale `json:"locale,omitempty"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Role defines model for Role.
type Role string

// Session defines model for Session.
type Session struct {
	User User `json:"user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Locale *Locale `json:"locale,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string   `json:"avatarUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Email Email address (validated server-side)
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	HasPassword   bool               `json:"hasPassword"`
	Id            openapi_types.UUID `json:"id"`
	Locale        Locale             `json:"locale"`
	Name          string             `json:"name"`
	Providers     []UserProviders    `json:"providers"`
}

// UserProviders defines model for User.Providers.
type UserProviders string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int                `json:"memberCount"`
	Name        string             `json:"name"`
	Role        Role               `json:"role"`
	Slug        string             `json:"slug"`
}

// WorkspaceInput defines model for WorkspaceInput.
type WorkspaceInput struct {
	Name string `json:"name"`
}

// Provider defines model for Provider.
type Provider string

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// OauthStartParams defines parameters for OauthStart.
type OauthStartParams struct {
	// Next Relative path to return to after sign-in
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// OauthStartParamsProvider defines parameters for OauthStart.
type OauthStartParamsProvider string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = EmailRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = WorkspaceInput

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = WorkspaceInput

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRequest
