// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulkCardActionAction.
const (
	BulkCardActionActionDelete   BulkCardActionAction = "delete"
	BulkCardActionActionMove     BulkCardActionAction = "move"
	BulkCardActionActionPriority BulkCardActionAction = "priority"
)

// Valid indicates whether the value is a known member of the BulkCardActionAction enum.
func (e BulkCardActionAction) Valid() bool {
	switch e {
	case BulkCardActionActionDelete:
		return true
	case BulkCardActionActionMove:
		return true
	case BulkCardActionActionPriority:
		return true
	default:
		return false
	}
}

// Defines values for ChatChannelKind.
const (
	ChatChannelKindCard    ChatChannelKind = "card"
	ChatChannelKindDm      ChatChannelKind = "dm"
	ChatChannelKindPrivate ChatChannelKind = "private"
	ChatChannelKindProject ChatChannelKind = "project"
	ChatChannelKindPublic  ChatChannelKind = "public"
)

// Valid indicates whether the value is a known member of the ChatChannelKind enum.
func (e ChatChannelKind) Valid() bool {
	switch e {
	case ChatChannelKindCard:
		return true
	case ChatChannelKindDm:
		return true
	case ChatChannelKindPrivate:
		return true
	case ChatChannelKindProject:
		return true
	case ChatChannelKindPublic:
		return true
	default:
		return false
	}
}

// Defines values for InviteRole.
const (
	InviteRoleAdmin  InviteRole = "admin"
	InviteRoleMember InviteRole = "member"
	InviteRoleViewer InviteRole = "viewer"
)

// Valid indicates whether the value is a known member of the InviteRole enum.
func (e InviteRole) Valid() bool {
	switch e {
	case InviteRoleAdmin:
		return true
	case InviteRoleMember:
		return true
	case InviteRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	LocaleEn Locale = "en"
	LocaleUk Locale = "uk"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case LocaleEn:
		return true
	case LocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for Priority.
const (
	High   Priority = "high"
	Low    Priority = "low"
	Medium Priority = "medium"
)

// Valid indicates whether the value is a known member of the Priority enum.
func (e Priority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ProjectIcon.
const (
	ProjectIconCode      ProjectIcon = "code"
	ProjectIconFlask     ProjectIcon = "flask"
	ProjectIconFolder    ProjectIcon = "folder"
	ProjectIconGlobe     ProjectIcon = "globe"
	ProjectIconLayers    ProjectIcon = "layers"
	ProjectIconMegaphone ProjectIcon = "megaphone"
	ProjectIconRocket    ProjectIcon = "rocket"
	ProjectIconShield    ProjectIcon = "shield"
	ProjectIconSparkles  ProjectIcon = "sparkles"
	ProjectIconTarget    ProjectIcon = "target"
)

// Valid indicates whether the value is a known member of the ProjectIcon enum.
func (e ProjectIcon) Valid() bool {
	switch e {
	case ProjectIconCode:
		return true
	case ProjectIconFlask:
		return true
	case ProjectIconFolder:
		return true
	case ProjectIconGlobe:
		return true
	case ProjectIconLayers:
		return true
	case ProjectIconMegaphone:
		return true
	case ProjectIconRocket:
		return true
	case ProjectIconShield:
		return true
	case ProjectIconSparkles:
		return true
	case ProjectIconTarget:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusPending    ProjectStatus = "pending"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusCompleted:
		return true
	case ProjectStatusInProgress:
		return true
	case ProjectStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
	RoleOwner  Role = "owner"
	RoleViewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleMember:
		return true
	case RoleOwner:
		return true
	case RoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusDone       TaskStatus = "done"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusInReview   TaskStatus = "in_review"
	TaskStatusTodo       TaskStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusDone:
		return true
	case TaskStatusInProgress:
		return true
	case TaskStatusInReview:
		return true
	case TaskStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for Tone.
const (
	Amber   Tone = "amber"
	Neutral Tone = "neutral"
	Purple  Tone = "purple"
	Red     Tone = "red"
	Teal    Tone = "teal"
)

// Valid indicates whether the value is a known member of the Tone enum.
func (e Tone) Valid() bool {
	switch e {
	case Amber:
		return true
	case Neutral:
		return true
	case Purple:
		return true
	case Red:
		return true
	case Teal:
		return true
	default:
		return false
	}
}

// Defines values for UserProviders.
const (
	UserProvidersGithub UserProviders = "github"
	UserProvidersGoogle UserProviders = "google"
)

// Valid indicates whether the value is a known member of the UserProviders enum.
func (e UserProviders) Valid() bool {
	switch e {
	case UserProvidersGithub:
		return true
	case UserProvidersGoogle:
		return true
	default:
		return false
	}
}

// Defines values for WikiAccessVia.
const (
	WikiAccessViaGrant     WikiAccessVia = "grant"
	WikiAccessViaNone      WikiAccessVia = "none"
	WikiAccessViaOwner     WikiAccessVia = "owner"
	WikiAccessViaWorkspace WikiAccessVia = "workspace"
)

// Valid indicates whether the value is a known member of the WikiAccessVia enum.
func (e WikiAccessVia) Valid() bool {
	switch e {
	case WikiAccessViaGrant:
		return true
	case WikiAccessViaNone:
		return true
	case WikiAccessViaOwner:
		return true
	case WikiAccessViaWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for WikiAccessSummarySource.
const (
	WikiAccessSummarySourceNode  WikiAccessSummarySource = "node"
	WikiAccessSummarySourceSpace WikiAccessSummarySource = "space"
)

// Valid indicates whether the value is a known member of the WikiAccessSummarySource enum.
func (e WikiAccessSummarySource) Valid() bool {
	switch e {
	case WikiAccessSummarySourceNode:
		return true
	case WikiAccessSummarySourceSpace:
		return true
	default:
		return false
	}
}

// Defines values for WikiAccessSummaryVia.
const (
	WikiAccessSummaryViaGrant     WikiAccessSummaryVia = "grant"
	WikiAccessSummaryViaNone      WikiAccessSummaryVia = "none"
	WikiAccessSummaryViaOwner     WikiAccessSummaryVia = "owner"
	WikiAccessSummaryViaWorkspace WikiAccessSummaryVia = "workspace"
)

// Valid indicates whether the value is a known member of the WikiAccessSummaryVia enum.
func (e WikiAccessSummaryVia) Valid() bool {
	switch e {
	case WikiAccessSummaryViaGrant:
		return true
	case WikiAccessSummaryViaNone:
		return true
	case WikiAccessSummaryViaOwner:
		return true
	case WikiAccessSummaryViaWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for WikiGrantSource.
const (
	WikiGrantSourceNode  WikiGrantSource = "node"
	WikiGrantSourceSpace WikiGrantSource = "space"
)

// Valid indicates whether the value is a known member of the WikiGrantSource enum.
func (e WikiGrantSource) Valid() bool {
	switch e {
	case WikiGrantSourceNode:
		return true
	case WikiGrantSourceSpace:
		return true
	default:
		return false
	}
}

// Defines values for WikiNodeKind.
const (
	WikiNodeKindFolder WikiNodeKind = "folder"
	WikiNodeKindPage   WikiNodeKind = "page"
)

// Valid indicates whether the value is a known member of the WikiNodeKind enum.
func (e WikiNodeKind) Valid() bool {
	switch e {
	case WikiNodeKindFolder:
		return true
	case WikiNodeKindPage:
		return true
	default:
		return false
	}
}

// Defines values for WikiNodeInputKind.
const (
	WikiNodeInputKindFolder WikiNodeInputKind = "folder"
	WikiNodeInputKindPage   WikiNodeInputKind = "page"
)

// Valid indicates whether the value is a known member of the WikiNodeInputKind enum.
func (e WikiNodeInputKind) Valid() bool {
	switch e {
	case WikiNodeInputKindFolder:
		return true
	case WikiNodeInputKindPage:
		return true
	default:
		return false
	}
}

// Defines values for WikiNodeInputLang.
const (
	WikiNodeInputLangEn WikiNodeInputLang = "en"
	WikiNodeInputLangUk WikiNodeInputLang = "uk"
)

// Valid indicates whether the value is a known member of the WikiNodeInputLang enum.
func (e WikiNodeInputLang) Valid() bool {
	switch e {
	case WikiNodeInputLangEn:
		return true
	case WikiNodeInputLangUk:
		return true
	default:
		return false
	}
}

// Defines values for WikiPrincipalKind.
const (
	WikiPrincipalKindTeam WikiPrincipalKind = "team"
	WikiPrincipalKindUser WikiPrincipalKind = "user"
)

// Valid indicates whether the value is a known member of the WikiPrincipalKind enum.
func (e WikiPrincipalKind) Valid() bool {
	switch e {
	case WikiPrincipalKindTeam:
		return true
	case WikiPrincipalKindUser:
		return true
	default:
		return false
	}
}

// Defines values for WikiRole.
const (
	WikiRoleCommenter WikiRole = "commenter"
	WikiRoleEditor    WikiRole = "editor"
	WikiRoleOwner     WikiRole = "owner"
	WikiRoleViewer    WikiRole = "viewer"
)

// Valid indicates whether the value is a known member of the WikiRole enum.
func (e WikiRole) Valid() bool {
	switch e {
	case WikiRoleCommenter:
		return true
	case WikiRoleEditor:
		return true
	case WikiRoleOwner:
		return true
	case WikiRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for WikiStatus.
const (
	Draft     WikiStatus = "draft"
	Outdated  WikiStatus = "outdated"
	Published WikiStatus = "published"
)

// Valid indicates whether the value is a known member of the WikiStatus enum.
func (e WikiStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Outdated:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for WikiTreeNodeKind.
const (
	WikiTreeNodeKindFolder WikiTreeNodeKind = "folder"
	WikiTreeNodeKindPage   WikiTreeNodeKind = "page"
)

// Valid indicates whether the value is a known member of the WikiTreeNodeKind enum.
func (e WikiTreeNodeKind) Valid() bool {
	switch e {
	case WikiTreeNodeKindFolder:
		return true
	case WikiTreeNodeKindPage:
		return true
	default:
		return false
	}
}

// Defines values for WikiVisibility.
const (
	WikiVisibilityPrivate   WikiVisibility = "private"
	WikiVisibilityShared    WikiVisibility = "shared"
	WikiVisibilityWorkspace WikiVisibility = "workspace"
)

// Valid indicates whether the value is a known member of the WikiVisibility enum.
func (e WikiVisibility) Valid() bool {
	switch e {
	case WikiVisibilityPrivate:
		return true
	case WikiVisibilityShared:
		return true
	case WikiVisibilityWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for WikiWorkspaceRole.
const (
	WikiWorkspaceRoleCommenter WikiWorkspaceRole = "commenter"
	WikiWorkspaceRoleEditor    WikiWorkspaceRole = "editor"
	WikiWorkspaceRoleViewer    WikiWorkspaceRole = "viewer"
)

// Valid indicates whether the value is a known member of the WikiWorkspaceRole enum.
func (e WikiWorkspaceRole) Valid() bool {
	switch e {
	case WikiWorkspaceRoleCommenter:
		return true
	case WikiWorkspaceRoleEditor:
		return true
	case WikiWorkspaceRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for CardDue.
const (
	CardDueMonth   CardDue = "month"
	CardDueNone    CardDue = "none"
	CardDueOverdue CardDue = "overdue"
	CardDueToday   CardDue = "today"
	CardDueWeek    CardDue = "week"
)

// Valid indicates whether the value is a known member of the CardDue enum.
func (e CardDue) Valid() bool {
	switch e {
	case CardDueMonth:
		return true
	case CardDueNone:
		return true
	case CardDueOverdue:
		return true
	case CardDueToday:
		return true
	case CardDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderGithub Provider = "github"
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderGithub:
		return true
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGithub OauthCallbackParamsProvider = "github"
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case OauthCallbackParamsProviderGithub:
		return true
	case OauthCallbackParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthStartParamsProvider.
const (
	OauthStartParamsProviderGithub OauthStartParamsProvider = "github"
	OauthStartParamsProviderGoogle OauthStartParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthStartParamsProvider enum.
func (e OauthStartParamsProvider) Valid() bool {
	switch e {
	case OauthStartParamsProviderGithub:
		return true
	case OauthStartParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsDue.
const (
	ListCardsParamsDueMonth   ListCardsParamsDue = "month"
	ListCardsParamsDueNone    ListCardsParamsDue = "none"
	ListCardsParamsDueOverdue ListCardsParamsDue = "overdue"
	ListCardsParamsDueToday   ListCardsParamsDue = "today"
	ListCardsParamsDueWeek    ListCardsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the ListCardsParamsDue enum.
func (e ListCardsParamsDue) Valid() bool {
	switch e {
	case ListCardsParamsDueMonth:
		return true
	case ListCardsParamsDueNone:
		return true
	case ListCardsParamsDueOverdue:
		return true
	case ListCardsParamsDueToday:
		return true
	case ListCardsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsSort.
const (
	ListCardsParamsSortAssignee ListCardsParamsSort = "assignee"
	ListCardsParamsSortDeadline ListCardsParamsSort = "deadline"
	ListCardsParamsSortKey      ListCardsParamsSort = "key"
	ListCardsParamsSortPosition ListCardsParamsSort = "position"
	ListCardsParamsSortPriority ListCardsParamsSort = "priority"
	ListCardsParamsSortProgress ListCardsParamsSort = "progress"
	ListCardsParamsSortProject  ListCardsParamsSort = "project"
	ListCardsParamsSortTitle    ListCardsParamsSort = "title"
	ListCardsParamsSortUpdated  ListCardsParamsSort = "updated"
)

// Valid indicates whether the value is a known member of the ListCardsParamsSort enum.
func (e ListCardsParamsSort) Valid() bool {
	switch e {
	case ListCardsParamsSortAssignee:
		return true
	case ListCardsParamsSortDeadline:
		return true
	case ListCardsParamsSortKey:
		return true
	case ListCardsParamsSortPosition:
		return true
	case ListCardsParamsSortPriority:
		return true
	case ListCardsParamsSortProgress:
		return true
	case ListCardsParamsSortProject:
		return true
	case ListCardsParamsSortTitle:
		return true
	case ListCardsParamsSortUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsOrder.
const (
	ListCardsParamsOrderAsc  ListCardsParamsOrder = "asc"
	ListCardsParamsOrderDesc ListCardsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListCardsParamsOrder enum.
func (e ListCardsParamsOrder) Valid() bool {
	switch e {
	case ListCardsParamsOrderAsc:
		return true
	case ListCardsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for BoardCardsParamsDue.
const (
	BoardCardsParamsDueMonth   BoardCardsParamsDue = "month"
	BoardCardsParamsDueNone    BoardCardsParamsDue = "none"
	BoardCardsParamsDueOverdue BoardCardsParamsDue = "overdue"
	BoardCardsParamsDueToday   BoardCardsParamsDue = "today"
	BoardCardsParamsDueWeek    BoardCardsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the BoardCardsParamsDue enum.
func (e BoardCardsParamsDue) Valid() bool {
	switch e {
	case BoardCardsParamsDueMonth:
		return true
	case BoardCardsParamsDueNone:
		return true
	case BoardCardsParamsDueOverdue:
		return true
	case BoardCardsParamsDueToday:
		return true
	case BoardCardsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for CardStatusCountsParamsDue.
const (
	CardStatusCountsParamsDueMonth   CardStatusCountsParamsDue = "month"
	CardStatusCountsParamsDueNone    CardStatusCountsParamsDue = "none"
	CardStatusCountsParamsDueOverdue CardStatusCountsParamsDue = "overdue"
	CardStatusCountsParamsDueToday   CardStatusCountsParamsDue = "today"
	CardStatusCountsParamsDueWeek    CardStatusCountsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the CardStatusCountsParamsDue enum.
func (e CardStatusCountsParamsDue) Valid() bool {
	switch e {
	case CardStatusCountsParamsDueMonth:
		return true
	case CardStatusCountsParamsDueNone:
		return true
	case CardStatusCountsParamsDueOverdue:
		return true
	case CardStatusCountsParamsDueToday:
		return true
	case CardStatusCountsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsProgress.
const (
	ListProjectsParamsProgressAlmost     ListProjectsParamsProgress = "almost"
	ListProjectsParamsProgressDone       ListProjectsParamsProgress = "done"
	ListProjectsParamsProgressEarly      ListProjectsParamsProgress = "early"
	ListProjectsParamsProgressMidway     ListProjectsParamsProgress = "midway"
	ListProjectsParamsProgressNotStarted ListProjectsParamsProgress = "not_started"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsProgress enum.
func (e ListProjectsParamsProgress) Valid() bool {
	switch e {
	case ListProjectsParamsProgressAlmost:
		return true
	case ListProjectsParamsProgressDone:
		return true
	case ListProjectsParamsProgressEarly:
		return true
	case ListProjectsParamsProgressMidway:
		return true
	case ListProjectsParamsProgressNotStarted:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsDeadline.
const (
	ListProjectsParamsDeadlineLater   ListProjectsParamsDeadline = "later"
	ListProjectsParamsDeadlineMonth   ListProjectsParamsDeadline = "month"
	ListProjectsParamsDeadlineNone    ListProjectsParamsDeadline = "none"
	ListProjectsParamsDeadlineOverdue ListProjectsParamsDeadline = "overdue"
	ListProjectsParamsDeadlineWeek    ListProjectsParamsDeadline = "week"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsDeadline enum.
func (e ListProjectsParamsDeadline) Valid() bool {
	switch e {
	case ListProjectsParamsDeadlineLater:
		return true
	case ListProjectsParamsDeadlineMonth:
		return true
	case ListProjectsParamsDeadlineNone:
		return true
	case ListProjectsParamsDeadlineOverdue:
		return true
	case ListProjectsParamsDeadlineWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsSort.
const (
	ListProjectsParamsSortCreated  ListProjectsParamsSort = "created"
	ListProjectsParamsSortDeadline ListProjectsParamsSort = "deadline"
	ListProjectsParamsSortName     ListProjectsParamsSort = "name"
	ListProjectsParamsSortProgress ListProjectsParamsSort = "progress"
	ListProjectsParamsSortUpdated  ListProjectsParamsSort = "updated"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsSort enum.
func (e ListProjectsParamsSort) Valid() bool {
	switch e {
	case ListProjectsParamsSortCreated:
		return true
	case ListProjectsParamsSortDeadline:
		return true
	case ListProjectsParamsSortName:
		return true
	case ListProjectsParamsSortProgress:
		return true
	case ListProjectsParamsSortUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsOrder.
const (
	ListProjectsParamsOrderAsc  ListProjectsParamsOrder = "asc"
	ListProjectsParamsOrderDesc ListProjectsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsOrder enum.
func (e ListProjectsParamsOrder) Valid() bool {
	switch e {
	case ListProjectsParamsOrderAsc:
		return true
	case ListProjectsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListWikiTemplatesParamsLang.
const (
	ListWikiTemplatesParamsLangEn ListWikiTemplatesParamsLang = "en"
	ListWikiTemplatesParamsLangUk ListWikiTemplatesParamsLang = "uk"
)

// Valid indicates whether the value is a known member of the ListWikiTemplatesParamsLang enum.
func (e ListWikiTemplatesParamsLang) Valid() bool {
	switch e {
	case ListWikiTemplatesParamsLangEn:
		return true
	case ListWikiTemplatesParamsLangUk:
		return true
	default:
		return false
	}
}

// ActivityEntry defines model for ActivityEntry.
type ActivityEntry struct {
	Actor *PersonRef             `json:"actor"`
	At    time.Time              `json:"at"`
	Data  map[string]interface{} `json:"data"`
	Id    int64                  `json:"id"`

	// Kind Translatable key: card.created|updated|moved|deleted, checklist.*, comment.*, attachment.*
	//
	// Example: card.moved
	Kind string `json:"kind"`
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	Actor *PersonRef `json:"actor"`
	At    time.Time  `json:"at"`
	Card  struct {
		Id    openapi_types.UUID `json:"id"`
		Key   string             `json:"key"`
		Title string             `json:"title"`
	} `json:"card"`
	From    *TaskStatus `json:"from"`
	Id      int64       `json:"id"`
	Project ProjectRef  `json:"project"`
	To      TaskStatus  `json:"to"`
}

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items      []ActivityEntry `json:"items"`
	NextBefore *int64          `json:"nextBefore"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string             `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`

	// Previewable Image the browser may display inline
	Previewable bool       `json:"previewable"`
	Size        int64      `json:"size"`
	UploadedBy  *PersonRef `json:"uploadedBy"`
}

// AuthProviders defines model for AuthProviders.
type AuthProviders struct {
	Github bool `json:"github"`
	Google bool `json:"google"`
}

// Board defines model for Board.
type Board struct {
	Columns   []BoardColumn      `json:"columns"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	ProjectId openapi_types.UUID `json:"projectId"`
}

// BoardColumn defines model for BoardColumn.
type BoardColumn struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Position string             `json:"position"`
	Status   TaskStatus         `json:"status"`
	WipLimit *int               `json:"wipLimit"`
}

// BulkCardAction defines model for BulkCardAction.
type BulkCardAction struct {
	Action   BulkCardActionAction `json:"action"`
	Ids      []openapi_types.UUID `json:"ids"`
	Priority *Priority            `json:"priority,omitempty"`
	Status   *TaskStatus          `json:"status,omitempty"`
}

// BulkCardActionAction defines model for BulkCardAction.Action.
type BulkCardActionAction string

// BulkResult defines model for BulkResult.
type BulkResult struct {
	Updated int `json:"updated"`
}

// Card defines model for Card.
type Card struct {
	Assignees       []PersonRef         `json:"assignees"`
	AttachmentCount int                 `json:"attachmentCount"`
	Checklist       ChecklistSummary    `json:"checklist"`
	ColumnId        openapi_types.UUID  `json:"columnId"`
	CommentCount    int                 `json:"commentCount"`
	CompletedAt     *time.Time          `json:"completedAt"`
	CreatedAt       time.Time           `json:"createdAt"`
	Description     string              `json:"description"`
	DueDate         *openapi_types.Date `json:"dueDate"`
	Id              openapi_types.UUID  `json:"id"`

	// Key Example: LK-12
	Key      string      `json:"key"`
	Labels   []Label     `json:"labels"`
	Number   int         `json:"number"`
	Parent   *CardParent `json:"parent,omitempty"`
	Position string      `json:"position"`
	Priority Priority    `json:"priority"`

	// Progress Derived: checklist share, else workflow stage; 100 only when done (ADR 0010)
	Progress  int              `json:"progress"`
	Project   ProjectRef       `json:"project"`
	Status    TaskStatus       `json:"status"`
	Subtasks  ChecklistSummary `json:"subtasks"`
	Title     string           `json:"title"`
	UpdatedAt time.Time        `json:"updatedAt"`

	// Version Optimistic concurrency token; send it back on update/move
	Version int `json:"version"`
}

// CardBoard defines model for CardBoard.
type CardBoard struct {
	Items []Card `json:"items"`

	// Truncated More cards match than were returned
	Truncated bool `json:"truncated"`
}

// CardInput defines model for CardInput.
type CardInput struct {
	AssigneeIds *[]openapi_types.UUID `json:"assigneeIds,omitempty"`
	ColumnId    *openapi_types.UUID   `json:"columnId,omitempty"`
	Description *string               `json:"description,omitempty"`
	DueDate     *openapi_types.Date   `json:"dueDate,omitempty"`
	LabelIds    *[]openapi_types.UUID `json:"labelIds,omitempty"`

	// ParentId Create as a subtask of this card (same project; one level deep)
	ParentId  *openapi_types.UUID `json:"parentId,omitempty"`
	Priority  *Priority           `json:"priority,omitempty"`
	ProjectId openapi_types.UUID  `json:"projectId"`
	Status    *TaskStatus         `json:"status,omitempty"`
	Title     string              `json:"title"`
}

// CardMove Target column (project board: neighbours must be in that column) or status only
// (cross-project board: neighbours may be any cards of that status; the card lands in its
// project's first column of the status). Omitted neighbours append to the end.
type CardMove struct {
	// AfterId Card that will be directly above
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId Card that will be directly below
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
	ColumnId *openapi_types.UUID `json:"columnId,omitempty"`
	Status   *TaskStatus         `json:"status,omitempty"`
	Version  int                 `json:"version"`
}

// CardPage defines model for CardPage.
type CardPage struct {
	Items    []Card `json:"items"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
	Total    int    `json:"total"`
}

// CardParent defines model for CardParent.
type CardParent struct {
	Id openapi_types.UUID `json:"id"`

	// Key Example: LK-12
	Key   string `json:"key"`
	Title string `json:"title"`
}

// CardPatch Absent fields are unchanged; dueDate null clears it.
type CardPatch struct {
	AssigneeIds *[]openapi_types.UUID `json:"assigneeIds,omitempty"`
	Description *string               `json:"description,omitempty"`
	DueDate     *openapi_types.Date   `json:"dueDate,omitempty"`
	LabelIds    *[]openapi_types.UUID `json:"labelIds,omitempty"`
	Priority    *Priority             `json:"priority,omitempty"`
	Title       *string               `json:"title,omitempty"`
	Version     int                   `json:"version"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Required when the account already has a password
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     string  `json:"newPassword"`
}

// ChatBodyInput defines model for ChatBodyInput.
type ChatBodyInput struct {
	Body string `json:"body"`
}

// ChatChannel defines model for ChatChannel.
type ChatChannel struct {
	Id            openapi_types.UUID `json:"id"`
	Joined        bool               `json:"joined"`
	Kind          ChatChannelKind    `json:"kind"`
	LastMessageAt *time.Time         `json:"lastMessageAt"`
	MemberCount   int                `json:"memberCount"`

	// Mentions Of those
	Mentions int  `json:"mentions"`
	Muted    bool `json:"muted"`

	// Name Null for direct messages and for project and card conversations
	Name *string `json:"name"`

	// People Participants of a direct message
	People  []PersonRef `json:"people"`
	Starred bool        `json:"starred"`
	Topic   string      `json:"topic"`

	// Unread Messages from others since the caller last read
	Unread      int                `json:"unread"`
	WorkspaceId openapi_types.UUID `json:"workspaceId"`
}

// ChatChannelKind defines model for ChatChannel.Kind.
type ChatChannelKind string

// ChatChannelInput defines model for ChatChannelInput.
type ChatChannelInput struct {
	MemberIds *[]openapi_types.UUID `json:"memberIds,omitempty"`
	Name      string                `json:"name"`
	Private   *bool                 `json:"private,omitempty"`
	Topic     *string               `json:"topic,omitempty"`
}

// ChatChannelPatch defines model for ChatChannelPatch.
type ChatChannelPatch struct {
	Name  *string `json:"name,omitempty"`
	Topic *string `json:"topic,omitempty"`
}

// ChatDirectInput defines model for ChatDirectInput.
type ChatDirectInput struct {
	// UserIds The other participants
	UserIds []openapi_types.UUID `json:"userIds"`
}

// ChatFile defines model for ChatFile.
type ChatFile struct {
	ContentType string             `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Size        int64              `json:"size"`
	Url         string             `json:"url"`
}

// ChatHit defines model for ChatHit.
type ChatHit struct {
	Channel ChatChannel `json:"channel"`
	Message ChatMessage `json:"message"`
}

// ChatMembersInput defines model for ChatMembersInput.
type ChatMembersInput struct {
	UserIds []openapi_types.UUID `json:"userIds"`
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Author *PersonRef `json:"author"`

	// Body Markdown; mentions are written as @[Name](user-id). Empty when deleted
	Body        string             `json:"body"`
	ChannelId   openapi_types.UUID `json:"channelId"`
	CreatedAt   time.Time          `json:"createdAt"`
	Deleted     bool               `json:"deleted"`
	EditedAt    *time.Time         `json:"editedAt"`
	Files       []ChatFile         `json:"files"`
	Id          openapi_types.UUID `json:"id"`
	LastReplyAt *time.Time         `json:"lastReplyAt"`

	// MentionAll @channel, @here or @everyone
	MentionAll bool                `json:"mentionAll"`
	Mentions   []PersonRef         `json:"mentions"`
	ParentId   *openapi_types.UUID `json:"parentId"`
	Pinned     bool                `json:"pinned"`
	Reactions  []ChatReaction      `json:"reactions"`
	ReplyCount int                 `json:"replyCount"`

	// ReplyPeople Up to three people who replied
	ReplyPeople []PersonRef `json:"replyPeople"`

	// Saved In the caller's Later list
	Saved bool `json:"saved"`
}

// ChatMessageInput defines model for ChatMessageInput.
type ChatMessageInput struct {
	// Body May be empty when fileIds is not
	Body string `json:"body"`

	// FileIds Uploaded files to attach
	FileIds  *[]openapi_types.UUID `json:"fileIds,omitempty"`
	ParentId *openapi_types.UUID   `json:"parentId,omitempty"`
}

// ChatMessagePage defines model for ChatMessagePage.
type ChatMessagePage struct {
	HasMore  bool          `json:"hasMore"`
	Messages []ChatMessage `json:"messages"`
}

// ChatMuteInput defines model for ChatMuteInput.
type ChatMuteInput struct {
	Muted bool `json:"muted"`
}

// ChatPresence defines model for ChatPresence.
type ChatPresence struct {
	Online []openapi_types.UUID `json:"online"`
}

// ChatReaction defines model for ChatReaction.
type ChatReaction struct {
	Count int                  `json:"count"`
	Key   string               `json:"key"`
	Mine  bool                 `json:"mine"`
	Users []openapi_types.UUID `json:"users"`
}

// ChecklistItem defines model for ChecklistItem.
type ChecklistItem struct {
	CompletedAt *time.Time         `json:"completedAt"`
	Done        bool               `json:"done"`
	Id          openapi_types.UUID `json:"id"`
	Position    string             `json:"position"`
	Text        string             `json:"text"`
}

// ChecklistItemInput defines model for ChecklistItemInput.
type ChecklistItemInput struct {
	Text string `json:"text"`
}

// ChecklistItemPatch Any subset; `move` reorders between neighbours.
type ChecklistItemPatch struct {
	Done *bool       `json:"done,omitempty"`
	Move *Neighbours `json:"move,omitempty"`
	Text *string     `json:"text,omitempty"`
}

// ChecklistSummary defines model for ChecklistSummary.
type ChecklistSummary struct {
	Done  int `json:"done"`
	Total int `json:"total"`
}

// ColumnInput defines model for ColumnInput.
type ColumnInput struct {
	Name     string     `json:"name"`
	Status   TaskStatus `json:"status"`
	WipLimit *int       `json:"wipLimit,omitempty"`
}

// ColumnPatch Absent fields are unchanged; wipLimit null removes the limit.
type ColumnPatch struct {
	Name     *string `json:"name,omitempty"`
	WipLimit *int    `json:"wipLimit,omitempty"`
}

// Comment defines model for Comment.
type Comment struct {
	Author *PersonRef `json:"author"`

	// Body Markdown; mentions are written as @[Name](user-id)
	Body      string             `json:"body"`
	CardId    openapi_types.UUID `json:"cardId"`
	CreatedAt time.Time          `json:"createdAt"`
	EditedAt  *time.Time         `json:"editedAt"`
	Id        openapi_types.UUID `json:"id"`
	Mentions  []PersonRef        `json:"mentions"`
}

// CommentInput defines model for CommentInput.
type CommentInput struct {
	Body string `json:"body"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	// Email Email address (validated server-side)
	Email string     `json:"email"`
	Role  InviteRole `json:"role"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken struct {
	Token string `json:"token"`
}

// DailyActivity defines model for DailyActivity.
type DailyActivity struct {
	Date       openapi_types.Date `json:"date"`
	Done       int                `json:"done"`
	InProgress int                `json:"in_progress"`
	InReview   int                `json:"in_review"`

	// Todo Cards created
	Todo int `json:"todo"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	Active            int             `json:"active"`
	Activity          []ActivityItem  `json:"activity"`
	CompletedThisWeek Trend           `json:"completedThisWeek"`
	CreatedThisWeek   Trend           `json:"createdThisWeek"`
	Daily             []DailyActivity `json:"daily"`
	InReview          int             `json:"inReview"`
	Overdue           int             `json:"overdue"`
	StatusCounts      StatusCounts    `json:"statusCounts"`
	Total             int             `json:"total"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email string `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: auth.invalid_credentials
		Code    string                  `json:"code"`
		Fields  *[]FieldError           `json:"fields,omitempty"`
		Message string                  `json:"message"`
		Meta    *map[string]interface{} `json:"meta,omitempty"`
	} `json:"error"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Example: min_length
	Code   string                  `json:"code"`
	Field  string                  `json:"field"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// Invite defines model for Invite.
type Invite struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      InviteRole         `json:"role"`
}

// InvitePreview defines model for InvitePreview.
type InvitePreview struct {
	Accepted      bool       `json:"accepted"`
	Email         string     `json:"email"`
	Expired       bool       `json:"expired"`
	InviterName   *string    `json:"inviterName"`
	Role          InviteRole `json:"role"`
	WorkspaceName string     `json:"workspaceName"`
}

// InviteRole defines model for InviteRole.
type InviteRole string

// Label defines model for Label.
type Label struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Tone Tone               `json:"tone"`
}

// LabelInput defines model for LabelInput.
type LabelInput struct {
	Name string `json:"name"`
	Tone *Tone  `json:"tone,omitempty"`
}

// LabelPatch defines model for LabelPatch.
type LabelPatch struct {
	Name *string `json:"name,omitempty"`
	Tone *Tone   `json:"tone,omitempty"`
}

// Locale defines model for Locale.
type Locale string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Member defines model for Member.
type Member struct {
	JoinedAt time.Time  `json:"joinedAt"`
	Role     Role       `json:"role"`
	User     MemberUser `json:"user"`
}

// MemberUser defines model for MemberUser.
type MemberUser struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// Neighbours defines model for Neighbours.
type Neighbours struct {
	// AfterId Item that will be directly before
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId Item that will be directly after
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
}

// PersonRef defines model for PersonRef.
type PersonRef struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// Priority defines model for Priority.
type Priority string

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time           `json:"createdAt"`
	Deadline    *openapi_types.Date `json:"deadline"`
	Description string              `json:"description"`
	DoneCount   int                 `json:"doneCount"`
	Icon        ProjectIcon         `json:"icon"`
	Id          openapi_types.UUID  `json:"id"`

	// Key Example: LK
	Key       string              `json:"key"`
	Name      string              `json:"name"`
	Overdue   bool                `json:"overdue"`
	Pic       *PersonRef          `json:"pic"`
	PicRole   *Role               `json:"picRole"`
	Progress  int                 `json:"progress"`
	StartDate *openapi_types.Date `json:"startDate"`
	Status    ProjectStatus       `json:"status"`
	TaskCount int                 `json:"taskCount"`
	Team      *string             `json:"team"`
	Tone      Tone                `json:"tone"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// ProjectIcon defines model for ProjectIcon.
type ProjectIcon string

// ProjectInput defines model for ProjectInput.
type ProjectInput struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Icon        *ProjectIcon        `json:"icon,omitempty"`

	// Key 2–6 uppercase letters/digits; derived from the name when omitted
	Key       *string             `json:"key,omitempty"`
	Name      string              `json:"name"`
	PicId     *openapi_types.UUID `json:"picId,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *ProjectStatus      `json:"status,omitempty"`
	Team      *string             `json:"team,omitempty"`
	Tone      *Tone               `json:"tone,omitempty"`
}

// ProjectPage defines model for ProjectPage.
type ProjectPage struct {
	Items    []Project `json:"items"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
	Total    int       `json:"total"`
}

// ProjectPatch Absent fields are unchanged; null clears nullable fields.
type ProjectPatch struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Icon        *ProjectIcon        `json:"icon,omitempty"`
	Name        *string             `json:"name,omitempty"`
	PicId       *openapi_types.UUID `json:"picId,omitempty"`
	StartDate   *openapi_types.Date `json:"startDate,omitempty"`
	Status      *ProjectStatus      `json:"status,omitempty"`
	Team        *string             `json:"team,omitempty"`
	Tone        *Tone               `json:"tone,omitempty"`
}

// ProjectRef defines model for ProjectRef.
type ProjectRef struct {
	Icon ProjectIcon        `json:"icon"`
	Id   openapi_types.UUID `json:"id"`
	Key  string             `json:"key"`
	Name string             `json:"name"`
	Tone Tone               `json:"tone"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus string

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	Completed  int      `json:"completed"`
	InProgress int      `json:"inProgress"`
	Overdue    int      `json:"overdue"`
	Pending    int      `json:"pending"`
	Teams      []string `json:"teams"`
	Total      int      `json:"total"`
}

// RealtimeMessage defines model for RealtimeMessage.
type RealtimeMessage struct {
	ActorId *openapi_types.UUID `json:"actorId,omitempty"`
	CardId  *openapi_types.UUID `json:"cardId,omitempty"`

	// ChannelId Chat hints only
	ChannelId *openapi_types.UUID `json:"channelId,omitempty"`

	// MessageId Chat hints only
	MessageId *openapi_types.UUID `json:"messageId,omitempty"`
	ProjectId *openapi_types.UUID `json:"projectId,omitempty"`

	// Type Example: card.moved
	Type        string             `json:"type"`
	WorkspaceId openapi_types.UUID `json:"workspaceId"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email address (validated server-side)
	Email    string  `json:"email"`
	Locale   *Locale `json:"locale,omitempty"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Role defines model for Role.
type Role string

// RunningTimer defines model for RunningTimer.
type RunningTimer struct {
	Entry *TimeEntry `json:"entry,omitempty"`
}

// SavedView defines model for SavedView.
type SavedView struct {
	// Config Opaque view configuration (filters, swimlanes, project)
	Config    map[string]interface{} `json:"config"`
	CreatedAt time.Time              `json:"createdAt"`
	Id        openapi_types.UUID     `json:"id"`
	Name      string                 `json:"name"`
	UpdatedAt time.Time              `json:"updatedAt"`
}

// SavedViewInput defines model for SavedViewInput.
type SavedViewInput struct {
	Config map[string]interface{} `json:"config"`
	Name   string                 `json:"name"`
}

// SavedViewPatch defines model for SavedViewPatch.
type SavedViewPatch struct {
	Config *map[string]interface{} `json:"config,omitempty"`
	Name   *string                 `json:"name,omitempty"`
}

// Session defines model for Session.
type Session struct {
	User User `json:"user"`
}

// StatusCounts defines model for StatusCounts.
type StatusCounts struct {
	Done       int `json:"done"`
	InProgress int `json:"in_progress"`
	InReview   int `json:"in_review"`
	Todo       int `json:"todo"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TimeEntry defines model for TimeEntry.
type TimeEntry struct {
	CardId  openapi_types.UUID `json:"cardId"`
	EndedAt *time.Time         `json:"endedAt"`
	Id      openapi_types.UUID `json:"id"`

	// Manual Entered by hand rather than timed
	Manual  bool   `json:"manual"`
	Note    string `json:"note"`
	Running bool   `json:"running"`

	// Seconds Logged duration; for a running timer
	Seconds   int        `json:"seconds"`
	StartedAt time.Time  `json:"startedAt"`
	User      *PersonRef `json:"user"`
}

// TimeLogInput defines model for TimeLogInput.
type TimeLogInput struct {
	Note    *string `json:"note,omitempty"`
	Seconds int     `json:"seconds"`

	// StartedAt Defaults to "seconds ago"
	StartedAt *time.Time `json:"startedAt,omitempty"`
}

// TimeSummary defines model for TimeSummary.
type TimeSummary struct {
	Entries      []TimeEntry `json:"entries"`
	TotalSeconds int         `json:"totalSeconds"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// Tone defines model for Tone.
type Tone string

// Trend defines model for Trend.
type Trend struct {
	// ChangePct Percent change vs previous period (0 when previous is 0)
	ChangePct float32 `json:"changePct"`
	Previous  int     `json:"previous"`
	Value     int     `json:"value"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Locale *Locale `json:"locale,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string   `json:"avatarUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Email Email address (validated server-side)
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	HasPassword   bool               `json:"hasPassword"`
	Id            openapi_types.UUID `json:"id"`
	Locale        Locale             `json:"locale"`
	Name          string             `json:"name"`
	Providers     []UserProviders    `json:"providers"`
}

// UserProviders defines model for User.Providers.
type UserProviders string

// WikiAccess The caller's effective access to an element
type WikiAccess struct {
	// Role Null when the caller has no access
	Role       *WikiRole      `json:"role"`
	Via        WikiAccessVia  `json:"via"`
	Visibility WikiVisibility `json:"visibility"`

	// VisibilitySourceId The space or node that sets the effective visibility
	VisibilitySourceId openapi_types.UUID `json:"visibilitySourceId"`
}

// WikiAccessVia defines model for WikiAccess.Via.
type WikiAccessVia string

// WikiAccessSummary defines model for WikiAccessSummary.
type WikiAccessSummary struct {
	CanManage bool        `json:"canManage"`
	Grants    []WikiGrant `json:"grants"`

	// Inherited The effective visibility is set by an ancestor
	Inherited bool `json:"inherited"`

	// Own Explicit visibility on this element; null = inherits
	Own         *WikiVisibility         `json:"own,omitempty"`
	OwnerId     openapi_types.UUID      `json:"ownerId"`
	Role        *WikiRole               `json:"role"`
	Source      WikiAccessSummarySource `json:"source"`
	SourceId    openapi_types.UUID      `json:"sourceId"`
	SourceTitle string                  `json:"sourceTitle"`
	Via         WikiAccessSummaryVia    `json:"via"`
	Visibility  WikiVisibility          `json:"visibility"`

	// WorkspaceRole What workspace visibility lets every member do
	WorkspaceRole WikiWorkspaceRole `json:"workspaceRole"`
}

// WikiAccessSummarySource defines model for WikiAccessSummary.Source.
type WikiAccessSummarySource string

// WikiAccessSummaryVia defines model for WikiAccessSummary.Via.
type WikiAccessSummaryVia string

// WikiAuditEvent defines model for WikiAuditEvent.
type WikiAuditEvent struct {
	ActorId *openapi_types.UUID    `json:"actorId"`
	At      time.Time              `json:"at"`
	Data    map[string]interface{} `json:"data"`
	Id      int64                  `json:"id"`
	Kind    string                 `json:"kind"`
	NodeId  *openapi_types.UUID    `json:"nodeId"`
}

// WikiAuditPage defines model for WikiAuditPage.
type WikiAuditPage struct {
	Events []WikiAuditEvent `json:"events"`

	// Next Cursor for the next page; null at the end
	Next *int64 `json:"next"`
}

// WikiContent defines model for WikiContent.
type WikiContent struct {
	// Doc ProseMirror (TipTap) document
	Doc       map[string]interface{} `json:"doc"`
	UpdatedAt time.Time              `json:"updatedAt"`
	UpdatedBy *openapi_types.UUID    `json:"updatedBy"`

	// Version 0 until the first save; send it back with the next save
	Version int `json:"version"`
}

// WikiContentInput defines model for WikiContentInput.
type WikiContentInput struct {
	Doc map[string]interface{} `json:"doc"`

	// Version The version last read; a stale one answers 409 wiki.content_conflict
	Version int `json:"version"`
}

// WikiFile defines model for WikiFile.
type WikiFile struct {
	ContentType string             `json:"contentType"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Size        int64              `json:"size"`

	// Url Path to the file; images may be shown inline with ?inline=true
	Url string `json:"url"`
}

// WikiGrant defines model for WikiGrant.
type WikiGrant struct {
	Inherited   bool               `json:"inherited"`
	Kind        WikiPrincipalKind  `json:"kind"`
	PrincipalId openapi_types.UUID `json:"principalId"`
	Role        WikiRole           `json:"role"`
	Source      WikiGrantSource    `json:"source"`
	SourceId    openapi_types.UUID `json:"sourceId"`
	SourceTitle string             `json:"sourceTitle"`
}

// WikiGrantSource defines model for WikiGrant.Source.
type WikiGrantSource string

// WikiGrantInput defines model for WikiGrantInput.
type WikiGrantInput struct {
	Role WikiRole `json:"role"`
}

// WikiMoveInput defines model for WikiMoveInput.
type WikiMoveInput struct {
	AfterId      *openapi_types.UUID `json:"afterId,omitempty"`
	BeforeId     *openapi_types.UUID `json:"beforeId,omitempty"`
	ConfirmWiden *bool               `json:"confirmWiden,omitempty"`

	// ParentId Destination parent; null = space root
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// SpaceId Destination space (default current)
	SpaceId *openapi_types.UUID `json:"spaceId,omitempty"`
}

// WikiNode defines model for WikiNode.
type WikiNode struct {
	// Access The caller's effective access to an element
	Access         WikiAccess          `json:"access"`
	Cover          string              `json:"cover"`
	CreatedAt      time.Time           `json:"createdAt"`
	DeletedAt      *time.Time          `json:"deletedAt,omitempty"`
	Depth          int                 `json:"depth"`
	Favorite       bool                `json:"favorite"`
	FullWidth      bool                `json:"fullWidth"`
	Icon           string              `json:"icon"`
	Id             openapi_types.UUID  `json:"id"`
	Kind           WikiNodeKind        `json:"kind"`
	LastVerifiedAt *time.Time          `json:"lastVerifiedAt"`
	OwnerId        openapi_types.UUID  `json:"ownerId"`
	ParentId       *openapi_types.UUID `json:"parentId"`

	// ProjectIds Linked projects; filled when a single page is read
	ProjectIds []openapi_types.UUID `json:"projectIds"`
	Rank       string               `json:"rank"`

	// ReviewDays Days a published page stays fresh; 0 = no reminder
	ReviewDays int `json:"reviewDays"`

	// ReviewDue A published page whose review period has run out
	ReviewDue bool               `json:"reviewDue"`
	SpaceId   openapi_types.UUID `json:"spaceId"`
	Status    WikiStatus         `json:"status"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updatedAt"`

	// Visibility Explicit visibility of this node; null = inherits
	Visibility *WikiVisibility `json:"visibility"`
}

// WikiNodeKind defines model for WikiNode.Kind.
type WikiNodeKind string

// WikiNodeInput defines model for WikiNodeInput.
type WikiNodeInput struct {
	// AfterId Sibling to place the node after (default last)
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`
	Icon    *string             `json:"icon,omitempty"`
	Kind    WikiNodeInputKind   `json:"kind"`

	// Lang Language of a built-in template
	Lang     *WikiNodeInputLang  `json:"lang,omitempty"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// TemplateId builtin:<name> or a custom template id; fills a new page
	TemplateId *string `json:"templateId,omitempty"`
	Title      string  `json:"title"`
}

// WikiNodeInputKind defines model for WikiNodeInput.Kind.
type WikiNodeInputKind string

// WikiNodeInputLang Language of a built-in template
type WikiNodeInputLang string

// WikiNodePatch defines model for WikiNodePatch.
type WikiNodePatch struct {
	Cover     *string `json:"cover,omitempty"`
	FullWidth *bool   `json:"fullWidth,omitempty"`

	// Icon A Lucide icon key such as file-text; emoji are rejected
	Icon       *string               `json:"icon,omitempty"`
	ProjectIds *[]openapi_types.UUID `json:"projectIds,omitempty"`
	ReviewDays *int                  `json:"reviewDays,omitempty"`
	Status     *WikiStatus           `json:"status,omitempty"`
	Tags       *[]string             `json:"tags,omitempty"`
	Title      *string               `json:"title,omitempty"`

	// Verify Mark the page as verified now
	Verify *bool `json:"verify,omitempty"`
}

// WikiPrincipalKind defines model for WikiPrincipalKind.
type WikiPrincipalKind string

// WikiRole defines model for WikiRole.
type WikiRole string

// WikiSpace defines model for WikiSpace.
type WikiSpace struct {
	// Access The caller's effective access to an element
	Access      WikiAccess         `json:"access"`
	Color       string             `json:"color"`
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
	Id          openapi_types.UUID `json:"id"`
	MaxDepth    int                `json:"maxDepth"`
	Name        string             `json:"name"`
	OwnerId     openapi_types.UUID `json:"ownerId"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	Visibility  WikiVisibility     `json:"visibility"`
	WorkspaceId openapi_types.UUID `json:"workspaceId"`

	// WorkspaceRole What workspace visibility lets every member do
	WorkspaceRole WikiWorkspaceRole `json:"workspaceRole"`
}

// WikiSpaceInput defines model for WikiSpaceInput.
type WikiSpaceInput struct {
	Color       *string         `json:"color,omitempty"`
	Description *string         `json:"description,omitempty"`
	Icon        *string         `json:"icon,omitempty"`
	MaxDepth    *int            `json:"maxDepth,omitempty"`
	Name        string          `json:"name"`
	Visibility  *WikiVisibility `json:"visibility,omitempty"`

	// WorkspaceRole What workspace visibility lets every member do
	WorkspaceRole *WikiWorkspaceRole `json:"workspaceRole,omitempty"`
}

// WikiSpacePatch defines model for WikiSpacePatch.
type WikiSpacePatch struct {
	Color       *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	MaxDepth    *int    `json:"maxDepth,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// WikiStatus defines model for WikiStatus.
type WikiStatus string

// WikiTemplate defines model for WikiTemplate.
type WikiTemplate struct {
	Builtin     bool   `json:"builtin"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Id          string `json:"id"`
	Name        string `json:"name"`
}

// WikiTemplateInput defines model for WikiTemplateInput.
type WikiTemplateInput struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// NodeId The page whose content becomes the template
	NodeId openapi_types.UUID `json:"nodeId"`
}

// WikiTrashItem defines model for WikiTrashItem.
type WikiTrashItem struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Node      WikiNode  `json:"node"`
}

// WikiTree defines model for WikiTree.
type WikiTree struct {
	Nodes []WikiTreeNode `json:"nodes"`
	Space WikiSpace      `json:"space"`
}

// WikiTreeNode defines model for WikiTreeNode.
type WikiTreeNode struct {
	// Access The caller's effective access to an element
	Access    WikiAccess `json:"access"`
	Cover     string     `json:"cover"`
	CreatedAt time.Time  `json:"createdAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	Depth     int        `json:"depth"`

	// Detached Visible although the parent is hidden; show under "Shared with me"
	Detached       bool                `json:"detached"`
	Favorite       bool                `json:"favorite"`
	FullWidth      bool                `json:"fullWidth"`
	Icon           string              `json:"icon"`
	Id             openapi_types.UUID  `json:"id"`
	Kind           WikiTreeNodeKind    `json:"kind"`
	LastVerifiedAt *time.Time          `json:"lastVerifiedAt"`
	OwnerId        openapi_types.UUID  `json:"ownerId"`
	ParentId       *openapi_types.UUID `json:"parentId"`

	// ProjectIds Linked projects; filled when a single page is read
	ProjectIds []openapi_types.UUID `json:"projectIds"`
	Rank       string               `json:"rank"`

	// ReviewDays Days a published page stays fresh; 0 = no reminder
	ReviewDays int `json:"reviewDays"`

	// ReviewDue A published page whose review period has run out
	ReviewDue bool               `json:"reviewDue"`
	SpaceId   openapi_types.UUID `json:"spaceId"`
	Status    WikiStatus         `json:"status"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updatedAt"`

	// Visibility Explicit visibility of this node; null = inherits
	Visibility *WikiVisibility `json:"visibility"`
}

// WikiTreeNodeKind defines model for WikiTreeNode.Kind.
type WikiTreeNodeKind string

// WikiVisibility defines model for WikiVisibility.
type WikiVisibility string

// WikiVisibilityInput defines model for WikiVisibilityInput.
type WikiVisibilityInput struct {
	// Visibility Null = inherit (nodes only)
	Visibility *WikiVisibility `json:"visibility"`

	// WorkspaceRole What workspace visibility lets every member do
	WorkspaceRole *WikiWorkspaceRole `json:"workspaceRole,omitempty"`
}

// WikiWorkspaceRole What workspace visibility lets every member do
type WikiWorkspaceRole string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int                `json:"memberCount"`
	Name        string             `json:"name"`
	Role        Role               `json:"role"`
	Slug        string             `json:"slug"`
}

// WorkspaceInput defines model for WorkspaceInput.
type WorkspaceInput struct {
	Name string `json:"name"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// CardAssigneeId defines model for CardAssigneeId.
type CardAssigneeId = openapi_types.UUID

// CardDue defines model for CardDue.
type CardDue string

// CardId defines model for CardId.
type CardId = openapi_types.UUID

// CardLabelId defines model for CardLabelId.
type CardLabelId = openapi_types.UUID

// CardParentId defines model for CardParentId.
type CardParentId = openapi_types.UUID

// CardPriority defines model for CardPriority.
type CardPriority = Priority

// CardProjectId defines model for CardProjectId.
type CardProjectId = openapi_types.UUID

// CardQuery defines model for CardQuery.
type CardQuery = string

// CardStatus defines model for CardStatus.
type CardStatus = TaskStatus

// ChatChannelId defines model for ChatChannelId.
type ChatChannelId = openapi_types.UUID

// ChatMessageId defines model for ChatMessageId.
type ChatMessageId = openapi_types.UUID

// ColumnId defines model for ColumnId.
type ColumnId = openapi_types.UUID

// CommentId defines model for CommentId.
type CommentId = openapi_types.UUID

// ItemId defines model for ItemId.
type ItemId = openapi_types.UUID

// LabelId defines model for LabelId.
type LabelId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProjectId defines model for ProjectId.
type ProjectId = openapi_types.UUID

// Provider defines model for Provider.
type Provider string

// TimeEntryId defines model for TimeEntryId.
type TimeEntryId = openapi_types.UUID

// ViewId defines model for ViewId.
type ViewId = openapi_types.UUID

// WikiNodeId defines model for WikiNodeId.
type WikiNodeId = openapi_types.UUID

// WikiPrincipalId defines model for WikiPrincipalId.
type WikiPrincipalId = openapi_types.UUID

// WikiSpaceId defines model for WikiSpaceId.
type WikiSpaceId = openapi_types.UUID

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// DownloadAttachmentParams defines parameters for DownloadAttachment.
type DownloadAttachmentParams struct {
	// Inline Display images inline (other types always download)
	Inline *bool `form:"inline,omitempty" json:"inline,omitempty"`
}

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// OauthStartParams defines parameters for OauthStart.
type OauthStartParams struct {
	// Next Relative path to return to after sign-in
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// OauthStartParamsProvider defines parameters for OauthStart.
type OauthStartParamsProvider string

// CardActivityParams defines parameters for CardActivity.
type CardActivityParams struct {
	// Before Return entries older than this id
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadAttachmentMultipartBody defines parameters for UploadAttachment.
type UploadAttachmentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadChatFileMultipartBody defines parameters for UploadChatFile.
type UploadChatFileMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListChatMessagesParams defines parameters for ListChatMessages.
type ListChatMessagesParams struct {
	// Before Id of the oldest message already loaded; returns the page before it
	Before *openapi_types.UUID `form:"before,omitempty" json:"before,omitempty"`
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadWikiFileMultipartBody defines parameters for UploadWikiFile.
type UploadWikiFileMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListWikiAuditParams defines parameters for ListWikiAudit.
type ListWikiAuditParams struct {
	// Before Cursor from the previous page
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCardsParams defines parameters for ListCards.
type ListCardsParams struct {
	Status     *CardStatus     `form:"status,omitempty" json:"status,omitempty"`
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// ParentId Only subtasks of this card
	ParentId *CardParentId `form:"parentId,omitempty" json:"parentId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q        *CardQuery            `form:"q,omitempty" json:"q,omitempty"`
	Due      *ListCardsParamsDue   `form:"due,omitempty" json:"due,omitempty"`
	Sort     *ListCardsParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order    *ListCardsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Page     *Page                 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize             `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListCardsParamsDue defines parameters for ListCards.
type ListCardsParamsDue string

// ListCardsParamsSort defines parameters for ListCards.
type ListCardsParamsSort string

// ListCardsParamsOrder defines parameters for ListCards.
type ListCardsParamsOrder string

// BoardCardsParams defines parameters for BoardCards.
type BoardCardsParams struct {
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// ParentId Only subtasks of this card
	ParentId *CardParentId `form:"parentId,omitempty" json:"parentId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q   *CardQuery           `form:"q,omitempty" json:"q,omitempty"`
	Due *BoardCardsParamsDue `form:"due,omitempty" json:"due,omitempty"`
}

// BoardCardsParamsDue defines parameters for BoardCards.
type BoardCardsParamsDue string

// CardStatsParams defines parameters for CardStats.
type CardStatsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// CardStatusCountsParams defines parameters for CardStatusCounts.
type CardStatusCountsParams struct {
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// ParentId Only subtasks of this card
	ParentId *CardParentId `form:"parentId,omitempty" json:"parentId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q   *CardQuery                 `form:"q,omitempty" json:"q,omitempty"`
	Due *CardStatusCountsParamsDue `form:"due,omitempty" json:"due,omitempty"`
}

// CardStatusCountsParamsDue defines parameters for CardStatusCounts.
type CardStatusCountsParamsDue string

// SearchChatParams defines parameters for SearchChat.
type SearchChatParams struct {
	Q string `form:"q" json:"q"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Q Search in name or key
	Q        *string                     `form:"q,omitempty" json:"q,omitempty"`
	Status   *ProjectStatus              `form:"status,omitempty" json:"status,omitempty"`
	PicId    *openapi_types.UUID         `form:"picId,omitempty" json:"picId,omitempty"`
	Team     *string                     `form:"team,omitempty" json:"team,omitempty"`
	Progress *ListProjectsParamsProgress `form:"progress,omitempty" json:"progress,omitempty"`
	Deadline *ListProjectsParamsDeadline `form:"deadline,omitempty" json:"deadline,omitempty"`
	Sort     *ListProjectsParamsSort     `form:"sort,omitempty" json:"sort,omitempty"`
	Order    *ListProjectsParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
	Page     *Page                       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize                   `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListProjectsParamsProgress defines parameters for ListProjects.
type ListProjectsParamsProgress string

// ListProjectsParamsDeadline defines parameters for ListProjects.
type ListProjectsParamsDeadline string

// ListProjectsParamsSort defines parameters for ListProjects.
type ListProjectsParamsSort string

// ListProjectsParamsOrder defines parameters for ListProjects.
type ListProjectsParamsOrder string

// ListWikiTemplatesParams defines parameters for ListWikiTemplates.
type ListWikiTemplatesParams struct {
	Lang *ListWikiTemplatesParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// ListWikiTemplatesParamsLang defines parameters for ListWikiTemplates.
type ListWikiTemplatesParamsLang string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = EmailRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// UpdateCardJSONRequestBody defines body for UpdateCard for application/json ContentType.
type UpdateCardJSONRequestBody = CardPatch

// UploadAttachmentMultipartRequestBody defines body for UploadAttachment for multipart/form-data ContentType.
type UploadAttachmentMultipartRequestBody UploadAttachmentMultipartBody

// AddChecklistItemJSONRequestBody defines body for AddChecklistItem for application/json ContentType.
type AddChecklistItemJSONRequestBody = ChecklistItemInput

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CommentInput

// MoveCardJSONRequestBody defines body for MoveCard for application/json ContentType.
type MoveCardJSONRequestBody = CardMove

// LogTimeJSONRequestBody defines body for LogTime for application/json ContentType.
type LogTimeJSONRequestBody = TimeLogInput

// UpdateChatChannelJSONRequestBody defines body for UpdateChatChannel for application/json ContentType.
type UpdateChatChannelJSONRequestBody = ChatChannelPatch

// UploadChatFileMultipartRequestBody defines body for UploadChatFile for multipart/form-data ContentType.
type UploadChatFileMultipartRequestBody UploadChatFileMultipartBody

// AddChatMembersJSONRequestBody defines body for AddChatMembers for application/json ContentType.
type AddChatMembersJSONRequestBody = ChatMembersInput

// PostChatMessageJSONRequestBody defines body for PostChatMessage for application/json ContentType.
type PostChatMessageJSONRequestBody = ChatMessageInput

// MuteChatChannelJSONRequestBody defines body for MuteChatChannel for application/json ContentType.
type MuteChatChannelJSONRequestBody = ChatMuteInput

// EditChatMessageJSONRequestBody defines body for EditChatMessage for application/json ContentType.
type EditChatMessageJSONRequestBody = ChatBodyInput

// UpdateChecklistItemJSONRequestBody defines body for UpdateChecklistItem for application/json ContentType.
type UpdateChecklistItemJSONRequestBody = ChecklistItemPatch

// UpdateColumnJSONRequestBody defines body for UpdateColumn for application/json ContentType.
type UpdateColumnJSONRequestBody = ColumnPatch

// MoveColumnJSONRequestBody defines body for MoveColumn for application/json ContentType.
type MoveColumnJSONRequestBody = Neighbours

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = CommentInput

// UpdateLabelJSONRequestBody defines body for UpdateLabel for application/json ContentType.
type UpdateLabelJSONRequestBody = LabelPatch

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectPatch

// CreateColumnJSONRequestBody defines body for CreateColumn for application/json ContentType.
type CreateColumnJSONRequestBody = ColumnInput

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// UpdateSavedViewJSONRequestBody defines body for UpdateSavedView for application/json ContentType.
type UpdateSavedViewJSONRequestBody = SavedViewPatch

// UpdateWikiNodeJSONRequestBody defines body for UpdateWikiNode for application/json ContentType.
type UpdateWikiNodeJSONRequestBody = WikiNodePatch

// SaveWikiContentJSONRequestBody defines body for SaveWikiContent for application/json ContentType.
type SaveWikiContentJSONRequestBody = WikiContentInput

// UploadWikiFileMultipartRequestBody defines body for UploadWikiFile for multipart/form-data ContentType.
type UploadWikiFileMultipartRequestBody UploadWikiFileMultipartBody

// MoveWikiNodeJSONRequestBody defines body for MoveWikiNode for application/json ContentType.
type MoveWikiNodeJSONRequestBody = WikiMoveInput

// SetWikiNodeGrantJSONRequestBody defines body for SetWikiNodeGrant for application/json ContentType.
type SetWikiNodeGrantJSONRequestBody = WikiGrantInput

// SetWikiNodeVisibilityJSONRequestBody defines body for SetWikiNodeVisibility for application/json ContentType.
type SetWikiNodeVisibilityJSONRequestBody = WikiVisibilityInput

// UpdateWikiSpaceJSONRequestBody defines body for UpdateWikiSpace for application/json ContentType.
type UpdateWikiSpaceJSONRequestBody = WikiSpacePatch

// CreateWikiNodeJSONRequestBody defines body for CreateWikiNode for application/json ContentType.
type CreateWikiNodeJSONRequestBody = WikiNodeInput

// SetWikiSpaceGrantJSONRequestBody defines body for SetWikiSpaceGrant for application/json ContentType.
type SetWikiSpaceGrantJSONRequestBody = WikiGrantInput

// SetWikiSpaceVisibilityJSONRequestBody defines body for SetWikiSpaceVisibility for application/json ContentType.
type SetWikiSpaceVisibilityJSONRequestBody = WikiVisibilityInput

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = WorkspaceInput

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = WorkspaceInput

// CreateCardJSONRequestBody defines body for CreateCard for application/json ContentType.
type CreateCardJSONRequestBody = CardInput

// BulkCardsJSONRequestBody defines body for BulkCards for application/json ContentType.
type BulkCardsJSONRequestBody = BulkCardAction

// CreateChatChannelJSONRequestBody defines body for CreateChatChannel for application/json ContentType.
type CreateChatChannelJSONRequestBody = ChatChannelInput

// OpenChatDirectJSONRequestBody defines body for OpenChatDirect for application/json ContentType.
type OpenChatDirectJSONRequestBody = ChatDirectInput

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = LabelInput

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectInput

// CreateSavedViewJSONRequestBody defines body for CreateSavedView for application/json ContentType.
type CreateSavedViewJSONRequestBody = SavedViewInput

// CreateWikiSpaceJSONRequestBody defines body for CreateWikiSpace for application/json ContentType.
type CreateWikiSpaceJSONRequestBody = WikiSpaceInput

// CreateWikiTemplateJSONRequestBody defines body for CreateWikiTemplate for application/json ContentType.
type CreateWikiTemplateJSONRequestBody = WikiTemplateInput
