// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulkCardActionAction.
const (
	BulkCardActionActionDelete   BulkCardActionAction = "delete"
	BulkCardActionActionMove     BulkCardActionAction = "move"
	BulkCardActionActionPriority BulkCardActionAction = "priority"
)

// Valid indicates whether the value is a known member of the BulkCardActionAction enum.
func (e BulkCardActionAction) Valid() bool {
	switch e {
	case BulkCardActionActionDelete:
		return true
	case BulkCardActionActionMove:
		return true
	case BulkCardActionActionPriority:
		return true
	default:
		return false
	}
}

// Defines values for InviteRole.
const (
	InviteRoleAdmin  InviteRole = "admin"
	InviteRoleMember InviteRole = "member"
	InviteRoleViewer InviteRole = "viewer"
)

// Valid indicates whether the value is a known member of the InviteRole enum.
func (e InviteRole) Valid() bool {
	switch e {
	case InviteRoleAdmin:
		return true
	case InviteRoleMember:
		return true
	case InviteRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	En Locale = "en"
	Uk Locale = "uk"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case En:
		return true
	case Uk:
		return true
	default:
		return false
	}
}

// Defines values for Priority.
const (
	High   Priority = "high"
	Low    Priority = "low"
	Medium Priority = "medium"
)

// Valid indicates whether the value is a known member of the Priority enum.
func (e Priority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ProjectIcon.
const (
	Code      ProjectIcon = "code"
	Flask     ProjectIcon = "flask"
	Folder    ProjectIcon = "folder"
	Globe     ProjectIcon = "globe"
	Layers    ProjectIcon = "layers"
	Megaphone ProjectIcon = "megaphone"
	Rocket    ProjectIcon = "rocket"
	Shield    ProjectIcon = "shield"
	Sparkles  ProjectIcon = "sparkles"
	Target    ProjectIcon = "target"
)

// Valid indicates whether the value is a known member of the ProjectIcon enum.
func (e ProjectIcon) Valid() bool {
	switch e {
	case Code:
		return true
	case Flask:
		return true
	case Folder:
		return true
	case Globe:
		return true
	case Layers:
		return true
	case Megaphone:
		return true
	case Rocket:
		return true
	case Shield:
		return true
	case Sparkles:
		return true
	case Target:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusPending    ProjectStatus = "pending"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusCompleted:
		return true
	case ProjectStatusInProgress:
		return true
	case ProjectStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
	RoleOwner  Role = "owner"
	RoleViewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleMember:
		return true
	case RoleOwner:
		return true
	case RoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusDone       TaskStatus = "done"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusInReview   TaskStatus = "in_review"
	TaskStatusTodo       TaskStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusDone:
		return true
	case TaskStatusInProgress:
		return true
	case TaskStatusInReview:
		return true
	case TaskStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for Tone.
const (
	Amber   Tone = "amber"
	Neutral Tone = "neutral"
	Purple  Tone = "purple"
	Red     Tone = "red"
	Teal    Tone = "teal"
)

// Valid indicates whether the value is a known member of the Tone enum.
func (e Tone) Valid() bool {
	switch e {
	case Amber:
		return true
	case Neutral:
		return true
	case Purple:
		return true
	case Red:
		return true
	case Teal:
		return true
	default:
		return false
	}
}

// Defines values for UserProviders.
const (
	UserProvidersGithub UserProviders = "github"
	UserProvidersGoogle UserProviders = "google"
)

// Valid indicates whether the value is a known member of the UserProviders enum.
func (e UserProviders) Valid() bool {
	switch e {
	case UserProvidersGithub:
		return true
	case UserProvidersGoogle:
		return true
	default:
		return false
	}
}

// Defines values for CardDue.
const (
	CardDueMonth   CardDue = "month"
	CardDueNone    CardDue = "none"
	CardDueOverdue CardDue = "overdue"
	CardDueToday   CardDue = "today"
	CardDueWeek    CardDue = "week"
)

// Valid indicates whether the value is a known member of the CardDue enum.
func (e CardDue) Valid() bool {
	switch e {
	case CardDueMonth:
		return true
	case CardDueNone:
		return true
	case CardDueOverdue:
		return true
	case CardDueToday:
		return true
	case CardDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderGithub Provider = "github"
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderGithub:
		return true
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGithub OauthCallbackParamsProvider = "github"
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case OauthCallbackParamsProviderGithub:
		return true
	case OauthCallbackParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthStartParamsProvider.
const (
	OauthStartParamsProviderGithub OauthStartParamsProvider = "github"
	OauthStartParamsProviderGoogle OauthStartParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthStartParamsProvider enum.
func (e OauthStartParamsProvider) Valid() bool {
	switch e {
	case OauthStartParamsProviderGithub:
		return true
	case OauthStartParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsDue.
const (
	ListCardsParamsDueMonth   ListCardsParamsDue = "month"
	ListCardsParamsDueNone    ListCardsParamsDue = "none"
	ListCardsParamsDueOverdue ListCardsParamsDue = "overdue"
	ListCardsParamsDueToday   ListCardsParamsDue = "today"
	ListCardsParamsDueWeek    ListCardsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the ListCardsParamsDue enum.
func (e ListCardsParamsDue) Valid() bool {
	switch e {
	case ListCardsParamsDueMonth:
		return true
	case ListCardsParamsDueNone:
		return true
	case ListCardsParamsDueOverdue:
		return true
	case ListCardsParamsDueToday:
		return true
	case ListCardsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsSort.
const (
	ListCardsParamsSortAssignee ListCardsParamsSort = "assignee"
	ListCardsParamsSortDeadline ListCardsParamsSort = "deadline"
	ListCardsParamsSortKey      ListCardsParamsSort = "key"
	ListCardsParamsSortPosition ListCardsParamsSort = "position"
	ListCardsParamsSortPriority ListCardsParamsSort = "priority"
	ListCardsParamsSortProgress ListCardsParamsSort = "progress"
	ListCardsParamsSortProject  ListCardsParamsSort = "project"
	ListCardsParamsSortTitle    ListCardsParamsSort = "title"
	ListCardsParamsSortUpdated  ListCardsParamsSort = "updated"
)

// Valid indicates whether the value is a known member of the ListCardsParamsSort enum.
func (e ListCardsParamsSort) Valid() bool {
	switch e {
	case ListCardsParamsSortAssignee:
		return true
	case ListCardsParamsSortDeadline:
		return true
	case ListCardsParamsSortKey:
		return true
	case ListCardsParamsSortPosition:
		return true
	case ListCardsParamsSortPriority:
		return true
	case ListCardsParamsSortProgress:
		return true
	case ListCardsParamsSortProject:
		return true
	case ListCardsParamsSortTitle:
		return true
	case ListCardsParamsSortUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListCardsParamsOrder.
const (
	ListCardsParamsOrderAsc  ListCardsParamsOrder = "asc"
	ListCardsParamsOrderDesc ListCardsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListCardsParamsOrder enum.
func (e ListCardsParamsOrder) Valid() bool {
	switch e {
	case ListCardsParamsOrderAsc:
		return true
	case ListCardsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for BoardCardsParamsDue.
const (
	BoardCardsParamsDueMonth   BoardCardsParamsDue = "month"
	BoardCardsParamsDueNone    BoardCardsParamsDue = "none"
	BoardCardsParamsDueOverdue BoardCardsParamsDue = "overdue"
	BoardCardsParamsDueToday   BoardCardsParamsDue = "today"
	BoardCardsParamsDueWeek    BoardCardsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the BoardCardsParamsDue enum.
func (e BoardCardsParamsDue) Valid() bool {
	switch e {
	case BoardCardsParamsDueMonth:
		return true
	case BoardCardsParamsDueNone:
		return true
	case BoardCardsParamsDueOverdue:
		return true
	case BoardCardsParamsDueToday:
		return true
	case BoardCardsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for CardStatusCountsParamsDue.
const (
	CardStatusCountsParamsDueMonth   CardStatusCountsParamsDue = "month"
	CardStatusCountsParamsDueNone    CardStatusCountsParamsDue = "none"
	CardStatusCountsParamsDueOverdue CardStatusCountsParamsDue = "overdue"
	CardStatusCountsParamsDueToday   CardStatusCountsParamsDue = "today"
	CardStatusCountsParamsDueWeek    CardStatusCountsParamsDue = "week"
)

// Valid indicates whether the value is a known member of the CardStatusCountsParamsDue enum.
func (e CardStatusCountsParamsDue) Valid() bool {
	switch e {
	case CardStatusCountsParamsDueMonth:
		return true
	case CardStatusCountsParamsDueNone:
		return true
	case CardStatusCountsParamsDueOverdue:
		return true
	case CardStatusCountsParamsDueToday:
		return true
	case CardStatusCountsParamsDueWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsProgress.
const (
	ListProjectsParamsProgressAlmost     ListProjectsParamsProgress = "almost"
	ListProjectsParamsProgressDone       ListProjectsParamsProgress = "done"
	ListProjectsParamsProgressEarly      ListProjectsParamsProgress = "early"
	ListProjectsParamsProgressMidway     ListProjectsParamsProgress = "midway"
	ListProjectsParamsProgressNotStarted ListProjectsParamsProgress = "not_started"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsProgress enum.
func (e ListProjectsParamsProgress) Valid() bool {
	switch e {
	case ListProjectsParamsProgressAlmost:
		return true
	case ListProjectsParamsProgressDone:
		return true
	case ListProjectsParamsProgressEarly:
		return true
	case ListProjectsParamsProgressMidway:
		return true
	case ListProjectsParamsProgressNotStarted:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsDeadline.
const (
	ListProjectsParamsDeadlineLater   ListProjectsParamsDeadline = "later"
	ListProjectsParamsDeadlineMonth   ListProjectsParamsDeadline = "month"
	ListProjectsParamsDeadlineNone    ListProjectsParamsDeadline = "none"
	ListProjectsParamsDeadlineOverdue ListProjectsParamsDeadline = "overdue"
	ListProjectsParamsDeadlineWeek    ListProjectsParamsDeadline = "week"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsDeadline enum.
func (e ListProjectsParamsDeadline) Valid() bool {
	switch e {
	case ListProjectsParamsDeadlineLater:
		return true
	case ListProjectsParamsDeadlineMonth:
		return true
	case ListProjectsParamsDeadlineNone:
		return true
	case ListProjectsParamsDeadlineOverdue:
		return true
	case ListProjectsParamsDeadlineWeek:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsSort.
const (
	ListProjectsParamsSortCreated  ListProjectsParamsSort = "created"
	ListProjectsParamsSortDeadline ListProjectsParamsSort = "deadline"
	ListProjectsParamsSortName     ListProjectsParamsSort = "name"
	ListProjectsParamsSortProgress ListProjectsParamsSort = "progress"
	ListProjectsParamsSortUpdated  ListProjectsParamsSort = "updated"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsSort enum.
func (e ListProjectsParamsSort) Valid() bool {
	switch e {
	case ListProjectsParamsSortCreated:
		return true
	case ListProjectsParamsSortDeadline:
		return true
	case ListProjectsParamsSortName:
		return true
	case ListProjectsParamsSortProgress:
		return true
	case ListProjectsParamsSortUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsOrder.
const (
	ListProjectsParamsOrderAsc  ListProjectsParamsOrder = "asc"
	ListProjectsParamsOrderDesc ListProjectsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsOrder enum.
func (e ListProjectsParamsOrder) Valid() bool {
	switch e {
	case ListProjectsParamsOrderAsc:
		return true
	case ListProjectsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// ActivityEntry defines model for ActivityEntry.
type ActivityEntry struct {
	Actor *PersonRef             `json:"actor"`
	At    time.Time              `json:"at"`
	Data  map[string]interface{} `json:"data"`
	Id    int64                  `json:"id"`

	// Kind Translatable key: card.created|updated|moved|deleted, checklist.*, comment.*, attachment.*
	//
	// Example: card.moved
	Kind string `json:"kind"`
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	Actor *PersonRef `json:"actor"`
	At    time.Time  `json:"at"`
	Card  struct {
		Id    openapi_types.UUID `json:"id"`
		Key   string             `json:"key"`
		Title string             `json:"title"`
	} `json:"card"`
	From    *TaskStatus `json:"from"`
	Id      int64       `json:"id"`
	Project ProjectRef  `json:"project"`
	To      TaskStatus  `json:"to"`
}

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items      []ActivityEntry `json:"items"`
	NextBefore *int64          `json:"nextBefore"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string             `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`

	// Previewable Image the browser may display inline
	Previewable bool       `json:"previewable"`
	Size        int64      `json:"size"`
	UploadedBy  *PersonRef `json:"uploadedBy"`
}

// AuthProviders defines model for AuthProviders.
type AuthProviders struct {
	Github bool `json:"github"`
	Google bool `json:"google"`
}

// Board defines model for Board.
type Board struct {
	Columns   []BoardColumn      `json:"columns"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	ProjectId openapi_types.UUID `json:"projectId"`
}

// BoardColumn defines model for BoardColumn.
type BoardColumn struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Position string             `json:"position"`
	Status   TaskStatus         `json:"status"`
	WipLimit *int               `json:"wipLimit"`
}

// BulkCardAction defines model for BulkCardAction.
type BulkCardAction struct {
	Action   BulkCardActionAction `json:"action"`
	Ids      []openapi_types.UUID `json:"ids"`
	Priority *Priority            `json:"priority,omitempty"`
	Status   *TaskStatus          `json:"status,omitempty"`
}

// BulkCardActionAction defines model for BulkCardAction.Action.
type BulkCardActionAction string

// BulkResult defines model for BulkResult.
type BulkResult struct {
	Updated int `json:"updated"`
}

// Card defines model for Card.
type Card struct {
	Assignees       []PersonRef         `json:"assignees"`
	AttachmentCount int                 `json:"attachmentCount"`
	Checklist       ChecklistSummary    `json:"checklist"`
	ColumnId        openapi_types.UUID  `json:"columnId"`
	CommentCount    int                 `json:"commentCount"`
	CompletedAt     *time.Time          `json:"completedAt"`
	CreatedAt       time.Time           `json:"createdAt"`
	Description     string              `json:"description"`
	DueDate         *openapi_types.Date `json:"dueDate"`
	Id              openapi_types.UUID  `json:"id"`

	// Key Example: LK-12
	Key      string   `json:"key"`
	Labels   []Label  `json:"labels"`
	Number   int      `json:"number"`
	Position string   `json:"position"`
	Priority Priority `json:"priority"`

	// Progress Derived: checklist share, else workflow stage; 100 only when done (ADR 0010)
	Progress  int        `json:"progress"`
	Project   ProjectRef `json:"project"`
	Status    TaskStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updatedAt"`

	// Version Optimistic concurrency token; send it back on update/move
	Version int `json:"version"`
}

// CardBoard defines model for CardBoard.
type CardBoard struct {
	Items []Card `json:"items"`

	// Truncated More cards match than were returned
	Truncated bool `json:"truncated"`
}

// CardInput defines model for CardInput.
type CardInput struct {
	AssigneeIds *[]openapi_types.UUID `json:"assigneeIds,omitempty"`
	ColumnId    *openapi_types.UUID   `json:"columnId,omitempty"`
	Description *string               `json:"description,omitempty"`
	DueDate     *openapi_types.Date   `json:"dueDate,omitempty"`
	LabelIds    *[]openapi_types.UUID `json:"labelIds,omitempty"`
	Priority    *Priority             `json:"priority,omitempty"`
	ProjectId   openapi_types.UUID    `json:"projectId"`
	Status      *TaskStatus           `json:"status,omitempty"`
	Title       string                `json:"title"`
}

// CardMove Target column (project board: neighbours must be in that column) or status only
// (cross-project board: neighbours may be any cards of that status; the card lands in its
// project's first column of the status). Omitted neighbours append to the end.
type CardMove struct {
	// AfterId Card that will be directly above
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId Card that will be directly below
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
	ColumnId *openapi_types.UUID `json:"columnId,omitempty"`
	Status   *TaskStatus         `json:"status,omitempty"`
	Version  int                 `json:"version"`
}

// CardPage defines model for CardPage.
type CardPage struct {
	Items    []Card `json:"items"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
	Total    int    `json:"total"`
}

// CardPatch Absent fields are unchanged; dueDate null clears it.
type CardPatch struct {
	AssigneeIds *[]openapi_types.UUID `json:"assigneeIds,omitempty"`
	Description *string               `json:"description,omitempty"`
	DueDate     *openapi_types.Date   `json:"dueDate,omitempty"`
	LabelIds    *[]openapi_types.UUID `json:"labelIds,omitempty"`
	Priority    *Priority             `json:"priority,omitempty"`
	Title       *string               `json:"title,omitempty"`
	Version     int                   `json:"version"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Required when the account already has a password
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     string  `json:"newPassword"`
}

// ChecklistItem defines model for ChecklistItem.
type ChecklistItem struct {
	CompletedAt *time.Time         `json:"completedAt"`
	Done        bool               `json:"done"`
	Id          openapi_types.UUID `json:"id"`
	Position    string             `json:"position"`
	Text        string             `json:"text"`
}

// ChecklistItemInput defines model for ChecklistItemInput.
type ChecklistItemInput struct {
	Text string `json:"text"`
}

// ChecklistItemPatch Any subset; `move` reorders between neighbours.
type ChecklistItemPatch struct {
	Done *bool       `json:"done,omitempty"`
	Move *Neighbours `json:"move,omitempty"`
	Text *string     `json:"text,omitempty"`
}

// ChecklistSummary defines model for ChecklistSummary.
type ChecklistSummary struct {
	Done  int `json:"done"`
	Total int `json:"total"`
}

// ColumnInput defines model for ColumnInput.
type ColumnInput struct {
	Name     string     `json:"name"`
	Status   TaskStatus `json:"status"`
	WipLimit *int       `json:"wipLimit,omitempty"`
}

// ColumnPatch Absent fields are unchanged; wipLimit null removes the limit.
type ColumnPatch struct {
	Name     *string `json:"name,omitempty"`
	WipLimit *int    `json:"wipLimit,omitempty"`
}

// Comment defines model for Comment.
type Comment struct {
	Author *PersonRef `json:"author"`

	// Body Markdown; mentions are written as @[Name](user-id)
	Body      string             `json:"body"`
	CardId    openapi_types.UUID `json:"cardId"`
	CreatedAt time.Time          `json:"createdAt"`
	EditedAt  *time.Time         `json:"editedAt"`
	Id        openapi_types.UUID `json:"id"`
	Mentions  []PersonRef        `json:"mentions"`
}

// CommentInput defines model for CommentInput.
type CommentInput struct {
	Body string `json:"body"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	// Email Email address (validated server-side)
	Email string     `json:"email"`
	Role  InviteRole `json:"role"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken struct {
	Token string `json:"token"`
}

// DailyActivity defines model for DailyActivity.
type DailyActivity struct {
	Date       openapi_types.Date `json:"date"`
	Done       int                `json:"done"`
	InProgress int                `json:"in_progress"`
	InReview   int                `json:"in_review"`

	// Todo Cards created
	Todo int `json:"todo"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	Active            int             `json:"active"`
	Activity          []ActivityItem  `json:"activity"`
	CompletedThisWeek Trend           `json:"completedThisWeek"`
	CreatedThisWeek   Trend           `json:"createdThisWeek"`
	Daily             []DailyActivity `json:"daily"`
	InReview          int             `json:"inReview"`
	Overdue           int             `json:"overdue"`
	StatusCounts      StatusCounts    `json:"statusCounts"`
	Total             int             `json:"total"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email string `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: auth.invalid_credentials
		Code    string                  `json:"code"`
		Fields  *[]FieldError           `json:"fields,omitempty"`
		Message string                  `json:"message"`
		Meta    *map[string]interface{} `json:"meta,omitempty"`
	} `json:"error"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Example: min_length
	Code   string                  `json:"code"`
	Field  string                  `json:"field"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// Invite defines model for Invite.
type Invite struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      InviteRole         `json:"role"`
}

// InvitePreview defines model for InvitePreview.
type InvitePreview struct {
	Accepted      bool       `json:"accepted"`
	Email         string     `json:"email"`
	Expired       bool       `json:"expired"`
	InviterName   *string    `json:"inviterName"`
	Role          InviteRole `json:"role"`
	WorkspaceName string     `json:"workspaceName"`
}

// InviteRole defines model for InviteRole.
type InviteRole string

// Label defines model for Label.
type Label struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Tone Tone               `json:"tone"`
}

// LabelInput defines model for LabelInput.
type LabelInput struct {
	Name string `json:"name"`
	Tone *Tone  `json:"tone,omitempty"`
}

// LabelPatch defines model for LabelPatch.
type LabelPatch struct {
	Name *string `json:"name,omitempty"`
	Tone *Tone   `json:"tone,omitempty"`
}

// Locale defines model for Locale.
type Locale string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Member defines model for Member.
type Member struct {
	JoinedAt time.Time  `json:"joinedAt"`
	Role     Role       `json:"role"`
	User     MemberUser `json:"user"`
}

// MemberUser defines model for MemberUser.
type MemberUser struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// Neighbours defines model for Neighbours.
type Neighbours struct {
	// AfterId Item that will be directly before
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId Item that will be directly after
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
}

// PersonRef defines model for PersonRef.
type PersonRef struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// Priority defines model for Priority.
type Priority string

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time           `json:"createdAt"`
	Deadline    *openapi_types.Date `json:"deadline"`
	Description string              `json:"description"`
	DoneCount   int                 `json:"doneCount"`
	Icon        ProjectIcon         `json:"icon"`
	Id          openapi_types.UUID  `json:"id"`

	// Key Example: LK
	Key       string              `json:"key"`
	Name      string              `json:"name"`
	Overdue   bool                `json:"overdue"`
	Pic       *PersonRef          `json:"pic"`
	PicRole   *Role               `json:"picRole"`
	Progress  int                 `json:"progress"`
	StartDate *openapi_types.Date `json:"startDate"`
	Status    ProjectStatus       `json:"status"`
	TaskCount int                 `json:"taskCount"`
	Team      *string             `json:"team"`
	Tone      Tone                `json:"tone"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// ProjectIcon defines model for ProjectIcon.
type ProjectIcon string

// ProjectInput defines model for ProjectInput.
type ProjectInput struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Icon        *ProjectIcon        `json:"icon,omitempty"`

	// Key 2–6 uppercase letters/digits; derived from the name when omitted
	Key       *string             `json:"key,omitempty"`
	Name      string              `json:"name"`
	PicId     *openapi_types.UUID `json:"picId,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *ProjectStatus      `json:"status,omitempty"`
	Team      *string             `json:"team,omitempty"`
	Tone      *Tone               `json:"tone,omitempty"`
}

// ProjectPage defines model for ProjectPage.
type ProjectPage struct {
	Items    []Project `json:"items"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
	Total    int       `json:"total"`
}

// ProjectPatch Absent fields are unchanged; null clears nullable fields.
type ProjectPatch struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Icon        *ProjectIcon        `json:"icon,omitempty"`
	Name        *string             `json:"name,omitempty"`
	PicId       *openapi_types.UUID `json:"picId,omitempty"`
	StartDate   *openapi_types.Date `json:"startDate,omitempty"`
	Status      *ProjectStatus      `json:"status,omitempty"`
	Team        *string             `json:"team,omitempty"`
	Tone        *Tone               `json:"tone,omitempty"`
}

// ProjectRef defines model for ProjectRef.
type ProjectRef struct {
	Icon ProjectIcon        `json:"icon"`
	Id   openapi_types.UUID `json:"id"`
	Key  string             `json:"key"`
	Name string             `json:"name"`
	Tone Tone               `json:"tone"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus string

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	Completed  int      `json:"completed"`
	InProgress int      `json:"inProgress"`
	Overdue    int      `json:"overdue"`
	Pending    int      `json:"pending"`
	Teams      []string `json:"teams"`
	Total      int      `json:"total"`
}

// RealtimeMessage defines model for RealtimeMessage.
type RealtimeMessage struct {
	ActorId   *openapi_types.UUID `json:"actorId,omitempty"`
	CardId    *openapi_types.UUID `json:"cardId,omitempty"`
	ProjectId *openapi_types.UUID `json:"projectId,omitempty"`

	// Type Example: card.moved
	Type        string             `json:"type"`
	WorkspaceId openapi_types.UUID `json:"workspaceId"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email address (validated server-side)
	Email    string  `json:"email"`
	Locale   *Locale `json:"locale,omitempty"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Role defines model for Role.
type Role string

// SavedView defines model for SavedView.
type SavedView struct {
	// Config Opaque view configuration (filters, swimlanes, project)
	Config    map[string]interface{} `json:"config"`
	CreatedAt time.Time              `json:"createdAt"`
	Id        openapi_types.UUID     `json:"id"`
	Name      string                 `json:"name"`
	UpdatedAt time.Time              `json:"updatedAt"`
}

// SavedViewInput defines model for SavedViewInput.
type SavedViewInput struct {
	Config map[string]interface{} `json:"config"`
	Name   string                 `json:"name"`
}

// SavedViewPatch defines model for SavedViewPatch.
type SavedViewPatch struct {
	Config *map[string]interface{} `json:"config,omitempty"`
	Name   *string                 `json:"name,omitempty"`
}

// Session defines model for Session.
type Session struct {
	User User `json:"user"`
}

// StatusCounts defines model for StatusCounts.
type StatusCounts struct {
	Done       int `json:"done"`
	InProgress int `json:"in_progress"`
	InReview   int `json:"in_review"`
	Todo       int `json:"todo"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// Tone defines model for Tone.
type Tone string

// Trend defines model for Trend.
type Trend struct {
	// ChangePct Percent change vs previous period (0 when previous is 0)
	ChangePct float32 `json:"changePct"`
	Previous  int     `json:"previous"`
	Value     int     `json:"value"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Locale *Locale `json:"locale,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string   `json:"avatarUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Email Email address (validated server-side)
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	HasPassword   bool               `json:"hasPassword"`
	Id            openapi_types.UUID `json:"id"`
	Locale        Locale             `json:"locale"`
	Name          string             `json:"name"`
	Providers     []UserProviders    `json:"providers"`
}

// UserProviders defines model for User.Providers.
type UserProviders string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int                `json:"memberCount"`
	Name        string             `json:"name"`
	Role        Role               `json:"role"`
	Slug        string             `json:"slug"`
}

// WorkspaceInput defines model for WorkspaceInput.
type WorkspaceInput struct {
	Name string `json:"name"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// CardAssigneeId defines model for CardAssigneeId.
type CardAssigneeId = openapi_types.UUID

// CardDue defines model for CardDue.
type CardDue string

// CardId defines model for CardId.
type CardId = openapi_types.UUID

// CardLabelId defines model for CardLabelId.
type CardLabelId = openapi_types.UUID

// CardPriority defines model for CardPriority.
type CardPriority = Priority

// CardProjectId defines model for CardProjectId.
type CardProjectId = openapi_types.UUID

// CardQuery defines model for CardQuery.
type CardQuery = string

// CardStatus defines model for CardStatus.
type CardStatus = TaskStatus

// ColumnId defines model for ColumnId.
type ColumnId = openapi_types.UUID

// CommentId defines model for CommentId.
type CommentId = openapi_types.UUID

// ItemId defines model for ItemId.
type ItemId = openapi_types.UUID

// LabelId defines model for LabelId.
type LabelId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProjectId defines model for ProjectId.
type ProjectId = openapi_types.UUID

// Provider defines model for Provider.
type Provider string

// ViewId defines model for ViewId.
type ViewId = openapi_types.UUID

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// DownloadAttachmentParams defines parameters for DownloadAttachment.
type DownloadAttachmentParams struct {
	// Inline Display images inline (other types always download)
	Inline *bool `form:"inline,omitempty" json:"inline,omitempty"`
}

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// OauthStartParams defines parameters for OauthStart.
type OauthStartParams struct {
	// Next Relative path to return to after sign-in
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// OauthStartParamsProvider defines parameters for OauthStart.
type OauthStartParamsProvider string

// CardActivityParams defines parameters for CardActivity.
type CardActivityParams struct {
	// Before Return entries older than this id
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadAttachmentMultipartBody defines parameters for UploadAttachment.
type UploadAttachmentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListCardsParams defines parameters for ListCards.
type ListCardsParams struct {
	Status     *CardStatus     `form:"status,omitempty" json:"status,omitempty"`
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q        *CardQuery            `form:"q,omitempty" json:"q,omitempty"`
	Due      *ListCardsParamsDue   `form:"due,omitempty" json:"due,omitempty"`
	Sort     *ListCardsParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order    *ListCardsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Page     *Page                 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize             `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListCardsParamsDue defines parameters for ListCards.
type ListCardsParamsDue string

// ListCardsParamsSort defines parameters for ListCards.
type ListCardsParamsSort string

// ListCardsParamsOrder defines parameters for ListCards.
type ListCardsParamsOrder string

// BoardCardsParams defines parameters for BoardCards.
type BoardCardsParams struct {
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q   *CardQuery           `form:"q,omitempty" json:"q,omitempty"`
	Due *BoardCardsParamsDue `form:"due,omitempty" json:"due,omitempty"`
}

// BoardCardsParamsDue defines parameters for BoardCards.
type BoardCardsParamsDue string

// CardStatsParams defines parameters for CardStats.
type CardStatsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// CardStatusCountsParams defines parameters for CardStatusCounts.
type CardStatusCountsParams struct {
	ProjectId  *CardProjectId  `form:"projectId,omitempty" json:"projectId,omitempty"`
	AssigneeId *CardAssigneeId `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Priority   *CardPriority   `form:"priority,omitempty" json:"priority,omitempty"`
	LabelId    *CardLabelId    `form:"labelId,omitempty" json:"labelId,omitempty"`

	// Q Search in title or key (e.g. LK-12)
	Q   *CardQuery                 `form:"q,omitempty" json:"q,omitempty"`
	Due *CardStatusCountsParamsDue `form:"due,omitempty" json:"due,omitempty"`
}

// CardStatusCountsParamsDue defines parameters for CardStatusCounts.
type CardStatusCountsParamsDue string

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Q Search in name or key
	Q        *string                     `form:"q,omitempty" json:"q,omitempty"`
	Status   *ProjectStatus              `form:"status,omitempty" json:"status,omitempty"`
	PicId    *openapi_types.UUID         `form:"picId,omitempty" json:"picId,omitempty"`
	Team     *string                     `form:"team,omitempty" json:"team,omitempty"`
	Progress *ListProjectsParamsProgress `form:"progress,omitempty" json:"progress,omitempty"`
	Deadline *ListProjectsParamsDeadline `form:"deadline,omitempty" json:"deadline,omitempty"`
	Sort     *ListProjectsParamsSort     `form:"sort,omitempty" json:"sort,omitempty"`
	Order    *ListProjectsParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
	Page     *Page                       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize                   `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListProjectsParamsProgress defines parameters for ListProjects.
type ListProjectsParamsProgress string

// ListProjectsParamsDeadline defines parameters for ListProjects.
type ListProjectsParamsDeadline string

// ListProjectsParamsSort defines parameters for ListProjects.
type ListProjectsParamsSort string

// ListProjectsParamsOrder defines parameters for ListProjects.
type ListProjectsParamsOrder string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = EmailRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// UpdateCardJSONRequestBody defines body for UpdateCard for application/json ContentType.
type UpdateCardJSONRequestBody = CardPatch

// UploadAttachmentMultipartRequestBody defines body for UploadAttachment for multipart/form-data ContentType.
type UploadAttachmentMultipartRequestBody UploadAttachmentMultipartBody

// AddChecklistItemJSONRequestBody defines body for AddChecklistItem for application/json ContentType.
type AddChecklistItemJSONRequestBody = ChecklistItemInput

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CommentInput

// MoveCardJSONRequestBody defines body for MoveCard for application/json ContentType.
type MoveCardJSONRequestBody = CardMove

// UpdateChecklistItemJSONRequestBody defines body for UpdateChecklistItem for application/json ContentType.
type UpdateChecklistItemJSONRequestBody = ChecklistItemPatch

// UpdateColumnJSONRequestBody defines body for UpdateColumn for application/json ContentType.
type UpdateColumnJSONRequestBody = ColumnPatch

// MoveColumnJSONRequestBody defines body for MoveColumn for application/json ContentType.
type MoveColumnJSONRequestBody = Neighbours

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = CommentInput

// UpdateLabelJSONRequestBody defines body for UpdateLabel for application/json ContentType.
type UpdateLabelJSONRequestBody = LabelPatch

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectPatch

// CreateColumnJSONRequestBody defines body for CreateColumn for application/json ContentType.
type CreateColumnJSONRequestBody = ColumnInput

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// UpdateSavedViewJSONRequestBody defines body for UpdateSavedView for application/json ContentType.
type UpdateSavedViewJSONRequestBody = SavedViewPatch

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = WorkspaceInput

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = WorkspaceInput

// CreateCardJSONRequestBody defines body for CreateCard for application/json ContentType.
type CreateCardJSONRequestBody = CardInput

// BulkCardsJSONRequestBody defines body for BulkCards for application/json ContentType.
type BulkCardsJSONRequestBody = BulkCardAction

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = LabelInput

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectInput

// CreateSavedViewJSONRequestBody defines body for CreateSavedView for application/json ContentType.
type CreateSavedViewJSONRequestBody = SavedViewInput
