// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, key, name, description, status, pic_user_id, team, icon, tone, start_date, deadline, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12)
RETURNING id, workspace_id, key, name, description, status, pic_user_id, team, icon, tone, start_date, deadline, task_count, done_count, created_by, created_at, updated_at, archived_at
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID
	Key         string
	Name        string
	Description string
	Status      string
	PicUserID   uuid.NullUUID
	Team        *string
	Icon        string
	Tone        string
	StartDate   *time.Time
	Deadline    *time.Time
	CreatedBy   uuid.NullUUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.PicUserID,
		arg.Team,
		arg.Icon,
		arg.Tone,
		arg.StartDate,
		arg.Deadline,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PicUserID,
		&i.Team,
		&i.Icon,
		&i.Tone,
		&i.StartDate,
		&i.Deadline,
		&i.TaskCount,
		&i.DoneCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const distinctTeams = `-- name: DistinctTeams :many
SELECT DISTINCT team::text FROM projects
WHERE workspace_id = $1 AND archived_at IS NULL AND team IS NOT NULL
ORDER BY 1
`

func (q *Queries) DistinctTeams(ctx context.Context, workspaceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, distinctTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var team string
		if err := rows.Scan(&team); err != nil {
			return nil, err
		}
		items = append(items, team)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, key, name, description, status, pic_user_id, team, icon, tone, start_date, deadline, task_count, done_count, created_by, created_at, updated_at, archived_at FROM projects WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PicUserID,
		&i.Team,
		&i.Icon,
		&i.Tone,
		&i.StartDate,
		&i.Deadline,
		&i.TaskCount,
		&i.DoneCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const projectSummary = `-- name: ProjectSummary :one
SELECT count(*)::int AS total,
       count(*) FILTER (WHERE status = 'completed')::int AS completed,
       count(*) FILTER (WHERE status = 'in_progress')::int AS in_progress,
       count(*) FILTER (WHERE status = 'pending')::int AS pending,
       count(*) FILTER (WHERE status <> 'completed' AND deadline < $1::date)::int AS overdue
FROM projects WHERE workspace_id = $2 AND archived_at IS NULL
`

type ProjectSummaryParams struct {
	Today       time.Time
	WorkspaceID uuid.UUID
}

type ProjectSummaryRow struct {
	Total      int32
	Completed  int32
	InProgress int32
	Pending    int32
	Overdue    int32
}

func (q *Queries) ProjectSummary(ctx context.Context, arg ProjectSummaryParams) (ProjectSummaryRow, error) {
	row := q.db.QueryRow(ctx, projectSummary, arg.Today, arg.WorkspaceID)
	var i ProjectSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.InProgress,
		&i.Pending,
		&i.Overdue,
	)
	return i, err
}

const projectsByIDs = `-- name: ProjectsByIDs :many
SELECT id, workspace_id, key, name, icon, tone FROM projects WHERE id = ANY($1::uuid[])
`

type ProjectsByIDsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Key         string
	Name        string
	Icon        string
	Tone        string
}

func (q *Queries) ProjectsByIDs(ctx context.Context, ids []uuid.UUID) ([]ProjectsByIDsRow, error) {
	rows, err := q.db.Query(ctx, projectsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsByIDsRow{}
	for rows.Next() {
		var i ProjectsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Name,
			&i.Icon,
			&i.Tone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectCounts = `-- name: SetProjectCounts :exec
UPDATE projects SET task_count = $1, done_count = $2 WHERE id = $3
`

type SetProjectCountsParams struct {
	TaskCount int32
	DoneCount int32
	ID        uuid.UUID
}

func (q *Queries) SetProjectCounts(ctx context.Context, arg SetProjectCountsParams) error {
	_, err := q.db.Exec(ctx, setProjectCounts, arg.TaskCount, arg.DoneCount, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name        = COALESCE($1, name),
    description = COALESCE($2, description),
    status      = COALESCE($3, status),
    icon        = COALESCE($4, icon),
    tone        = COALESCE($5, tone),
    pic_user_id = CASE WHEN $6::bool THEN $7 ELSE pic_user_id END,
    team        = CASE WHEN $8::bool THEN $9 ELSE team END,
    start_date  = CASE WHEN $10::bool THEN $11 ELSE start_date END,
    deadline    = CASE WHEN $12::bool THEN $13 ELSE deadline END
WHERE id = $14 AND archived_at IS NULL
RETURNING id, workspace_id, key, name, description, status, pic_user_id, team, icon, tone, start_date, deadline, task_count, done_count, created_by, created_at, updated_at, archived_at
`

type UpdateProjectParams struct {
	Name        *string
	Description *string
	Status      *string
	Icon        *string
	Tone        *string
	SetPic      bool
	PicUserID   uuid.NullUUID
	SetTeam     bool
	Team        *string
	SetStart    bool
	StartDate   *time.Time
	SetDeadline bool
	Deadline    *time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Icon,
		arg.Tone,
		arg.SetPic,
		arg.PicUserID,
		arg.SetTeam,
		arg.Team,
		arg.SetStart,
		arg.StartDate,
		arg.SetDeadline,
		arg.Deadline,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PicUserID,
		&i.Team,
		&i.Icon,
		&i.Tone,
		&i.StartDate,
		&i.Deadline,
		&i.TaskCount,
		&i.DoneCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
