// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int FROM notifications WHERE user_id = $1 AND workspace_id = $2 AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.UserID, arg.WorkspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (user_id, workspace_id, kind, actor_id, card_id, project_id, channel_id, message_id, title, body)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, workspace_id, kind, actor_id, card_id, project_id, channel_id, message_id, title, body, created_at, read_at
`

type InsertNotificationParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	ActorID     uuid.NullUUID
	CardID      uuid.NullUUID
	ProjectID   uuid.NullUUID
	ChannelID   uuid.NullUUID
	MessageID   uuid.NullUUID
	Title       string
	Body        string
}

// notifications module queries (sqlc).
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.ActorID,
		arg.CardID,
		arg.ProjectID,
		arg.ChannelID,
		arg.MessageID,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ActorID,
		&i.CardID,
		&i.ProjectID,
		&i.ChannelID,
		&i.MessageID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, workspace_id, kind, actor_id, card_id, project_id, channel_id, message_id, title, body, created_at, read_at FROM notifications
WHERE user_id = $1 AND workspace_id = $2 AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotificationsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Limit       int32
	Before      *time.Time
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.WorkspaceID,
		arg.Limit,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ActorID,
			&i.CardID,
			&i.ProjectID,
			&i.ChannelID,
			&i.MessageID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND workspace_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UserID, arg.WorkspaceID)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND workspace_id = $2 AND read_at IS NULL AND id = ANY($3::uuid[])
`

type MarkNotificationsReadParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Column3     []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.WorkspaceID, arg.Column3)
	return err
}
