// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
)

type Querier interface {
	CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error)
	// notifications module queries (sqlc).
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
}

var _ Querier = (*Queries)(nil)
