import type { Config } from 'tailwindcss';

const rgb = (name: string) => `rgb(var(--c-${name}) / <alpha-value>)`;

const colorNames = [
  'primary',
  'primary-hover',
  'primary-solid',
  'primary-solid-hover',
  'primary-soft',
  'primary-subtle',
  'primary-border',
  'primary-ink',
  'on-primary',
  'bg',
  'surface',
  'surface-muted',
  'surface-sunken',
  'overlay',
  'border',
  'border-subtle',
  'border-strong',
  'text',
  'text-secondary',
  'text-muted',
  'text-faint',
  'todo',
  'todo-soft',
  'todo-ink',
  'progress',
  'progress-bar',
  'progress-soft',
  'progress-ink',
  'review',
  'review-bar',
  'review-soft',
  'review-ink',
  'done',
  'done-soft',
  'done-ink',
  'danger',
  'danger-soft',
  'danger-ink',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
] as const;

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: Object.fromEntries(colorNames.map((n) => [n, rgb(n)])),
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem' }],
        xs: ['0.75rem', { lineHeight: '1.125rem' }],
        sm: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['0.875rem', { lineHeight: '1.375rem' }],
        md: ['0.9375rem', { lineHeight: '1.5rem' }],
        lg: ['1.0625rem', { lineHeight: '1.625rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.625rem', { lineHeight: '2rem' }],
        '3xl': ['2rem', { lineHeight: '2.375rem' }],
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
      },
      boxShadow: {
        xs: 'var(--sh-xs)',
        sm: 'var(--sh-sm)',
        md: 'var(--sh-md)',
        lg: 'var(--sh-lg)',
        drag: 'var(--sh-drag)',
        primary: 'var(--sh-primary)',
        focus: 'var(--sh-focus)',
      },
      spacing: {
        sidebar: 'var(--sidebar-w)',
        'sidebar-collapsed': 'var(--sidebar-w-collapsed)',
        header: 'var(--header-h)',
        row: 'var(--row-h)',
        control: 'var(--control-h)',
        'control-sm': 'var(--control-h-sm)',
      },
      backgroundImage: {
        announce: 'var(--g-announce)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
      },
      transitionDuration: {
        micro: 'var(--dur-micro)',
        ui: 'var(--dur-ui)',
        large: 'var(--dur-large)',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.4s var(--ease-out) infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
