/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue the CSRF cookie */
        get: operations["getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which OAuth providers are configured */
        get: operations["getAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauthStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces the caller belongs to (a personal one is created on first call if none) */
        get: operations["listWorkspaces"];
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member (or leave, when userId is the caller) */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listInvites"];
        put?: never;
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                inviteId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        get: operations["previewInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/projects/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["projectSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["archiveProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/board": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listCards"];
        put?: never;
        post: operations["createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/cards/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["cardStatusCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/cards/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/cards/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["cardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["getCard"];
        put?: never;
        post?: never;
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        patch: operations["updateCard"];
        trace?: never;
    };
    "/cards/{cardId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/board/columns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Adds a custom column right after the last column of its status. */
        post: operations["createColumn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/columns/{columnId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: components["parameters"]["ColumnId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Only empty columns can be deleted, and every status keeps at least one column. */
        delete: operations["deleteColumn"];
        options?: never;
        head?: never;
        patch: operations["updateColumn"];
        trace?: never;
    };
    "/columns/{columnId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: components["parameters"]["ColumnId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveColumn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/views": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listSavedViews"];
        put?: never;
        post: operations["createSavedView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSavedView"];
        options?: never;
        head?: never;
        patch: operations["updateSavedView"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/cards/board": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** @description Every card matching the filters in board order (position), capped at 3000. */
        get: operations["boardCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listLabels"];
        put?: never;
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLabel"];
        options?: never;
        head?: never;
        patch: operations["updateLabel"];
        trace?: never;
    };
    "/cards/{cardId}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["listChecklist"];
        put?: never;
        post: operations["addChecklistItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist-items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteChecklistItem"];
        options?: never;
        head?: never;
        patch: operations["updateChecklistItem"];
        trace?: never;
    };
    "/cards/{cardId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["listComments"];
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch: operations["updateComment"];
        trace?: never;
    };
    "/cards/{cardId}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["listAttachments"];
        put?: never;
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["cardActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * @description Server-Sent Events stream of change hints for the workspace. Events: `ready` (once),
         *     `change` (data: RealtimeMessage), `resync` (messages may have been missed — refetch).
         */
        get: operations["workspaceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/i18n/error-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listErrorCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @example auth.invalid_credentials */
                code: string;
                message: string;
                fields?: components["schemas"]["FieldError"][];
                meta?: {
                    [key: string]: unknown;
                };
            };
        };
        FieldError: {
            field: string;
            /** @example min_length */
            code: string;
            params?: {
                [key: string]: unknown;
            };
        };
        CsrfToken: {
            token: string;
        };
        AuthProviders: {
            google: boolean;
            github: boolean;
        };
        /** @enum {string} */
        Locale: "en" | "uk";
        User: {
            /** Format: uuid */
            id: string;
            /** @description Email address (validated server-side) */
            email: string;
            name: string;
            locale: components["schemas"]["Locale"];
            avatarUrl: string | null;
            emailVerified: boolean;
            hasPassword: boolean;
            providers: ("google" | "github")[];
            /** Format: date-time */
            createdAt: string;
        };
        Session: {
            user: components["schemas"]["User"];
        };
        RegisterRequest: {
            name: string;
            /** @description Email address (validated server-side) */
            email: string;
            password: string;
            locale?: components["schemas"]["Locale"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        TokenRequest: {
            token: string;
        };
        EmailRequest: {
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        ChangePasswordRequest: {
            /** @description Required when the account already has a password */
            currentPassword?: string;
            newPassword: string;
        };
        UpdateProfileRequest: {
            name?: string;
            locale?: components["schemas"]["Locale"];
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member" | "viewer";
        /** @enum {string} */
        InviteRole: "admin" | "member" | "viewer";
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            role: components["schemas"]["Role"];
            memberCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        WorkspaceInput: {
            name: string;
        };
        MemberUser: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            avatarUrl: string | null;
        };
        Member: {
            user: components["schemas"]["MemberUser"];
            role: components["schemas"]["Role"];
            /** Format: date-time */
            joinedAt: string;
        };
        UpdateMemberRequest: {
            role: components["schemas"]["Role"];
        };
        Invite: {
            /** Format: uuid */
            id: string;
            email: string;
            role: components["schemas"]["InviteRole"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateInviteRequest: {
            /** @description Email address (validated server-side) */
            email: string;
            role: components["schemas"]["InviteRole"];
        };
        InvitePreview: {
            workspaceName: string;
            inviterName: string | null;
            email: string;
            role: components["schemas"]["InviteRole"];
            expired: boolean;
            accepted: boolean;
        };
        /** @enum {string} */
        TaskStatus: "todo" | "in_progress" | "in_review" | "done";
        /** @enum {string} */
        Priority: "high" | "medium" | "low";
        /** @enum {string} */
        ProjectStatus: "pending" | "in_progress" | "completed";
        /** @enum {string} */
        Tone: "teal" | "amber" | "purple" | "red" | "neutral";
        /** @enum {string} */
        ProjectIcon: "folder" | "rocket" | "shield" | "code" | "target" | "sparkles" | "globe" | "megaphone" | "layers" | "flask";
        PersonRef: {
            /** Format: uuid */
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        ProjectRef: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            tone: components["schemas"]["Tone"];
            icon: components["schemas"]["ProjectIcon"];
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** @example LK */
            key: string;
            name: string;
            description: string;
            status: components["schemas"]["ProjectStatus"];
            overdue: boolean;
            pic: components["schemas"]["PersonRef"] | null;
            picRole: components["schemas"]["Role"] | null;
            team: string | null;
            icon: components["schemas"]["ProjectIcon"];
            tone: components["schemas"]["Tone"];
            /** Format: date */
            startDate: string | null;
            /** Format: date */
            deadline: string | null;
            taskCount: number;
            doneCount: number;
            progress: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectInput: {
            name: string;
            /** @description 2–6 uppercase letters/digits; derived from the name when omitted */
            key?: string;
            description?: string;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: uuid */
            picId?: string;
            team?: string;
            icon?: components["schemas"]["ProjectIcon"];
            tone?: components["schemas"]["Tone"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            deadline?: string;
        };
        /** @description Absent fields are unchanged; null clears nullable fields. */
        ProjectPatch: {
            name?: string;
            description?: string;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: uuid */
            picId?: string | null;
            team?: string | null;
            icon?: components["schemas"]["ProjectIcon"];
            tone?: components["schemas"]["Tone"];
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            deadline?: string | null;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            total: number;
            page: number;
            pageSize: number;
        };
        ProjectSummary: {
            total: number;
            completed: number;
            inProgress: number;
            pending: number;
            overdue: number;
            teams: string[];
        };
        BoardColumn: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["TaskStatus"];
            position: string;
            wipLimit: number | null;
        };
        Board: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            columns: components["schemas"]["BoardColumn"][];
        };
        Card: {
            /** Format: uuid */
            id: string;
            /** @example LK-12 */
            key: string;
            number: number;
            title: string;
            description: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: uuid */
            columnId: string;
            priority: components["schemas"]["Priority"];
            /** @description Derived: checklist share, else workflow stage; 100 only when done (ADR 0010) */
            progress: number;
            /** Format: date */
            dueDate: string | null;
            project: components["schemas"]["ProjectRef"];
            assignees: components["schemas"]["PersonRef"][];
            labels: components["schemas"]["Label"][];
            checklist: components["schemas"]["ChecklistSummary"];
            commentCount: number;
            attachmentCount: number;
            position: string;
            /** @description Optimistic concurrency token; send it back on update/move */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        CardInput: {
            /** Format: uuid */
            projectId: string;
            title: string;
            description?: string;
            status?: components["schemas"]["TaskStatus"];
            /** Format: uuid */
            columnId?: string;
            priority?: components["schemas"]["Priority"];
            /** Format: date */
            dueDate?: string;
            assigneeIds?: string[];
            labelIds?: string[];
        };
        /** @description Absent fields are unchanged; dueDate null clears it. */
        CardPatch: {
            version: number;
            title?: string;
            description?: string;
            priority?: components["schemas"]["Priority"];
            /** Format: date */
            dueDate?: string | null;
            assigneeIds?: string[];
            labelIds?: string[];
        };
        /**
         * @description Target column (project board: neighbours must be in that column) or status only
         *     (cross-project board: neighbours may be any cards of that status; the card lands in its
         *     project's first column of the status). Omitted neighbours append to the end.
         */
        CardMove: {
            version: number;
            /** Format: uuid */
            columnId?: string;
            status?: components["schemas"]["TaskStatus"];
            /**
             * Format: uuid
             * @description Card that will be directly above
             */
            afterId?: string | null;
            /**
             * Format: uuid
             * @description Card that will be directly below
             */
            beforeId?: string | null;
        };
        CardBoard: {
            items: components["schemas"]["Card"][];
            /** @description More cards match than were returned */
            truncated: boolean;
        };
        Label: {
            /** Format: uuid */
            id: string;
            name: string;
            tone: components["schemas"]["Tone"];
        };
        LabelInput: {
            name: string;
            tone?: components["schemas"]["Tone"];
        };
        LabelPatch: {
            name?: string;
            tone?: components["schemas"]["Tone"];
        };
        ChecklistSummary: {
            total: number;
            done: number;
        };
        ChecklistItem: {
            /** Format: uuid */
            id: string;
            text: string;
            done: boolean;
            position: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        ChecklistItemInput: {
            text: string;
        };
        /** @description Any subset; `move` reorders between neighbours. */
        ChecklistItemPatch: {
            text?: string;
            done?: boolean;
            move?: components["schemas"]["Neighbours"];
        };
        Neighbours: {
            /**
             * Format: uuid
             * @description Item that will be directly before
             */
            afterId?: string | null;
            /**
             * Format: uuid
             * @description Item that will be directly after
             */
            beforeId?: string | null;
        };
        ColumnInput: {
            name: string;
            status: components["schemas"]["TaskStatus"];
            wipLimit?: number | null;
        };
        /** @description Absent fields are unchanged; wipLimit null removes the limit. */
        ColumnPatch: {
            name?: string;
            wipLimit?: number | null;
        };
        SavedView: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Opaque view configuration (filters, swimlanes, project) */
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SavedViewInput: {
            name: string;
            config: {
                [key: string]: unknown;
            };
        };
        SavedViewPatch: {
            name?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        Comment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cardId: string;
            author: components["schemas"]["PersonRef"] | null;
            /** @description Markdown; mentions are written as @[Name](user-id) */
            body: string;
            mentions: components["schemas"]["PersonRef"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt: string | null;
        };
        CommentInput: {
            body: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            name: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /** @description Image the browser may display inline */
            previewable: boolean;
            uploadedBy: components["schemas"]["PersonRef"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityEntry: {
            /** Format: int64 */
            id: number;
            /**
             * @description Translatable key: card.created|updated|moved|deleted, checklist.*, comment.*, attachment.*
             * @example card.moved
             */
            kind: string;
            data: {
                [key: string]: unknown;
            };
            actor: components["schemas"]["PersonRef"] | null;
            /** Format: date-time */
            at: string;
        };
        ActivityPage: {
            items: components["schemas"]["ActivityEntry"][];
            /** Format: int64 */
            nextBefore: number | null;
        };
        RealtimeMessage: {
            /** @example card.moved */
            type: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            cardId?: string;
            /** Format: uuid */
            actorId?: string;
        };
        CardPage: {
            items: components["schemas"]["Card"][];
            total: number;
            page: number;
            pageSize: number;
        };
        StatusCounts: {
            todo: number;
            in_progress: number;
            in_review: number;
            done: number;
        };
        BulkCardAction: {
            ids: string[];
            /** @enum {string} */
            action: "move" | "priority" | "delete";
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["Priority"];
        };
        BulkResult: {
            updated: number;
        };
        DailyActivity: {
            /** Format: date */
            date: string;
            /** @description Cards created */
            todo: number;
            in_progress: number;
            in_review: number;
            done: number;
        };
        ActivityItem: {
            /** Format: int64 */
            id: number;
            card: {
                /** Format: uuid */
                id: string;
                key: string;
                title: string;
            };
            project: components["schemas"]["ProjectRef"];
            actor: components["schemas"]["PersonRef"] | null;
            from: components["schemas"]["TaskStatus"] | null;
            to: components["schemas"]["TaskStatus"];
            /** Format: date-time */
            at: string;
        };
        Trend: {
            value: number;
            previous: number;
            /** @description Percent change vs previous period (0 when previous is 0) */
            changePct: number;
        };
        DashboardStats: {
            active: number;
            total: number;
            inReview: number;
            overdue: number;
            completedThisWeek: components["schemas"]["Trend"];
            createdThisWeek: components["schemas"]["Trend"];
            statusCounts: components["schemas"]["StatusCounts"];
            daily: components["schemas"]["DailyActivity"][];
            activity: components["schemas"]["ActivityItem"][];
        };
    };
    responses: {
        /** @description Authenticated session */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Provider: "google" | "github";
        WorkspaceId: string;
        ProjectId: string;
        CardId: string;
        Page: number;
        PageSize: number;
        CardStatus: components["schemas"]["TaskStatus"];
        CardProjectId: string;
        CardAssigneeId: string;
        CardPriority: components["schemas"]["Priority"];
        /** @description Search in title or key (e.g. LK-12) */
        CardQuery: string;
        CardLabelId: string;
        ColumnId: string;
        ViewId: string;
        LabelId: string;
        ItemId: string;
        CommentId: string;
        AttachmentId: string;
        CardDue: "overdue" | "today" | "week" | "month" | "none";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token (also set as the lk_csrf cookie) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    getAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Error"];
            423: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (cookies cleared) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Email verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification email queued (no-op if already verified) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["Error"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Always succeeds to avoid account enumeration */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    oauthStart: {
        parameters: {
            query?: {
                /** @description Relative path to return to after sign-in */
                next?: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    oauthCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to the app (with ?error=<code> on failure) */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; other sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Role updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open invites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Invite created and emailed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    previewInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite details for the acceptance screen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Joined workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            403: components["responses"]["Error"];
            410: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Search in name or key */
                q?: string;
                status?: components["schemas"]["ProjectStatus"];
                picId?: string;
                team?: string;
                progress?: "not_started" | "early" | "midway" | "almost" | "done";
                deadline?: "overdue" | "week" | "month" | "later" | "none";
                sort?: "updated" | "name" | "deadline" | "progress" | "created";
                order?: "asc" | "desc";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    projectSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KPI counts and filter facets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board with ordered columns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query?: {
                status?: components["parameters"]["CardStatus"];
                projectId?: components["parameters"]["CardProjectId"];
                assigneeId?: components["parameters"]["CardAssigneeId"];
                priority?: components["parameters"]["CardPriority"];
                labelId?: components["parameters"]["CardLabelId"];
                /** @description Search in title or key (e.g. LK-12) */
                q?: components["parameters"]["CardQuery"];
                due?: components["parameters"]["CardDue"];
                sort?: "key" | "title" | "assignee" | "project" | "progress" | "deadline" | "priority" | "position" | "updated";
                order?: "asc" | "desc";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardPage"];
                };
            };
        };
    };
    createCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    cardStatusCounts: {
        parameters: {
            query?: {
                projectId?: components["parameters"]["CardProjectId"];
                assigneeId?: components["parameters"]["CardAssigneeId"];
                priority?: components["parameters"]["CardPriority"];
                labelId?: components["parameters"]["CardLabelId"];
                /** @description Search in title or key (e.g. LK-12) */
                q?: components["parameters"]["CardQuery"];
                due?: components["parameters"]["CardDue"];
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card counts per status for the same filters as listCards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusCounts"];
                };
            };
        };
    };
    bulkCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCardAction"];
            };
        };
        responses: {
            /** @description Number of cards changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
        };
    };
    cardStats: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard KPIs, daily activity and recent transitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    moveCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardMove"];
            };
        };
        responses: {
            /** @description Moved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    createColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardColumn"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    deleteColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: components["parameters"]["ColumnId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: components["parameters"]["ColumnId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardColumn"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    moveColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: components["parameters"]["ColumnId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Neighbours"];
            };
        };
        responses: {
            /** @description Moved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardColumn"];
                };
            };
        };
    };
    listSavedViews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's saved views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"][];
                };
            };
        };
    };
    createSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    deleteSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
        };
    };
    boardCards: {
        parameters: {
            query?: {
                projectId?: components["parameters"]["CardProjectId"];
                assigneeId?: components["parameters"]["CardAssigneeId"];
                priority?: components["parameters"]["CardPriority"];
                labelId?: components["parameters"]["CardLabelId"];
                /** @description Search in title or key (e.g. LK-12) */
                q?: components["parameters"]["CardQuery"];
                due?: components["parameters"]["CardDue"];
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBoard"];
                };
            };
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"][];
                };
            };
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (removed from every card) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
        };
    };
    listChecklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items in order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"][];
                };
            };
        };
    };
    addChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemInput"];
            };
        };
        responses: {
            /** @description Created (card progress is recomputed) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
        };
    };
    deleteChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachments, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"][];
                };
            };
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            413: components["responses"]["Error"];
        };
    };
    deleteAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: {
                /** @description Display images inline (other types always download) */
                inline?: boolean;
            };
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    cardActivity: {
        parameters: {
            query?: {
                /** @description Return entries older than this id */
                before?: number;
                limit?: number;
            };
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
        };
    };
    workspaceEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RealtimeMessage"];
                };
            };
        };
    };
    listErrorCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every error code the API can return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
