// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimReminder = `-- name: ClaimReminder :one
UPDATE calendar_events SET notified_at = now() WHERE id = $1 AND notified_at IS NULL RETURNING id, integration_id, provider_event_id, title, starts_at, ends_at, all_day, location, link, join_url, attendee_emails, notified_at, updated_at
`

func (q *Queries) ClaimReminder(ctx context.Context, id uuid.UUID) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, claimReminder, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ProviderEventID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Location,
		&i.Link,
		&i.JoinUrl,
		&i.AttendeeEmails,
		&i.NotifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventsNotIn = `-- name: DeleteEventsNotIn :exec
DELETE FROM calendar_events
WHERE integration_id = $1 AND ends_at >= $2 AND NOT (provider_event_id = ANY($3::text[]))
`

type DeleteEventsNotInParams struct {
	IntegrationID uuid.UUID
	EndsAt        time.Time
	Column3       []string
}

func (q *Queries) DeleteEventsNotIn(ctx context.Context, arg DeleteEventsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEventsNotIn, arg.IntegrationID, arg.EndsAt, arg.Column3)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE user_id = $1 AND workspace_id = $2 AND provider = $3
`

type DeleteIntegrationParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Provider    string
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteIntegration, arg.UserID, arg.WorkspaceID, arg.Provider)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at FROM integrations WHERE user_id = $1 AND workspace_id = $2 AND provider = $3
`

type GetIntegrationParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Provider    string
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.UserID, arg.WorkspaceID, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AccountEmail,
		&i.RefreshTokenEnc,
		&i.LeadMinutes,
		&i.NotifyBell,
		&i.ChannelID,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AccountEmail,
		&i.RefreshTokenEnc,
		&i.LeadMinutes,
		&i.NotifyBell,
		&i.ChannelID,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueForSync = `-- name: ListDueForSync :many
SELECT id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at FROM integrations
WHERE enabled AND status = 'connected' AND (last_sync_at IS NULL OR last_sync_at < $1)
`

func (q *Queries) ListDueForSync(ctx context.Context, lastSyncAt *time.Time) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listDueForSync, lastSyncAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Provider,
			&i.Enabled,
			&i.AccountEmail,
			&i.RefreshTokenEnc,
			&i.LeadMinutes,
			&i.NotifyBell,
			&i.ChannelID,
			&i.Status,
			&i.LastError,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT e.id AS event_id, i.id AS integration_id
FROM calendar_events e JOIN integrations i ON i.id = e.integration_id
WHERE i.enabled AND i.status = 'connected' AND e.notified_at IS NULL AND NOT e.all_day
  AND e.starts_at > $1 AND e.starts_at - make_interval(mins => i.lead_minutes) <= $1
`

type ListDueRemindersRow struct {
	EventID       uuid.UUID
	IntegrationID uuid.UUID
}

func (q *Queries) ListDueReminders(ctx context.Context, startsAt time.Time) ([]ListDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueReminders, startsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRemindersRow{}
	for rows.Next() {
		var i ListDueRemindersRow
		if err := rows.Scan(&i.EventID, &i.IntegrationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForIntegration = `-- name: ListEventsForIntegration :many
SELECT id, integration_id, provider_event_id, title, starts_at, ends_at, all_day, location, link, join_url, attendee_emails, notified_at, updated_at FROM calendar_events WHERE integration_id = $1 AND ends_at > $2 ORDER BY starts_at LIMIT $3
`

type ListEventsForIntegrationParams struct {
	IntegrationID uuid.UUID
	EndsAt        time.Time
	Limit         int32
}

func (q *Queries) ListEventsForIntegration(ctx context.Context, arg ListEventsForIntegrationParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForIntegration, arg.IntegrationID, arg.EndsAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.ProviderEventID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Location,
			&i.Link,
			&i.JoinUrl,
			&i.AttendeeEmails,
			&i.NotifiedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at FROM integrations WHERE user_id = $1 AND workspace_id = $2 ORDER BY provider
`

type ListIntegrationsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ListIntegrations(ctx context.Context, arg ListIntegrationsParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Provider,
			&i.Enabled,
			&i.AccountEmail,
			&i.RefreshTokenEnc,
			&i.LeadMinutes,
			&i.NotifyBell,
			&i.ChannelID,
			&i.Status,
			&i.LastError,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT e.id, e.integration_id, e.provider_event_id, e.title, e.starts_at, e.ends_at, e.all_day, e.location, e.link, e.join_url, e.attendee_emails, e.notified_at, e.updated_at FROM calendar_events e JOIN integrations i ON i.id = e.integration_id
WHERE i.user_id = $1 AND i.workspace_id = $2 AND i.enabled AND e.ends_at > $3
ORDER BY e.starts_at
LIMIT $4
`

type ListUpcomingEventsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	EndsAt      time.Time
	Limit       int32
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents,
		arg.UserID,
		arg.WorkspaceID,
		arg.EndsAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.ProviderEventID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Location,
			&i.Link,
			&i.JoinUrl,
			&i.AttendeeEmails,
			&i.NotifiedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncFailed = `-- name: MarkSyncFailed :exec
UPDATE integrations SET last_sync_at = now(), status = $2, last_error = $3, updated_at = now() WHERE id = $1
`

type MarkSyncFailedParams struct {
	ID        uuid.UUID
	Status    string
	LastError string
}

func (q *Queries) MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markSyncFailed, arg.ID, arg.Status, arg.LastError)
	return err
}

const markSynced = `-- name: MarkSynced :exec
UPDATE integrations SET last_sync_at = now(), status = 'connected', last_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSynced, id)
	return err
}

const updateIntegrationSettings = `-- name: UpdateIntegrationSettings :one
UPDATE integrations SET enabled = $4, lead_minutes = $5, notify_bell = $6, channel_id = $7, updated_at = now()
WHERE user_id = $1 AND workspace_id = $2 AND provider = $3
RETURNING id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at
`

type UpdateIntegrationSettingsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Provider    string
	Enabled     bool
	LeadMinutes int32
	NotifyBell  bool
	ChannelID   uuid.NullUUID
}

func (q *Queries) UpdateIntegrationSettings(ctx context.Context, arg UpdateIntegrationSettingsParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationSettings,
		arg.UserID,
		arg.WorkspaceID,
		arg.Provider,
		arg.Enabled,
		arg.LeadMinutes,
		arg.NotifyBell,
		arg.ChannelID,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AccountEmail,
		&i.RefreshTokenEnc,
		&i.LeadMinutes,
		&i.NotifyBell,
		&i.ChannelID,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEvent = `-- name: UpsertEvent :exec
INSERT INTO calendar_events (integration_id, provider_event_id, title, starts_at, ends_at, all_day, location, link, join_url, attendee_emails)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (integration_id, provider_event_id) DO UPDATE
SET title = EXCLUDED.title, ends_at = EXCLUDED.ends_at, all_day = EXCLUDED.all_day, location = EXCLUDED.location,
    link = EXCLUDED.link, join_url = EXCLUDED.join_url, attendee_emails = EXCLUDED.attendee_emails,
    -- A meeting moved by more than a minute earns a fresh reminder.
    notified_at = CASE WHEN abs(extract(epoch FROM (calendar_events.starts_at - EXCLUDED.starts_at))) > 60
                       THEN NULL ELSE calendar_events.notified_at END,
    starts_at = EXCLUDED.starts_at, updated_at = now()
`

type UpsertEventParams struct {
	IntegrationID   uuid.UUID
	ProviderEventID string
	Title           string
	StartsAt        time.Time
	EndsAt          time.Time
	AllDay          bool
	Location        string
	Link            string
	JoinUrl         string
	AttendeeEmails  []string
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) error {
	_, err := q.db.Exec(ctx, upsertEvent,
		arg.IntegrationID,
		arg.ProviderEventID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Location,
		arg.Link,
		arg.JoinUrl,
		arg.AttendeeEmails,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :one

INSERT INTO integrations (user_id, workspace_id, provider, account_email, refresh_token_enc)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, workspace_id, provider) DO UPDATE
SET account_email = EXCLUDED.account_email, refresh_token_enc = EXCLUDED.refresh_token_enc,
    enabled = true, status = 'connected', last_error = '', updated_at = now()
RETURNING id, user_id, workspace_id, provider, enabled, account_email, refresh_token_enc, lead_minutes, notify_bell, channel_id, status, last_error, last_sync_at, created_at, updated_at
`

type UpsertIntegrationParams struct {
	UserID          uuid.UUID
	WorkspaceID     uuid.UUID
	Provider        string
	AccountEmail    string
	RefreshTokenEnc []byte
}

// integrations module queries (sqlc).
func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration,
		arg.UserID,
		arg.WorkspaceID,
		arg.Provider,
		arg.AccountEmail,
		arg.RefreshTokenEnc,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AccountEmail,
		&i.RefreshTokenEnc,
		&i.LeadMinutes,
		&i.NotifyBell,
		&i.ChannelID,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
