// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimReminder(ctx context.Context, id uuid.UUID) (CalendarEvent, error)
	DeleteEventsNotIn(ctx context.Context, arg DeleteEventsNotInParams) error
	DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error
	GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error)
	GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error)
	ListDueForSync(ctx context.Context, lastSyncAt *time.Time) ([]Integration, error)
	ListDueReminders(ctx context.Context, startsAt time.Time) ([]ListDueRemindersRow, error)
	ListEventsForIntegration(ctx context.Context, arg ListEventsForIntegrationParams) ([]CalendarEvent, error)
	ListIntegrations(ctx context.Context, arg ListIntegrationsParams) ([]Integration, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]CalendarEvent, error)
	MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error
	MarkSynced(ctx context.Context, id uuid.UUID) error
	UpdateIntegrationSettings(ctx context.Context, arg UpdateIntegrationSettingsParams) (Integration, error)
	UpsertEvent(ctx context.Context, arg UpsertEventParams) error
	// integrations module queries (sqlc).
	UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
