// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAssignees = `-- name: AddAssignees :exec
INSERT INTO card_assignees (card_id, user_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddAssigneesParams struct {
	CardID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) AddAssignees(ctx context.Context, arg AddAssigneesParams) error {
	_, err := q.db.Exec(ctx, addAssignees, arg.CardID, arg.UserIds)
	return err
}

const archiveCard = `-- name: ArchiveCard :execrows
UPDATE cards SET archived_at = now(), version = version + 1 WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveCard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assigneesForCards = `-- name: AssigneesForCards :many
SELECT card_id, user_id FROM card_assignees WHERE card_id = ANY($1::uuid[])
`

func (q *Queries) AssigneesForCards(ctx context.Context, ids []uuid.UUID) ([]CardAssignee, error) {
	rows, err := q.db.Query(ctx, assigneesForCards, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardAssignee{}
	for rows.Next() {
		var i CardAssignee
		if err := rows.Scan(&i.CardID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardKPIs = `-- name: CardKPIs :one
SELECT
    count(*) FILTER (WHERE status <> 'done')::int AS active,
    count(*)::int AS total,
    count(*) FILTER (WHERE status = 'in_review')::int AS in_review,
    count(*) FILTER (WHERE status <> 'done' AND due_date < $1::date)::int AS overdue,
    count(*) FILTER (WHERE completed_at >= $2)::int AS done_this_week,
    count(*) FILTER (WHERE completed_at >= $3 AND completed_at < $2)::int AS done_prev_week,
    count(*) FILTER (WHERE created_at >= $2)::int AS created_this_week,
    count(*) FILTER (WHERE created_at >= $3 AND created_at < $2)::int AS created_prev_week
FROM cards WHERE workspace_id = $4 AND archived_at IS NULL
`

type CardKPIsParams struct {
	Today         time.Time
	WeekStart     *time.Time
	PrevWeekStart *time.Time
	WorkspaceID   uuid.UUID
}

type CardKPIsRow struct {
	Active          int32
	Total           int32
	InReview        int32
	Overdue         int32
	DoneThisWeek    int32
	DonePrevWeek    int32
	CreatedThisWeek int32
	CreatedPrevWeek int32
}

func (q *Queries) CardKPIs(ctx context.Context, arg CardKPIsParams) (CardKPIsRow, error) {
	row := q.db.QueryRow(ctx, cardKPIs,
		arg.Today,
		arg.WeekStart,
		arg.PrevWeekStart,
		arg.WorkspaceID,
	)
	var i CardKPIsRow
	err := row.Scan(
		&i.Active,
		&i.Total,
		&i.InReview,
		&i.Overdue,
		&i.DoneThisWeek,
		&i.DonePrevWeek,
		&i.CreatedThisWeek,
		&i.CreatedPrevWeek,
	)
	return i, err
}

const clearAssignees = `-- name: ClearAssignees :exec
DELETE FROM card_assignees WHERE card_id = $1
`

func (q *Queries) ClearAssignees(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignees, cardID)
	return err
}

const countByProject = `-- name: CountByProject :one
SELECT count(*)::int AS total, count(*) FILTER (WHERE status = 'done')::int AS done
FROM cards WHERE project_id = $1 AND archived_at IS NULL
`

type CountByProjectRow struct {
	Total int32
	Done  int32
}

func (q *Queries) CountByProject(ctx context.Context, projectID uuid.UUID) (CountByProjectRow, error) {
	row := q.db.QueryRow(ctx, countByProject, projectID)
	var i CountByProjectRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (workspace_id, project_id, board_id, column_id, number, title, description, status, priority,
                   progress, due_date, position, created_by, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14)
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at
`

type CreateCardParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	BoardID     uuid.UUID
	ColumnID    uuid.UUID
	Number      int32
	Title       string
	Description string
	Status      string
	Priority    string
	Progress    int16
	DueDate     *time.Time
	Position    string
	CreatedBy   uuid.NullUUID
	CompletedAt *time.Time
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.BoardID,
		arg.ColumnID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.DueDate,
		arg.Position,
		arg.CreatedBy,
		arg.CompletedAt,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at FROM cards WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetCard(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertTransition = `-- name: InsertTransition :exec
INSERT INTO card_transitions (card_id, workspace_id, project_id, from_status, to_status, actor_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTransitionParams struct {
	CardID      uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	FromStatus  *string
	ToStatus    string
	ActorID     uuid.NullUUID
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) error {
	_, err := q.db.Exec(ctx, insertTransition,
		arg.CardID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
	)
	return err
}

const lastPosition = `-- name: LastPosition :one
SELECT COALESCE(max(position), '')::text FROM cards WHERE column_id = $1 AND archived_at IS NULL
`

func (q *Queries) LastPosition(ctx context.Context, columnID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastPosition, columnID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const moveCard = `-- name: MoveCard :one
UPDATE cards SET
    column_id    = $1,
    board_id     = $2,
    status       = $3,
    position     = $4,
    progress     = CASE WHEN $3 = 'done' THEN 100 ELSE progress END,
    completed_at = CASE WHEN $3 = 'done' THEN COALESCE(completed_at, now()) ELSE NULL END,
    version      = version + 1
WHERE id = $5 AND version = $6 AND archived_at IS NULL
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at
`

type MoveCardParams struct {
	ColumnID uuid.UUID
	BoardID  uuid.UUID
	Status   string
	Position string
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, moveCard,
		arg.ColumnID,
		arg.BoardID,
		arg.Status,
		arg.Position,
		arg.ID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const nextCardNumber = `-- name: NextCardNumber :one
INSERT INTO card_counters (project_id, next) VALUES ($1, 2)
ON CONFLICT (project_id) DO UPDATE SET next = card_counters.next + 1
RETURNING (next - 1)::int
`

func (q *Queries) NextCardNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCardNumber, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPositionAfter = `-- name: NextPositionAfter :one
SELECT COALESCE(min(position), '')::text FROM cards
WHERE column_id = $1 AND archived_at IS NULL AND position > $2::text
`

type NextPositionAfterParams struct {
	ColumnID uuid.UUID
	After    string
}

func (q *Queries) NextPositionAfter(ctx context.Context, arg NextPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, nextPositionAfter, arg.ColumnID, arg.After)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const positionInColumn = `-- name: PositionInColumn :one
SELECT position FROM cards WHERE id = $1 AND column_id = $2 AND archived_at IS NULL
`

type PositionInColumnParams struct {
	ID       uuid.UUID
	ColumnID uuid.UUID
}

func (q *Queries) PositionInColumn(ctx context.Context, arg PositionInColumnParams) (string, error) {
	row := q.db.QueryRow(ctx, positionInColumn, arg.ID, arg.ColumnID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const prevPositionBefore = `-- name: PrevPositionBefore :one
SELECT COALESCE(max(position), '')::text FROM cards
WHERE column_id = $1 AND archived_at IS NULL AND position < $2::text
`

type PrevPositionBeforeParams struct {
	ColumnID uuid.UUID
	Before   string
}

func (q *Queries) PrevPositionBefore(ctx context.Context, arg PrevPositionBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, prevPositionBefore, arg.ColumnID, arg.Before)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const recentTransitions = `-- name: RecentTransitions :many
SELECT t.id, t.card_id, t.project_id, t.from_status, t.to_status, t.actor_id, t.at, c.title, c.number
FROM card_transitions t JOIN cards c ON c.id = t.card_id
WHERE t.workspace_id = $1 AND c.archived_at IS NULL
ORDER BY t.at DESC
LIMIT $2
`

type RecentTransitionsParams struct {
	WorkspaceID uuid.UUID
	Limit       int32
}

type RecentTransitionsRow struct {
	ID         int64
	CardID     uuid.UUID
	ProjectID  uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorID    uuid.NullUUID
	At         time.Time
	Title      string
	Number     int32
}

func (q *Queries) RecentTransitions(ctx context.Context, arg RecentTransitionsParams) ([]RecentTransitionsRow, error) {
	rows, err := q.db.Query(ctx, recentTransitions, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentTransitionsRow{}
	for rows.Next() {
		var i RecentTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ProjectID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.At,
			&i.Title,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionsByDay = `-- name: TransitionsByDay :many
SELECT (at AT TIME ZONE 'UTC')::date AS day, to_status, count(*)::int AS n
FROM card_transitions
WHERE workspace_id = $1 AND at >= $2
GROUP BY 1, 2
ORDER BY 1
`

type TransitionsByDayParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
}

type TransitionsByDayRow struct {
	Day      time.Time
	ToStatus string
	N        int32
}

func (q *Queries) TransitionsByDay(ctx context.Context, arg TransitionsByDayParams) ([]TransitionsByDayRow, error) {
	rows, err := q.db.Query(ctx, transitionsByDay, arg.WorkspaceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransitionsByDayRow{}
	for rows.Next() {
		var i TransitionsByDayRow
		if err := rows.Scan(&i.Day, &i.ToStatus, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    priority    = COALESCE($3, priority),
    progress    = COALESCE($4, progress),
    due_date    = CASE WHEN $5::bool THEN $6 ELSE due_date END,
    version     = version + 1
WHERE id = $7 AND version = $8 AND archived_at IS NULL
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at
`

type UpdateCardParams struct {
	Title       *string
	Description *string
	Priority    *string
	Progress    *int16
	SetDue      bool
	DueDate     *time.Time
	ID          uuid.UUID
	Version     int32
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Progress,
		arg.SetDue,
		arg.DueDate,
		arg.ID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
