// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAssignees(ctx context.Context, arg AddAssigneesParams) error
	ArchiveCard(ctx context.Context, id uuid.UUID) (int64, error)
	AssigneesForCards(ctx context.Context, ids []uuid.UUID) ([]CardAssignee, error)
	CardKPIs(ctx context.Context, arg CardKPIsParams) (CardKPIsRow, error)
	ClearAssignees(ctx context.Context, cardID uuid.UUID) error
	CountByProject(ctx context.Context, projectID uuid.UUID) (CountByProjectRow, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	GetCard(ctx context.Context, id uuid.UUID) (Card, error)
	InsertTransition(ctx context.Context, arg InsertTransitionParams) error
	LastPosition(ctx context.Context, columnID uuid.UUID) (string, error)
	MoveCard(ctx context.Context, arg MoveCardParams) (Card, error)
	NextCardNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	NextPositionAfter(ctx context.Context, arg NextPositionAfterParams) (string, error)
	PositionInColumn(ctx context.Context, arg PositionInColumnParams) (string, error)
	PrevPositionBefore(ctx context.Context, arg PrevPositionBeforeParams) (string, error)
	RecentTransitions(ctx context.Context, arg RecentTransitionsParams) ([]RecentTransitionsRow, error)
	TransitionsByDay(ctx context.Context, arg TransitionsByDayParams) ([]TransitionsByDayRow, error)
	UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error)
}

var _ Querier = (*Queries)(nil)
