// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAssignees = `-- name: AddAssignees :exec
INSERT INTO card_assignees (card_id, user_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddAssigneesParams struct {
	CardID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) AddAssignees(ctx context.Context, arg AddAssigneesParams) error {
	_, err := q.db.Exec(ctx, addAssignees, arg.CardID, arg.UserIds)
	return err
}

const addCardLabels = `-- name: AddCardLabels :exec
INSERT INTO card_labels (card_id, label_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddCardLabelsParams struct {
	CardID   uuid.UUID
	LabelIds []uuid.UUID
}

func (q *Queries) AddCardLabels(ctx context.Context, arg AddCardLabelsParams) error {
	_, err := q.db.Exec(ctx, addCardLabels, arg.CardID, arg.LabelIds)
	return err
}

const archiveCard = `-- name: ArchiveCard :execrows
UPDATE cards SET archived_at = now(), version = version + 1 WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveCard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveChildren = `-- name: ArchiveChildren :exec
UPDATE cards SET archived_at = now(), version = version + 1 WHERE parent_id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveChildren(ctx context.Context, parentID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, archiveChildren, parentID)
	return err
}

const assigneesForCards = `-- name: AssigneesForCards :many
SELECT card_id, user_id FROM card_assignees WHERE card_id = ANY($1::uuid[])
`

func (q *Queries) AssigneesForCards(ctx context.Context, ids []uuid.UUID) ([]CardAssignee, error) {
	rows, err := q.db.Query(ctx, assigneesForCards, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardAssignee{}
	for rows.Next() {
		var i CardAssignee
		if err := rows.Scan(&i.CardID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardKPIs = `-- name: CardKPIs :one
SELECT
    count(*) FILTER (WHERE status <> 'done')::int AS active,
    count(*)::int AS total,
    count(*) FILTER (WHERE status = 'in_review')::int AS in_review,
    count(*) FILTER (WHERE status <> 'done' AND due_date < $1::date)::int AS overdue,
    count(*) FILTER (WHERE completed_at >= $2)::int AS done_this_week,
    count(*) FILTER (WHERE completed_at >= $3 AND completed_at < $2)::int AS done_prev_week,
    count(*) FILTER (WHERE created_at >= $2)::int AS created_this_week,
    count(*) FILTER (WHERE created_at >= $3 AND created_at < $2)::int AS created_prev_week
FROM cards WHERE workspace_id = $4 AND archived_at IS NULL
`

type CardKPIsParams struct {
	Today         time.Time
	WeekStart     *time.Time
	PrevWeekStart *time.Time
	WorkspaceID   uuid.UUID
}

type CardKPIsRow struct {
	Active          int32
	Total           int32
	InReview        int32
	Overdue         int32
	DoneThisWeek    int32
	DonePrevWeek    int32
	CreatedThisWeek int32
	CreatedPrevWeek int32
}

func (q *Queries) CardKPIs(ctx context.Context, arg CardKPIsParams) (CardKPIsRow, error) {
	row := q.db.QueryRow(ctx, cardKPIs,
		arg.Today,
		arg.WeekStart,
		arg.PrevWeekStart,
		arg.WorkspaceID,
	)
	var i CardKPIsRow
	err := row.Scan(
		&i.Active,
		&i.Total,
		&i.InReview,
		&i.Overdue,
		&i.DoneThisWeek,
		&i.DonePrevWeek,
		&i.CreatedThisWeek,
		&i.CreatedPrevWeek,
	)
	return i, err
}

const clearAssignees = `-- name: ClearAssignees :exec
DELETE FROM card_assignees WHERE card_id = $1
`

func (q *Queries) ClearAssignees(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignees, cardID)
	return err
}

const clearCardLabels = `-- name: ClearCardLabels :exec
DELETE FROM card_labels WHERE card_id = $1
`

func (q *Queries) ClearCardLabels(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCardLabels, cardID)
	return err
}

const countByProject = `-- name: CountByProject :one
SELECT count(*)::int AS total, count(*) FILTER (WHERE status = 'done')::int AS done,
       COALESCE(round(avg(progress)), 0)::int AS avg_progress
FROM cards WHERE project_id = $1 AND archived_at IS NULL
`

type CountByProjectRow struct {
	Total       int32
	Done        int32
	AvgProgress int32
}

func (q *Queries) CountByProject(ctx context.Context, projectID uuid.UUID) (CountByProjectRow, error) {
	row := q.db.QueryRow(ctx, countByProject, projectID)
	var i CountByProjectRow
	err := row.Scan(&i.Total, &i.Done, &i.AvgProgress)
	return i, err
}

const countChecklist = `-- name: CountChecklist :one
SELECT count(*)::int FROM checklist_items WHERE card_id = $1
`

func (q *Queries) CountChecklist(ctx context.Context, cardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countChecklist, cardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countInColumn = `-- name: CountInColumn :one
SELECT count(*)::int FROM cards WHERE column_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountInColumn(ctx context.Context, columnID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInColumn, columnID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLabelsInWorkspace = `-- name: CountLabelsInWorkspace :one
SELECT count(*)::int FROM labels WHERE workspace_id = $1 AND id = ANY($2::uuid[])
`

type CountLabelsInWorkspaceParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) CountLabelsInWorkspace(ctx context.Context, arg CountLabelsInWorkspaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLabelsInWorkspace, arg.WorkspaceID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (workspace_id, project_id, board_id, column_id, number, title, description, status, priority,
                   progress, due_date, position, created_by, completed_at, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15)
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done
`

type CreateCardParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	BoardID     uuid.UUID
	ColumnID    uuid.UUID
	Number      int32
	Title       string
	Description string
	Status      string
	Priority    string
	Progress    int16
	DueDate     *time.Time
	Position    string
	CreatedBy   uuid.NullUUID
	CompletedAt *time.Time
	ParentID    uuid.NullUUID
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.BoardID,
		arg.ColumnID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.DueDate,
		arg.Position,
		arg.CreatedBy,
		arg.CompletedAt,
		arg.ParentID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (card_id, text, position) VALUES ($1, $2, $3) RETURNING id, card_id, text, done, position, created_at, completed_at
`

type CreateChecklistItemParams struct {
	CardID   uuid.UUID
	Text     string
	Position string
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem, arg.CardID, arg.Text, arg.Position)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Text,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (workspace_id, name, tone) VALUES ($1, $2, $3) RETURNING id, workspace_id, name, tone, created_at
`

type CreateLabelParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Tone        string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.WorkspaceID, arg.Name, arg.Tone)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Tone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done FROM cards WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetCard(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const getCardByKey = `-- name: GetCardByKey :one
SELECT c.id, c.workspace_id, c.project_id, c.board_id, c.column_id, c.number, c.title, c.description, c.status, c.priority, c.progress, c.due_date, c.position, c.version, c.created_by, c.completed_at, c.created_at, c.updated_at, c.archived_at, c.checklist_total, c.checklist_done, c.comment_count, c.attachment_count, c.parent_id, c.subtask_total, c.subtask_done FROM cards c JOIN projects p ON p.id = c.project_id
WHERE c.workspace_id = $1 AND upper(p.key) = upper($2) AND c.number = $3
`

type GetCardByKeyParams struct {
	WorkspaceID uuid.UUID
	Upper       interface{}
	Number      int32
}

func (q *Queries) GetCardByKey(ctx context.Context, arg GetCardByKeyParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByKey, arg.WorkspaceID, arg.Upper, arg.Number)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, card_id, text, done, position, created_at, completed_at FROM checklist_items WHERE id = $1
`

func (q *Queries) GetChecklistItem(ctx context.Context, id uuid.UUID) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Text,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, name, tone, created_at FROM labels WHERE id = $1
`

func (q *Queries) GetLabel(ctx context.Context, id uuid.UUID) (Label, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Tone,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransition = `-- name: InsertTransition :exec
INSERT INTO card_transitions (card_id, workspace_id, project_id, from_status, to_status, actor_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTransitionParams struct {
	CardID      uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	FromStatus  *string
	ToStatus    string
	ActorID     uuid.NullUUID
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) error {
	_, err := q.db.Exec(ctx, insertTransition,
		arg.CardID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
	)
	return err
}

const labelsForCards = `-- name: LabelsForCards :many
SELECT cl.card_id, cl.label_id FROM card_labels cl JOIN labels l ON l.id = cl.label_id
WHERE cl.card_id = ANY($1::uuid[])
ORDER BY lower(l.name)
`

func (q *Queries) LabelsForCards(ctx context.Context, ids []uuid.UUID) ([]CardLabel, error) {
	rows, err := q.db.Query(ctx, labelsForCards, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardLabel{}
	for rows.Next() {
		var i CardLabel
		if err := rows.Scan(&i.CardID, &i.LabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastChecklistPosition = `-- name: LastChecklistPosition :one
SELECT COALESCE(max(position), '')::text FROM checklist_items WHERE card_id = $1
`

func (q *Queries) LastChecklistPosition(ctx context.Context, cardID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastChecklistPosition, cardID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const lastPosition = `-- name: LastPosition :one
SELECT COALESCE(max(position), '')::text FROM cards WHERE column_id = $1 AND archived_at IS NULL
`

func (q *Queries) LastPosition(ctx context.Context, columnID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastPosition, columnID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const lastPositionInStatus = `-- name: LastPositionInStatus :one
SELECT COALESCE(max(position), '')::text FROM cards
WHERE workspace_id = $1 AND status = $2 AND archived_at IS NULL
`

type LastPositionInStatusParams struct {
	WorkspaceID uuid.UUID
	Status      string
}

func (q *Queries) LastPositionInStatus(ctx context.Context, arg LastPositionInStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, lastPositionInStatus, arg.WorkspaceID, arg.Status)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listChecklist = `-- name: ListChecklist :many

SELECT id, card_id, text, done, position, created_at, completed_at FROM checklist_items WHERE card_id = $1 ORDER BY position, id
`

// Checklist.
func (q *Queries) ListChecklist(ctx context.Context, cardID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklist, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Text,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many

SELECT id, workspace_id, name, tone, created_at FROM labels WHERE workspace_id = $1 ORDER BY lower(name)
`

// Labels.
func (q *Queries) ListLabels(ctx context.Context, workspaceID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Tone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCard = `-- name: MoveCard :one
UPDATE cards SET
    column_id    = $1,
    board_id     = $2,
    status       = $3,
    position     = $4,
    progress     = $5,
    completed_at = CASE WHEN $3 = 'done' THEN COALESCE(completed_at, now()) ELSE NULL END,
    version      = version + 1
WHERE id = $6 AND version = $7 AND archived_at IS NULL
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done
`

type MoveCardParams struct {
	ColumnID uuid.UUID
	BoardID  uuid.UUID
	Status   string
	Position string
	Progress int16
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, moveCard,
		arg.ColumnID,
		arg.BoardID,
		arg.Status,
		arg.Position,
		arg.Progress,
		arg.ID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const nextCardNumber = `-- name: NextCardNumber :one
INSERT INTO card_counters (project_id, next) VALUES ($1, 2)
ON CONFLICT (project_id) DO UPDATE SET next = card_counters.next + 1
RETURNING (next - 1)::int
`

func (q *Queries) NextCardNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCardNumber, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextChecklistPositionAfter = `-- name: NextChecklistPositionAfter :one
SELECT COALESCE(min(position), '')::text FROM checklist_items WHERE card_id = $1 AND position > $2::text
`

type NextChecklistPositionAfterParams struct {
	CardID uuid.UUID
	After  string
}

func (q *Queries) NextChecklistPositionAfter(ctx context.Context, arg NextChecklistPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, nextChecklistPositionAfter, arg.CardID, arg.After)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPositionAfter = `-- name: NextPositionAfter :one
SELECT COALESCE(min(position), '')::text FROM cards
WHERE column_id = $1 AND archived_at IS NULL AND position > $2::text
`

type NextPositionAfterParams struct {
	ColumnID uuid.UUID
	After    string
}

func (q *Queries) NextPositionAfter(ctx context.Context, arg NextPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, nextPositionAfter, arg.ColumnID, arg.After)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPositionAfterInStatus = `-- name: NextPositionAfterInStatus :one
SELECT COALESCE(min(position), '')::text FROM cards
WHERE workspace_id = $1 AND status = $2 AND archived_at IS NULL AND position > $3::text
`

type NextPositionAfterInStatusParams struct {
	WorkspaceID uuid.UUID
	Status      string
	After       string
}

func (q *Queries) NextPositionAfterInStatus(ctx context.Context, arg NextPositionAfterInStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, nextPositionAfterInStatus, arg.WorkspaceID, arg.Status, arg.After)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const positionInColumn = `-- name: PositionInColumn :one
SELECT position FROM cards WHERE id = $1 AND column_id = $2 AND archived_at IS NULL
`

type PositionInColumnParams struct {
	ID       uuid.UUID
	ColumnID uuid.UUID
}

func (q *Queries) PositionInColumn(ctx context.Context, arg PositionInColumnParams) (string, error) {
	row := q.db.QueryRow(ctx, positionInColumn, arg.ID, arg.ColumnID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const positionInStatus = `-- name: PositionInStatus :one

SELECT position FROM cards
WHERE id = $1 AND workspace_id = $2 AND status = $3 AND archived_at IS NULL
`

type PositionInStatusParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Status      string
}

// Lane-scoped ordering (cross-project board: one lane per status).
func (q *Queries) PositionInStatus(ctx context.Context, arg PositionInStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, positionInStatus, arg.ID, arg.WorkspaceID, arg.Status)
	var position string
	err := row.Scan(&position)
	return position, err
}

const prevChecklistPositionBefore = `-- name: PrevChecklistPositionBefore :one
SELECT COALESCE(max(position), '')::text FROM checklist_items WHERE card_id = $1 AND position < $2::text
`

type PrevChecklistPositionBeforeParams struct {
	CardID uuid.UUID
	Before string
}

func (q *Queries) PrevChecklistPositionBefore(ctx context.Context, arg PrevChecklistPositionBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, prevChecklistPositionBefore, arg.CardID, arg.Before)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const prevPositionBefore = `-- name: PrevPositionBefore :one
SELECT COALESCE(max(position), '')::text FROM cards
WHERE column_id = $1 AND archived_at IS NULL AND position < $2::text
`

type PrevPositionBeforeParams struct {
	ColumnID uuid.UUID
	Before   string
}

func (q *Queries) PrevPositionBefore(ctx context.Context, arg PrevPositionBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, prevPositionBefore, arg.ColumnID, arg.Before)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const prevPositionBeforeInStatus = `-- name: PrevPositionBeforeInStatus :one
SELECT COALESCE(max(position), '')::text FROM cards
WHERE workspace_id = $1 AND status = $2 AND archived_at IS NULL AND position < $3::text
`

type PrevPositionBeforeInStatusParams struct {
	WorkspaceID uuid.UUID
	Status      string
	Before      string
}

func (q *Queries) PrevPositionBeforeInStatus(ctx context.Context, arg PrevPositionBeforeInStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, prevPositionBeforeInStatus, arg.WorkspaceID, arg.Status, arg.Before)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const recentTransitions = `-- name: RecentTransitions :many
SELECT t.id, t.card_id, t.project_id, t.from_status, t.to_status, t.actor_id, t.at, c.title, c.number
FROM card_transitions t JOIN cards c ON c.id = t.card_id
WHERE t.workspace_id = $1 AND c.archived_at IS NULL
ORDER BY t.at DESC
LIMIT $2
`

type RecentTransitionsParams struct {
	WorkspaceID uuid.UUID
	Limit       int32
}

type RecentTransitionsRow struct {
	ID         int64
	CardID     uuid.UUID
	ProjectID  uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorID    uuid.NullUUID
	At         time.Time
	Title      string
	Number     int32
}

func (q *Queries) RecentTransitions(ctx context.Context, arg RecentTransitionsParams) ([]RecentTransitionsRow, error) {
	rows, err := q.db.Query(ctx, recentTransitions, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentTransitionsRow{}
	for rows.Next() {
		var i RecentTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ProjectID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.At,
			&i.Title,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshChecklistCounts = `-- name: RefreshChecklistCounts :one

UPDATE cards SET
    checklist_total = (SELECT count(*) FROM checklist_items i WHERE i.card_id = cards.id),
    checklist_done  = (SELECT count(*) FROM checklist_items i WHERE i.card_id = cards.id AND i.done)
WHERE cards.id = $1
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done
`

// Derived data (not user edits: no version bump).
func (q *Queries) RefreshChecklistCounts(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, refreshChecklistCounts, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const refreshSubtaskCounts = `-- name: RefreshSubtaskCounts :one
UPDATE cards SET
    subtask_total = (SELECT count(*) FROM cards s WHERE s.parent_id = cards.id AND s.archived_at IS NULL),
    subtask_done  = (SELECT count(*) FROM cards s WHERE s.parent_id = cards.id AND s.archived_at IS NULL
                     AND s.status = 'done')
WHERE cards.id = $1
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done
`

func (q *Queries) RefreshSubtaskCounts(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, refreshSubtaskCounts, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const relocateArchivedCards = `-- name: RelocateArchivedCards :exec
UPDATE cards SET column_id = $1 WHERE column_id = $2 AND archived_at IS NOT NULL
`

type RelocateArchivedCardsParams struct {
	ToColumn   uuid.UUID
	FromColumn uuid.UUID
}

func (q *Queries) RelocateArchivedCards(ctx context.Context, arg RelocateArchivedCardsParams) error {
	_, err := q.db.Exec(ctx, relocateArchivedCards, arg.ToColumn, arg.FromColumn)
	return err
}

const setAttachmentCount = `-- name: SetAttachmentCount :exec
UPDATE cards SET attachment_count = $1 WHERE id = $2
`

type SetAttachmentCountParams struct {
	Count int32
	ID    uuid.UUID
}

func (q *Queries) SetAttachmentCount(ctx context.Context, arg SetAttachmentCountParams) error {
	_, err := q.db.Exec(ctx, setAttachmentCount, arg.Count, arg.ID)
	return err
}

const setCommentCount = `-- name: SetCommentCount :exec
UPDATE cards SET comment_count = $1 WHERE id = $2
`

type SetCommentCountParams struct {
	Count int32
	ID    uuid.UUID
}

func (q *Queries) SetCommentCount(ctx context.Context, arg SetCommentCountParams) error {
	_, err := q.db.Exec(ctx, setCommentCount, arg.Count, arg.ID)
	return err
}

const setProgress = `-- name: SetProgress :exec
UPDATE cards SET progress = $1 WHERE id = $2
`

type SetProgressParams struct {
	Progress int16
	ID       uuid.UUID
}

func (q *Queries) SetProgress(ctx context.Context, arg SetProgressParams) error {
	_, err := q.db.Exec(ctx, setProgress, arg.Progress, arg.ID)
	return err
}

const transitionsByDay = `-- name: TransitionsByDay :many
SELECT (at AT TIME ZONE 'UTC')::date AS day, to_status, count(*)::int AS n
FROM card_transitions
WHERE workspace_id = $1 AND at >= $2
GROUP BY 1, 2
ORDER BY 1
`

type TransitionsByDayParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
}

type TransitionsByDayRow struct {
	Day      time.Time
	ToStatus string
	N        int32
}

func (q *Queries) TransitionsByDay(ctx context.Context, arg TransitionsByDayParams) ([]TransitionsByDayRow, error) {
	rows, err := q.db.Query(ctx, transitionsByDay, arg.WorkspaceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransitionsByDayRow{}
	for rows.Next() {
		var i TransitionsByDayRow
		if err := rows.Scan(&i.Day, &i.ToStatus, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    priority    = COALESCE($3, priority),
    due_date    = CASE WHEN $4::bool THEN $5 ELSE due_date END,
    version     = version + 1
WHERE id = $6 AND version = $7 AND archived_at IS NULL
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, status, priority, progress, due_date, position, version, created_by, completed_at, created_at, updated_at, archived_at, checklist_total, checklist_done, comment_count, attachment_count, parent_id, subtask_total, subtask_done
`

type UpdateCardParams struct {
	Title       *string
	Description *string
	Priority    *string
	SetDue      bool
	DueDate     *time.Time
	ID          uuid.UUID
	Version     int32
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.SetDue,
		arg.DueDate,
		arg.ID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.DueDate,
		&i.Position,
		&i.Version,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
		&i.AttachmentCount,
		&i.ParentID,
		&i.SubtaskTotal,
		&i.SubtaskDone,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE checklist_items SET
    text         = COALESCE($1, text),
    done         = COALESCE($2, done),
    completed_at = CASE WHEN $2::bool IS NULL THEN completed_at
                        WHEN $2::bool THEN COALESCE(completed_at, now()) ELSE NULL END,
    position     = COALESCE($3, position)
WHERE id = $4
RETURNING id, card_id, text, done, position, created_at, completed_at
`

type UpdateChecklistItemParams struct {
	Text     *string
	Done     pgtype.Bool
	Position *string
	ID       uuid.UUID
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.Text,
		arg.Done,
		arg.Position,
		arg.ID,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Text,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels SET name = COALESCE($1, name), tone = COALESCE($2, tone)
WHERE id = $3 RETURNING id, workspace_id, name, tone, created_at
`

type UpdateLabelParams struct {
	Name *string
	Tone *string
	ID   uuid.UUID
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel, arg.Name, arg.Tone, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Tone,
		&i.CreatedAt,
	)
	return i, err
}
