// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveField = `-- name: ArchiveField :exec
UPDATE custom_fields SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveField(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveField, id)
	return err
}

const countFieldUses = `-- name: CountFieldUses :one
SELECT count(*)::int FROM card_field_values WHERE field_id = $1
`

func (q *Queries) CountFieldUses(ctx context.Context, fieldID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFieldUses, fieldID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFields = `-- name: CountFields :one
SELECT count(*)::int FROM custom_fields WHERE workspace_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountFields(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFields, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createField = `-- name: CreateField :one
INSERT INTO custom_fields (workspace_id, name, description, kind, options, show_on_card, position)
VALUES ($1, $2, $3, $4, $5, $6,
        (SELECT COALESCE(max(position) + 1, 0) FROM custom_fields WHERE workspace_id = $1 AND archived_at IS NULL))
RETURNING id, workspace_id, name, description, kind, options, show_on_card, position, archived_at, created_at
`

type CreateFieldParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Description string
	Kind        string
	Options     []byte
	ShowOnCard  bool
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (CustomField, error) {
	row := q.db.QueryRow(ctx, createField,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Options,
		arg.ShowOnCard,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Options,
		&i.ShowOnCard,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteValue = `-- name: DeleteValue :exec
DELETE FROM card_field_values WHERE card_id = $1 AND field_id = $2
`

type DeleteValueParams struct {
	CardID  uuid.UUID
	FieldID uuid.UUID
}

func (q *Queries) DeleteValue(ctx context.Context, arg DeleteValueParams) error {
	_, err := q.db.Exec(ctx, deleteValue, arg.CardID, arg.FieldID)
	return err
}

const deleteValuesOutsideOptions = `-- name: DeleteValuesOutsideOptions :exec
DELETE FROM card_field_values WHERE field_id = $1 AND NOT ((value #>> '{}') = ANY($2::text[]))
`

type DeleteValuesOutsideOptionsParams struct {
	FieldID uuid.UUID
	Keep    []string
}

// Drops values that point at select options that no longer exist.
func (q *Queries) DeleteValuesOutsideOptions(ctx context.Context, arg DeleteValuesOutsideOptionsParams) error {
	_, err := q.db.Exec(ctx, deleteValuesOutsideOptions, arg.FieldID, arg.Keep)
	return err
}

const getField = `-- name: GetField :one
SELECT id, workspace_id, name, description, kind, options, show_on_card, position, archived_at, created_at FROM custom_fields WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetField(ctx context.Context, id uuid.UUID) (CustomField, error) {
	row := q.db.QueryRow(ctx, getField, id)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Options,
		&i.ShowOnCard,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFields = `-- name: ListFields :many
SELECT id, workspace_id, name, description, kind, options, show_on_card, position, archived_at, created_at FROM custom_fields WHERE workspace_id = $1 AND archived_at IS NULL ORDER BY position, created_at, id
`

func (q *Queries) ListFields(ctx context.Context, workspaceID uuid.UUID) ([]CustomField, error) {
	rows, err := q.db.Query(ctx, listFields, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomField{}
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Options,
			&i.ShowOnCard,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuesForCard = `-- name: ListValuesForCard :many
SELECT card_id, field_id, workspace_id, value, updated_at FROM card_field_values WHERE card_id = $1
`

func (q *Queries) ListValuesForCard(ctx context.Context, cardID uuid.UUID) ([]CardFieldValue, error) {
	rows, err := q.db.Query(ctx, listValuesForCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardFieldValue{}
	for rows.Next() {
		var i CardFieldValue
		if err := rows.Scan(
			&i.CardID,
			&i.FieldID,
			&i.WorkspaceID,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuesForCards = `-- name: ListValuesForCards :many
SELECT card_id, field_id, workspace_id, value, updated_at FROM card_field_values WHERE workspace_id = $1 AND card_id = ANY($2::uuid[])
`

type ListValuesForCardsParams struct {
	WorkspaceID uuid.UUID
	CardIds     []uuid.UUID
}

func (q *Queries) ListValuesForCards(ctx context.Context, arg ListValuesForCardsParams) ([]CardFieldValue, error) {
	rows, err := q.db.Query(ctx, listValuesForCards, arg.WorkspaceID, arg.CardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardFieldValue{}
	for rows.Next() {
		var i CardFieldValue
		if err := rows.Scan(
			&i.CardID,
			&i.FieldID,
			&i.WorkspaceID,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFieldPosition = `-- name: SetFieldPosition :exec
UPDATE custom_fields SET position = $2 WHERE id = $1 AND workspace_id = $3
`

type SetFieldPositionParams struct {
	ID          uuid.UUID
	Position    int32
	WorkspaceID uuid.UUID
}

func (q *Queries) SetFieldPosition(ctx context.Context, arg SetFieldPositionParams) error {
	_, err := q.db.Exec(ctx, setFieldPosition, arg.ID, arg.Position, arg.WorkspaceID)
	return err
}

const updateField = `-- name: UpdateField :one
UPDATE custom_fields
SET name         = COALESCE($1, name),
    description  = COALESCE($2, description),
    options      = COALESCE($3, options),
    show_on_card = COALESCE($4, show_on_card)
WHERE id = $5 AND archived_at IS NULL
RETURNING id, workspace_id, name, description, kind, options, show_on_card, position, archived_at, created_at
`

type UpdateFieldParams struct {
	Name        *string
	Description *string
	Options     []byte
	ShowOnCard  pgtype.Bool
	ID          uuid.UUID
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) (CustomField, error) {
	row := q.db.QueryRow(ctx, updateField,
		arg.Name,
		arg.Description,
		arg.Options,
		arg.ShowOnCard,
		arg.ID,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Options,
		&i.ShowOnCard,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertValue = `-- name: UpsertValue :exec
INSERT INTO card_field_values (card_id, field_id, workspace_id, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (card_id, field_id) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertValueParams struct {
	CardID      uuid.UUID
	FieldID     uuid.UUID
	WorkspaceID uuid.UUID
	Value       []byte
}

func (q *Queries) UpsertValue(ctx context.Context, arg UpsertValueParams) error {
	_, err := q.db.Exec(ctx, upsertValue,
		arg.CardID,
		arg.FieldID,
		arg.WorkspaceID,
		arg.Value,
	)
	return err
}
