// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveField(ctx context.Context, id uuid.UUID) error
	CountFieldUses(ctx context.Context, fieldID uuid.UUID) (int32, error)
	CountFields(ctx context.Context, workspaceID uuid.UUID) (int32, error)
	CreateField(ctx context.Context, arg CreateFieldParams) (CustomField, error)
	DeleteValue(ctx context.Context, arg DeleteValueParams) error
	// Drops values that point at select options that no longer exist.
	DeleteValuesOutsideOptions(ctx context.Context, arg DeleteValuesOutsideOptionsParams) error
	GetField(ctx context.Context, id uuid.UUID) (CustomField, error)
	ListFields(ctx context.Context, workspaceID uuid.UUID) ([]CustomField, error)
	ListValuesForCard(ctx context.Context, cardID uuid.UUID) ([]CardFieldValue, error)
	ListValuesForCards(ctx context.Context, arg ListValuesForCardsParams) ([]CardFieldValue, error)
	SetFieldPosition(ctx context.Context, arg SetFieldPositionParams) error
	UpdateField(ctx context.Context, arg UpdateFieldParams) (CustomField, error)
	UpsertValue(ctx context.Context, arg UpsertValueParams) error
}

var _ Querier = (*Queries)(nil)
