// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (workspace_id, project_id, name) VALUES ($1, $2, $3)
ON CONFLICT (project_id) DO NOTHING
RETURNING id, workspace_id, project_id, name, created_at
`

type CreateBoardParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Name        string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.WorkspaceID, arg.ProjectID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_columns (board_id, name, category, position) VALUES ($1, $2, $3, $4)
RETURNING id, board_id, name, category, position, wip_limit, created_at
`

type CreateColumnParams struct {
	BoardID  uuid.UUID
	Name     string
	Category string
	Position string
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.Category,
		arg.Position,
	)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.CreatedAt,
	)
	return i, err
}

const firstColumnByCategory = `-- name: FirstColumnByCategory :one
SELECT c.id, c.board_id, c.name, c.category, c.position, c.wip_limit, b.project_id, b.workspace_id
FROM board_columns c JOIN boards b ON b.id = c.board_id
WHERE b.project_id = $1 AND c.category = $2
ORDER BY c.position
LIMIT 1
`

type FirstColumnByCategoryParams struct {
	ProjectID uuid.UUID
	Category  string
}

type FirstColumnByCategoryRow struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	Name        string
	Category    string
	Position    string
	WipLimit    *int32
	ProjectID   uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) FirstColumnByCategory(ctx context.Context, arg FirstColumnByCategoryParams) (FirstColumnByCategoryRow, error) {
	row := q.db.QueryRow(ctx, firstColumnByCategory, arg.ProjectID, arg.Category)
	var i FirstColumnByCategoryRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.ProjectID,
		&i.WorkspaceID,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, workspace_id, project_id, name, created_at FROM boards WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getBoardByProject = `-- name: GetBoardByProject :one
SELECT id, workspace_id, project_id, name, created_at FROM boards WHERE project_id = $1
`

func (q *Queries) GetBoardByProject(ctx context.Context, projectID uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByProject, projectID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT c.id, c.board_id, c.name, c.category, c.position, c.wip_limit, b.project_id, b.workspace_id
FROM board_columns c JOIN boards b ON b.id = c.board_id
WHERE c.id = $1
`

type GetColumnRow struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	Name        string
	Category    string
	Position    string
	WipLimit    *int32
	ProjectID   uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (GetColumnRow, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i GetColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.WipLimit,
		&i.ProjectID,
		&i.WorkspaceID,
	)
	return i, err
}

const listColumns = `-- name: ListColumns :many
SELECT id, board_id, name, category, position, wip_limit, created_at FROM board_columns WHERE board_id = $1 ORDER BY position
`

func (q *Queries) ListColumns(ctx context.Context, boardID uuid.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Category,
			&i.Position,
			&i.WipLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
