// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error)
	FirstColumnByCategory(ctx context.Context, arg FirstColumnByCategoryParams) (FirstColumnByCategoryRow, error)
	GetBoard(ctx context.Context, id uuid.UUID) (Board, error)
	GetBoardByProject(ctx context.Context, projectID uuid.UUID) (Board, error)
	GetColumn(ctx context.Context, id uuid.UUID) (GetColumnRow, error)
	ListColumns(ctx context.Context, boardID uuid.UUID) ([]BoardColumn, error)
}

var _ Querier = (*Queries)(nil)
