// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearAvatar = `-- name: ClearAvatar :exec
UPDATE users SET avatar_url = NULL, avatar_key = NULL, avatar_type = NULL WHERE id = $1
`

func (q *Queries) ClearAvatar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAvatar, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, locale, email_verified_at, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type
`

type CreateUserParams struct {
	Email           string
	Name            string
	PasswordHash    *string
	Locale          string
	EmailVerifiedAt *time.Time
	AvatarUrl       *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Locale,
		arg.EmailVerifiedAt,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.AvatarUrl,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.AvatarType,
	)
	return i, err
}

const getAvatar = `-- name: GetAvatar :one
SELECT avatar_key, avatar_type FROM users WHERE id = $1
`

type GetAvatarRow struct {
	AvatarKey  *string
	AvatarType *string
}

func (q *Queries) GetAvatar(ctx context.Context, id uuid.UUID) (GetAvatarRow, error) {
	row := q.db.QueryRow(ctx, getAvatar, id)
	var i GetAvatarRow
	err := row.Scan(&i.AvatarKey, &i.AvatarType)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.AvatarUrl,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.AvatarType,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.AvatarUrl,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.AvatarType,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type FROM users WHERE id = ANY($1::uuid[]) ORDER BY name
`

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.Locale,
			&i.AvatarUrl,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarKey,
			&i.AvatarType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now()) WHERE id = $1 RETURNING id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.AvatarUrl,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.AvatarType,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE WHEN failed_login_count + 1 >= $1::int
                        THEN now() + make_interval(secs => $2::int)
                        ELSE locked_until END
WHERE id = $3
RETURNING failed_login_count, locked_until
`

type RecordLoginFailureParams struct {
	Threshold   int32
	LockSeconds int32
	ID          uuid.UUID
}

type RecordLoginFailureRow struct {
	FailedLoginCount int32
	LockedUntil      *time.Time
}

// Increments the failure counter and locks the account once it reaches the threshold.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.Threshold, arg.LockSeconds, arg.ID)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE users SET failed_login_count = 0, locked_until = NULL
WHERE id = $1 AND (failed_login_count <> 0 OR locked_until IS NOT NULL)
`

func (q *Queries) ResetLoginFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, id)
	return err
}

const setAvatarIfEmpty = `-- name: SetAvatarIfEmpty :exec
UPDATE users SET avatar_url = $1 WHERE id = $2 AND avatar_url IS NULL
`

type SetAvatarIfEmptyParams struct {
	AvatarUrl *string
	ID        uuid.UUID
}

func (q *Queries) SetAvatarIfEmpty(ctx context.Context, arg SetAvatarIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setAvatarIfEmpty, arg.AvatarUrl, arg.ID)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const setUploadedAvatar = `-- name: SetUploadedAvatar :exec
UPDATE users SET avatar_url = $1, avatar_key = $2, avatar_type = $3 WHERE id = $4
`

type SetUploadedAvatarParams struct {
	AvatarUrl  *string
	AvatarKey  *string
	AvatarType *string
	ID         uuid.UUID
}

func (q *Queries) SetUploadedAvatar(ctx context.Context, arg SetUploadedAvatarParams) error {
	_, err := q.db.Exec(ctx, setUploadedAvatar,
		arg.AvatarUrl,
		arg.AvatarKey,
		arg.AvatarType,
		arg.ID,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name   = COALESCE($1, name),
    locale = COALESCE($2, locale)
WHERE id = $3
RETURNING id, email, name, password_hash, email_verified_at, locale, avatar_url, failed_login_count, locked_until, created_at, updated_at, avatar_key, avatar_type
`

type UpdateUserProfileParams struct {
	Name   *string
	Locale *string
	ID     uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.Locale, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.AvatarUrl,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.AvatarType,
	)
	return i, err
}
