// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAttachments(ctx context.Context, cardID uuid.UUID) (CountAttachmentsRow, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	ListAttachments(ctx context.Context, cardID uuid.UUID) ([]Attachment, error)
}

var _ Querier = (*Queries)(nil)
