// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countAttachments = `-- name: CountAttachments :one
SELECT count(*)::int AS n, COALESCE(sum(size_bytes), 0)::bigint AS bytes FROM attachments WHERE card_id = $1
`

type CountAttachmentsRow struct {
	N     int32
	Bytes int64
}

func (q *Queries) CountAttachments(ctx context.Context, cardID uuid.UUID) (CountAttachmentsRow, error) {
	row := q.db.QueryRow(ctx, countAttachments, cardID)
	var i CountAttachmentsRow
	err := row.Scan(&i.N, &i.Bytes)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (workspace_id, card_id, name, content_type, size_bytes, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, card_id, name, content_type, size_bytes, storage_key, uploaded_by, created_at
`

type CreateAttachmentParams struct {
	WorkspaceID uuid.UUID
	CardID      uuid.UUID
	Name        string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	UploadedBy  uuid.NullUUID
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.WorkspaceID,
		arg.CardID,
		arg.Name,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, workspace_id, card_id, name, content_type, size_bytes, storage_key, uploaded_by, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, workspace_id, card_id, name, content_type, size_bytes, storage_key, uploaded_by, created_at FROM attachments WHERE card_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAttachments(ctx context.Context, cardID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CardID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
