// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO chat_members (channel_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.ChannelID, arg.UserID)
	return err
}

const addReaction = `-- name: AddReaction :exec
INSERT INTO chat_reactions (message_id, user_id, key) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Key       string
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.MessageID, arg.UserID, arg.Key)
	return err
}

const addReply = `-- name: AddReply :exec
UPDATE chat_messages SET reply_count = reply_count + 1, last_reply_at = $2 WHERE id = $1
`

type AddReplyParams struct {
	ID          uuid.UUID
	LastReplyAt *time.Time
}

func (q *Queries) AddReply(ctx context.Context, arg AddReplyParams) error {
	_, err := q.db.Exec(ctx, addReply, arg.ID, arg.LastReplyAt)
	return err
}

const archiveChannel = `-- name: ArchiveChannel :exec
UPDATE chat_channels SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveChannel, id)
	return err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO chat_channels (workspace_id, kind, name, topic, dm_key, created_by, ref_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, kind, name, topic, dm_key, created_by, created_at, last_message_at, archived_at, ref_id
`

type CreateChannelParams struct {
	WorkspaceID uuid.UUID
	Kind        string
	Name        *string
	Topic       string
	DmKey       *string
	CreatedBy   uuid.NullUUID
	RefID       uuid.NullUUID
}

// chat module queries (sqlc). Threads are one level deep: replies carry parent_id.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.WorkspaceID,
		arg.Kind,
		arg.Name,
		arg.Topic,
		arg.DmKey,
		arg.CreatedBy,
		arg.RefID,
	)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.ArchivedAt,
		&i.RefID,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :one
UPDATE chat_messages SET body = '', mentions = '{}', deleted_at = now() WHERE id = $1 RETURNING id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, deleteMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.Mentions,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, workspace_id, kind, name, topic, dm_key, created_by, created_at, last_message_at, archived_at, ref_id FROM chat_channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.ArchivedAt,
		&i.RefID,
	)
	return i, err
}

const getChannelState = `-- name: GetChannelState :one
SELECT c.id, c.workspace_id, c.kind, c.name, c.topic, c.dm_key, c.ref_id, c.created_by, c.created_at, c.last_message_at,
       (m.user_id IS NOT NULL)::boolean AS joined,
       COALESCE(m.muted, false)::boolean AS muted,
       (SELECT count(*) FROM chat_messages x
         WHERE x.channel_id = c.id AND x.parent_id IS NULL AND x.deleted_at IS NULL
           AND m.user_id IS NOT NULL AND x.created_at > m.last_read_at
           AND x.author_id IS DISTINCT FROM $1::uuid)::int AS unread,
       (SELECT count(*) FROM chat_messages x
         WHERE x.channel_id = c.id AND x.deleted_at IS NULL
           AND m.user_id IS NOT NULL AND x.created_at > m.last_read_at
           AND x.author_id IS DISTINCT FROM $1::uuid
           AND $1::uuid = ANY (x.mentions))::int AS mentions
FROM chat_channels c
LEFT JOIN chat_members m ON m.channel_id = c.id AND m.user_id = $1
WHERE c.id = $2
`

type GetChannelStateParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetChannelStateRow struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Kind          string
	Name          *string
	Topic         string
	DmKey         *string
	RefID         uuid.NullUUID
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	LastMessageAt *time.Time
	Joined        bool
	Muted         bool
	Unread        int32
	Mentions      int32
}

func (q *Queries) GetChannelState(ctx context.Context, arg GetChannelStateParams) (GetChannelStateRow, error) {
	row := q.db.QueryRow(ctx, getChannelState, arg.UserID, arg.ID)
	var i GetChannelStateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.RefID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.Joined,
		&i.Muted,
		&i.Unread,
		&i.Mentions,
	)
	return i, err
}

const getDMChannel = `-- name: GetDMChannel :one
SELECT id, workspace_id, kind, name, topic, dm_key, created_by, created_at, last_message_at, archived_at, ref_id FROM chat_channels WHERE workspace_id = $1 AND kind = 'dm' AND dm_key = $2
`

type GetDMChannelParams struct {
	WorkspaceID uuid.UUID
	DmKey       *string
}

func (q *Queries) GetDMChannel(ctx context.Context, arg GetDMChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getDMChannel, arg.WorkspaceID, arg.DmKey)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.ArchivedAt,
		&i.RefID,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT channel_id, user_id, joined_at, last_read_at, muted FROM chat_members WHERE channel_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.ChannelID, arg.UserID)
	var i ChatMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.JoinedAt,
		&i.LastReadAt,
		&i.Muted,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at FROM chat_messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.Mentions,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScopeChannel = `-- name: GetScopeChannel :one
SELECT id, workspace_id, kind, name, topic, dm_key, created_by, created_at, last_message_at, archived_at, ref_id FROM chat_channels WHERE kind = $1 AND ref_id = $2
`

type GetScopeChannelParams struct {
	Kind  string
	RefID uuid.NullUUID
}

func (q *Queries) GetScopeChannel(ctx context.Context, arg GetScopeChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getScopeChannel, arg.Kind, arg.RefID)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.ArchivedAt,
		&i.RefID,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO chat_messages (channel_id, author_id, parent_id, body, mentions)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at
`

type InsertMessageParams struct {
	ChannelID uuid.UUID
	AuthorID  uuid.NullUUID
	ParentID  uuid.NullUUID
	Body      string
	Mentions  []uuid.UUID
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ChannelID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
		arg.Mentions,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.Mentions,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChannelStates = `-- name: ListChannelStates :many
SELECT c.id, c.workspace_id, c.kind, c.name, c.topic, c.dm_key, c.created_by, c.created_at, c.last_message_at,
       (m.user_id IS NOT NULL)::boolean AS joined,
       COALESCE(m.muted, false)::boolean AS muted,
       (SELECT count(*) FROM chat_messages x
         WHERE x.channel_id = c.id AND x.parent_id IS NULL AND x.deleted_at IS NULL
           AND m.user_id IS NOT NULL AND x.created_at > m.last_read_at
           AND x.author_id IS DISTINCT FROM $1::uuid)::int AS unread,
       (SELECT count(*) FROM chat_messages x
         WHERE x.channel_id = c.id AND x.deleted_at IS NULL
           AND m.user_id IS NOT NULL AND x.created_at > m.last_read_at
           AND x.author_id IS DISTINCT FROM $1::uuid
           AND $1::uuid = ANY (x.mentions))::int AS mentions
FROM chat_channels c
LEFT JOIN chat_members m ON m.channel_id = c.id AND m.user_id = $1
WHERE c.workspace_id = $2 AND c.archived_at IS NULL
  AND c.kind IN ('public', 'private', 'dm')
  AND (c.kind = 'public' OR m.user_id IS NOT NULL)
ORDER BY c.name NULLS LAST, c.last_message_at DESC NULLS LAST, c.id
`

type ListChannelStatesParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListChannelStatesRow struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Kind          string
	Name          *string
	Topic         string
	DmKey         *string
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	LastMessageAt *time.Time
	Joined        bool
	Muted         bool
	Unread        int32
	Mentions      int32
}

func (q *Queries) ListChannelStates(ctx context.Context, arg ListChannelStatesParams) ([]ListChannelStatesRow, error) {
	rows, err := q.db.Query(ctx, listChannelStates, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelStatesRow{}
	for rows.Next() {
		var i ListChannelStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.DmKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.Joined,
			&i.Muted,
			&i.Unread,
			&i.Mentions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT channel_id, user_id, joined_at, last_read_at, muted FROM chat_members WHERE channel_id = $1 ORDER BY joined_at, user_id
`

func (q *Queries) ListMembers(ctx context.Context, channelID uuid.UUID) ([]ChatMember, error) {
	rows, err := q.db.Query(ctx, listMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMember{}
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Muted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersOf = `-- name: ListMembersOf :many
SELECT channel_id, user_id, joined_at, last_read_at, muted FROM chat_members WHERE channel_id = ANY ($1::uuid[]) ORDER BY channel_id, joined_at, user_id
`

func (q *Queries) ListMembersOf(ctx context.Context, ids []uuid.UUID) ([]ChatMember, error) {
	rows, err := q.db.Query(ctx, listMembersOf, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMember{}
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Muted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at FROM chat_messages m
WHERE m.channel_id = $1 AND m.parent_id IS NULL
  AND ($2::uuid IS NULL
       OR m.created_at < (SELECT b.created_at FROM chat_messages b WHERE b.id = $2)
       OR (m.created_at = (SELECT b.created_at FROM chat_messages b WHERE b.id = $2)
           AND m.id < $2))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListMessagesParams struct {
	ChannelID uuid.UUID
	BeforeID  uuid.NullUUID
	Lim       int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChannelID, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.Mentions,
			&i.ReplyCount,
			&i.LastReplyAt,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactions = `-- name: ListReactions :many
SELECT message_id, user_id, key, created_at FROM chat_reactions WHERE message_id = ANY ($1::uuid[]) ORDER BY message_id, created_at, user_id
`

func (q *Queries) ListReactions(ctx context.Context, ids []uuid.UUID) ([]ChatReaction, error) {
	rows, err := q.db.Query(ctx, listReactions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatReaction{}
	for rows.Next() {
		var i ChatReaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.Key,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at FROM chat_messages WHERE parent_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListReplies(ctx context.Context, parentID uuid.NullUUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.Mentions,
			&i.ReplyCount,
			&i.LastReplyAt,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
UPDATE chat_members SET last_read_at = now() WHERE channel_id = $1 AND user_id = $2
`

type MarkReadParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.Exec(ctx, markRead, arg.ChannelID, arg.UserID)
	return err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM chat_members WHERE channel_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ChannelID, arg.UserID)
	return err
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM chat_reactions WHERE message_id = $1 AND user_id = $2 AND key = $3
`

type RemoveReactionParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Key       string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Key)
	return err
}

const removeReply = `-- name: RemoveReply :exec
UPDATE chat_messages SET reply_count = GREATEST(reply_count - 1, 0) WHERE id = $1
`

func (q *Queries) RemoveReply(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeReply, id)
	return err
}

const setMuted = `-- name: SetMuted :exec
UPDATE chat_members SET muted = $3 WHERE channel_id = $1 AND user_id = $2
`

type SetMutedParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Muted     bool
}

func (q *Queries) SetMuted(ctx context.Context, arg SetMutedParams) error {
	_, err := q.db.Exec(ctx, setMuted, arg.ChannelID, arg.UserID, arg.Muted)
	return err
}

const touchChannel = `-- name: TouchChannel :exec
UPDATE chat_channels SET last_message_at = $2 WHERE id = $1
`

type TouchChannelParams struct {
	ID            uuid.UUID
	LastMessageAt *time.Time
}

func (q *Queries) TouchChannel(ctx context.Context, arg TouchChannelParams) error {
	_, err := q.db.Exec(ctx, touchChannel, arg.ID, arg.LastMessageAt)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE chat_channels SET name = $2, topic = $3 WHERE id = $1 RETURNING id, workspace_id, kind, name, topic, dm_key, created_by, created_at, last_message_at, archived_at, ref_id
`

type UpdateChannelParams struct {
	ID    uuid.UUID
	Name  *string
	Topic string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, updateChannel, arg.ID, arg.Name, arg.Topic)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.ArchivedAt,
		&i.RefID,
	)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE chat_messages SET body = $2, mentions = $3, edited_at = now() WHERE id = $1 RETURNING id, channel_id, author_id, parent_id, body, mentions, reply_count, last_reply_at, created_at, edited_at, deleted_at
`

type UpdateMessageParams struct {
	ID       uuid.UUID
	Body     string
	Mentions []uuid.UUID
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Body, arg.Mentions)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.Mentions,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
