// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) error
	AddReaction(ctx context.Context, arg AddReactionParams) error
	AddReply(ctx context.Context, arg AddReplyParams) error
	ArchiveChannel(ctx context.Context, id uuid.UUID) error
	// chat module queries (sqlc). Threads are one level deep: replies carry parent_id.
	CreateChannel(ctx context.Context, arg CreateChannelParams) (ChatChannel, error)
	DeleteMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error)
	GetChannel(ctx context.Context, id uuid.UUID) (ChatChannel, error)
	GetChannelState(ctx context.Context, arg GetChannelStateParams) (GetChannelStateRow, error)
	GetDMChannel(ctx context.Context, arg GetDMChannelParams) (ChatChannel, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (ChatMember, error)
	GetMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error)
	GetScopeChannel(ctx context.Context, arg GetScopeChannelParams) (ChatChannel, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error)
	ListChannelStates(ctx context.Context, arg ListChannelStatesParams) ([]ListChannelStatesRow, error)
	ListMembers(ctx context.Context, channelID uuid.UUID) ([]ChatMember, error)
	ListMembersOf(ctx context.Context, ids []uuid.UUID) ([]ChatMember, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatMessage, error)
	ListReactions(ctx context.Context, ids []uuid.UUID) ([]ChatReaction, error)
	ListReplies(ctx context.Context, parentID uuid.NullUUID) ([]ChatMessage, error)
	MarkRead(ctx context.Context, arg MarkReadParams) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) error
	RemoveReply(ctx context.Context, id uuid.UUID) error
	SetMuted(ctx context.Context, arg SetMutedParams) error
	TouchChannel(ctx context.Context, arg TouchChannelParams) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (ChatChannel, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (ChatMessage, error)
}

var _ Querier = (*Queries)(nil)
