// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMentions(ctx context.Context, arg AddMentionsParams) error
	ClearMentions(ctx context.Context, commentID uuid.UUID) error
	CountComments(ctx context.Context, cardID uuid.UUID) (int32, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	DeleteComment(ctx context.Context, id uuid.UUID) error
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	ListComments(ctx context.Context, cardID uuid.UUID) ([]Comment, error)
	MentionsForComments(ctx context.Context, ids []uuid.UUID) ([]CommentMention, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
}

var _ Querier = (*Queries)(nil)
