// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addMentions = `-- name: AddMentions :exec
INSERT INTO comment_mentions (comment_id, user_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddMentionsParams struct {
	CommentID uuid.UUID
	UserIds   []uuid.UUID
}

func (q *Queries) AddMentions(ctx context.Context, arg AddMentionsParams) error {
	_, err := q.db.Exec(ctx, addMentions, arg.CommentID, arg.UserIds)
	return err
}

const clearMentions = `-- name: ClearMentions :exec
DELETE FROM comment_mentions WHERE comment_id = $1
`

func (q *Queries) ClearMentions(ctx context.Context, commentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMentions, commentID)
	return err
}

const countComments = `-- name: CountComments :one
SELECT count(*)::int FROM comments WHERE card_id = $1
`

func (q *Queries) CountComments(ctx context.Context, cardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countComments, cardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (workspace_id, card_id, author_id, body) VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, card_id, author_id, body, created_at, edited_at
`

type CreateCommentParams struct {
	WorkspaceID uuid.UUID
	CardID      uuid.UUID
	AuthorID    uuid.NullUUID
	Body        string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.WorkspaceID,
		arg.CardID,
		arg.AuthorID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, workspace_id, card_id, author_id, body, created_at, edited_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, workspace_id, card_id, author_id, body, created_at, edited_at FROM comments WHERE card_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListComments(ctx context.Context, cardID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listComments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CardID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionsForComments = `-- name: MentionsForComments :many
SELECT comment_id, user_id FROM comment_mentions WHERE comment_id = ANY($1::uuid[])
`

func (q *Queries) MentionsForComments(ctx context.Context, ids []uuid.UUID) ([]CommentMention, error) {
	rows, err := q.db.Query(ctx, mentionsForComments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentMention{}
	for rows.Next() {
		var i CommentMention
		if err := rows.Scan(&i.CommentID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET body = $1, edited_at = now() WHERE id = $2 RETURNING id, workspace_id, card_id, author_id, body, created_at, edited_at
`

type UpdateCommentParams struct {
	Body string
	ID   uuid.UUID
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Body, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}
