// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) error
	CountMemberships(ctx context.Context, userID uuid.UUID) (int32, error)
	CountOwners(ctx context.Context, workspaceID uuid.UUID) (int32, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (WorkspaceInvite, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error)
	DeleteOpenInviteForEmail(ctx context.Context, arg DeleteOpenInviteForEmailParams) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) error
	GetInviteByHash(ctx context.Context, tokenHash []byte) (WorkspaceInvite, error)
	GetInviteByHashForUpdate(ctx context.Context, tokenHash []byte) (WorkspaceInvite, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error)
	ListOpenInvites(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	MarkInviteAccepted(ctx context.Context, id uuid.UUID) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
