// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAudit = `-- name: AddAudit :exec
INSERT INTO workspace_audit (workspace_id, actor_id, action, details) VALUES ($1, $2, $3, $4)
`

type AddAuditParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.NullUUID
	Action      string
	Details     []byte
}

func (q *Queries) AddAudit(ctx context.Context, arg AddAuditParams) error {
	_, err := q.db.Exec(ctx, addAudit,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Action,
		arg.Details,
	)
	return err
}

const addMember = `-- name: AddMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type AddMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const countMemberships = `-- name: CountMemberships :one
SELECT count(*)::int FROM workspace_members WHERE user_id = $1
`

func (q *Queries) CountMemberships(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMemberships, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*)::int FROM workspace_members WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOwners, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO workspace_invites (workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   []byte
	InvitedBy   uuid.NullUUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, created_by) VALUES ($1, $2, $3) RETURNING id, name, slug, created_by, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name      string
	Slug      string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.CreatedBy)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM workspace_invites WHERE workspace_id = $1 AND id = $2 AND accepted_at IS NULL
`

type DeleteInviteParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOpenInviteForEmail = `-- name: DeleteOpenInviteForEmail :exec
DELETE FROM workspace_invites WHERE workspace_id = $1 AND email = $2 AND accepted_at IS NULL
`

type DeleteOpenInviteForEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) DeleteOpenInviteForEmail(ctx context.Context, arg DeleteOpenInviteForEmailParams) error {
	_, err := q.db.Exec(ctx, deleteOpenInviteForEmail, arg.WorkspaceID, arg.Email)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invites WHERE token_hash = $1
`

func (q *Queries) GetInviteByHash(ctx context.Context, tokenHash []byte) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByHash, tokenHash)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByHashForUpdate = `-- name: GetInviteByHashForUpdate :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invites WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetInviteByHashForUpdate(ctx context.Context, tokenHash []byte) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByHashForUpdate, tokenHash)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSettings = `-- name: GetSettings :one
SELECT data FROM workspace_settings WHERE workspace_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, workspaceID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettings, workspaceID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, created_by, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_id, action, details, at FROM workspace_audit WHERE workspace_id = $1 ORDER BY at DESC, id LIMIT $2
`

type ListAuditParams struct {
	WorkspaceID uuid.UUID
	Limit       int32
}

type ListAuditRow struct {
	ID      uuid.UUID
	ActorID uuid.NullUUID
	Action  string
	Details []byte
	At      time.Time
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRow{}
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Details,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT user_id, role, joined_at FROM workspace_members WHERE workspace_id = $1 ORDER BY joined_at
`

type ListMembersRow struct {
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(&i.UserID, &i.Role, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenInvites = `-- name: ListOpenInvites :many
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invites
WHERE workspace_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListOpenInvites(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error) {
	rows, err := q.db.Query(ctx, listOpenInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvite{}
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMail = `-- name: ListWorkspaceMail :many
SELECT j.id, j.status, j.attempts, j.max_attempts, COALESCE(j.last_error, '')::text AS last_error, j.created_at,
       COALESCE(j.payload->>'to', '')::text AS recipient, COALESCE(j.payload->>'subject', '')::text AS subject
FROM jobs j
WHERE j.kind = 'mail.send'
  AND lower(j.payload->>'to') IN (
      SELECT lower(u.email) FROM workspace_members m JOIN users u ON u.id = m.user_id WHERE m.workspace_id = $1
      UNION
      SELECT lower(email) FROM workspace_invites WHERE workspace_id = $1)
ORDER BY j.id DESC
LIMIT 20
`

type ListWorkspaceMailRow struct {
	ID          int64
	Status      string
	Attempts    int32
	MaxAttempts int32
	LastError   string
	CreatedAt   time.Time
	Recipient   string
	Subject     string
}

// The latest emails addressed to people of this workspace (members and invited addresses).
func (q *Queries) ListWorkspaceMail(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMailRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMail, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMailRow{}
	for rows.Next() {
		var i ListWorkspaceMailRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.Recipient,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.created_at, m.role,
       (SELECT count(*) FROM workspace_members mm WHERE mm.workspace_id = w.id)::int AS member_count
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

type ListWorkspacesForUserRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	CreatedAt   time.Time
	Role        string
	MemberCount int32
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailQueueCounts = `-- name: MailQueueCounts :one
SELECT count(*) FILTER (WHERE status IN ('pending', 'running'))::int AS waiting,
       count(*) FILTER (WHERE status = 'failed' AND created_at > now() - interval '7 days')::int AS failed
FROM jobs WHERE kind = 'mail.send'
`

type MailQueueCountsRow struct {
	Waiting int32
	Failed  int32
}

func (q *Queries) MailQueueCounts(ctx context.Context) (MailQueueCountsRow, error) {
	row := q.db.QueryRow(ctx, mailQueueCounts)
	var i MailQueueCountsRow
	err := row.Scan(&i.Waiting, &i.Failed)
	return i, err
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE workspace_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const putSettings = `-- name: PutSettings :exec
INSERT INTO workspace_settings (workspace_id, data) VALUES ($1, $2)
ON CONFLICT (workspace_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now()
`

type PutSettingsParams struct {
	WorkspaceID uuid.UUID
	Data        []byte
}

func (q *Queries) PutSettings(ctx context.Context, arg PutSettingsParams) error {
	_, err := q.db.Exec(ctx, putSettings, arg.WorkspaceID, arg.Data)
	return err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.WorkspaceID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE workspace_members SET role = $1 WHERE workspace_id = $2 AND user_id = $3
`

type UpdateMemberRoleParams struct {
	Role        string
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.Role, arg.WorkspaceID, arg.UserID)
	return err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces SET name = $1 WHERE id = $2 RETURNING id, name, slug, created_by, created_at, updated_at
`

type UpdateWorkspaceNameParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceName, arg.Name, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
