// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	CreateNode(ctx context.Context, arg CreateNodeParams) (WikiNode, error)
	// wiki module queries (sqlc). Nodes are always filtered by deleted_at explicitly.
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (WikiSpace, error)
	DeletePermission(ctx context.Context, arg DeletePermissionParams) (int64, error)
	DeleteSpace(ctx context.Context, id uuid.UUID) error
	FavoriteIDs(ctx context.Context, arg FavoriteIDsParams) ([]uuid.UUID, error)
	GetNode(ctx context.Context, id uuid.UUID) (WikiNode, error)
	GetNodes(ctx context.Context, ids []uuid.UUID) ([]WikiNode, error)
	GetPermission(ctx context.Context, arg GetPermissionParams) (WikiPermission, error)
	GetSpace(ctx context.Context, id uuid.UUID) (WikiSpace, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	ListAudit(ctx context.Context, arg ListAuditParams) ([]WikiAudit, error)
	// Grants of the space (node_id IS NULL) and of the given nodes: one chain.
	ListChainPermissions(ctx context.Context, arg ListChainPermissionsParams) ([]WikiPermission, error)
	ListFavoriteNodes(ctx context.Context, arg ListFavoriteNodesParams) ([]WikiNode, error)
	// Nodes (live) holding a direct grant for the user or one of their teams, not owned by them.
	ListGrantedNodes(ctx context.Context, arg ListGrantedNodesParams) ([]WikiNode, error)
	ListOwnedNodes(ctx context.Context, arg ListOwnedNodesParams) ([]WikiNode, error)
	ListRecentNodes(ctx context.Context, arg ListRecentNodesParams) ([]WikiNode, error)
	ListSiblings(ctx context.Context, arg ListSiblingsParams) ([]WikiNode, error)
	ListSpaceNodes(ctx context.Context, spaceID uuid.UUID) ([]WikiNode, error)
	ListSpacePermissions(ctx context.Context, spaceID uuid.UUID) ([]WikiPermission, error)
	ListSpaces(ctx context.Context, workspaceID uuid.UUID) ([]WikiSpace, error)
	ListTrashRoots(ctx context.Context, arg ListTrashRootsParams) ([]WikiNode, error)
	MoveGrantsToSpace(ctx context.Context, arg MoveGrantsToSpaceParams) error
	PlaceNode(ctx context.Context, arg PlaceNodeParams) (WikiNode, error)
	PurgeExpiredTrash(ctx context.Context, deletedAt *time.Time) (int64, error)
	// Permanent removal of a trashed subtree; independently trashed descendants (other roots) survive.
	PurgeTrashRoot(ctx context.Context, trashRootID uuid.NullUUID) error
	// Rewrites the descendants of a moved node: swaps the path prefix, shifts depth, follows the space.
	RebaseDescendants(ctx context.Context, arg RebaseDescendantsParams) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	RestoreTrashRoot(ctx context.Context, trashRootID uuid.NullUUID) error
	SetNodeVisibility(ctx context.Context, arg SetNodeVisibilityParams) (WikiNode, error)
	SetSpaceVisibility(ctx context.Context, arg SetSpaceVisibilityParams) (WikiSpace, error)
	SubtreeMaxDepth(ctx context.Context, prefix string) (int32, error)
	TouchRecent(ctx context.Context, arg TouchRecentParams) error
	TrashSubtree(ctx context.Context, arg TrashSubtreeParams) error
	UpdateNodeMeta(ctx context.Context, arg UpdateNodeMetaParams) (WikiNode, error)
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (WikiSpace, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (WikiPermission, error)
}

var _ Querier = (*Queries)(nil)
