// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries WHERE id = $1
`

func (q *Queries) DeleteTimeEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeEntry, id)
	return err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at FROM time_entries WHERE id = $1
`

func (q *Queries) GetTimeEntry(ctx context.Context, id uuid.UUID) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, getTimeEntry, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Seconds,
		&i.Note,
		&i.Manual,
		&i.CreatedAt,
	)
	return i, err
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at FROM time_entries WHERE card_id = $1 ORDER BY started_at DESC, id
`

func (q *Queries) ListTimeEntries(ctx context.Context, cardID uuid.UUID) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listTimeEntries, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CardID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Seconds,
			&i.Note,
			&i.Manual,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logTime = `-- name: LogTime :one
INSERT INTO time_entries (workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
RETURNING id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at
`

type LogTimeParams struct {
	WorkspaceID uuid.UUID
	CardID      uuid.UUID
	UserID      uuid.UUID
	StartedAt   time.Time
	EndedAt     *time.Time
	Seconds     int32
	Note        string
}

func (q *Queries) LogTime(ctx context.Context, arg LogTimeParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, logTime,
		arg.WorkspaceID,
		arg.CardID,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Seconds,
		arg.Note,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Seconds,
		&i.Note,
		&i.Manual,
		&i.CreatedAt,
	)
	return i, err
}

const runningTimer = `-- name: RunningTimer :one
SELECT id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at FROM time_entries WHERE user_id = $1 AND ended_at IS NULL
`

func (q *Queries) RunningTimer(ctx context.Context, userID uuid.UUID) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, runningTimer, userID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Seconds,
		&i.Note,
		&i.Manual,
		&i.CreatedAt,
	)
	return i, err
}

const startTimer = `-- name: StartTimer :one
INSERT INTO time_entries (workspace_id, card_id, user_id, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at
`

type StartTimerParams struct {
	WorkspaceID uuid.UUID
	CardID      uuid.UUID
	UserID      uuid.UUID
	StartedAt   time.Time
}

func (q *Queries) StartTimer(ctx context.Context, arg StartTimerParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, startTimer,
		arg.WorkspaceID,
		arg.CardID,
		arg.UserID,
		arg.StartedAt,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Seconds,
		&i.Note,
		&i.Manual,
		&i.CreatedAt,
	)
	return i, err
}

const stopRunningTimer = `-- name: StopRunningTimer :exec
UPDATE time_entries SET
    ended_at = $1,
    seconds  = GREATEST(EXTRACT(EPOCH FROM ($1::timestamptz - started_at))::int, 0)
WHERE user_id = $2 AND ended_at IS NULL
`

type StopRunningTimerParams struct {
	EndedAt *time.Time
	UserID  uuid.UUID
}

func (q *Queries) StopRunningTimer(ctx context.Context, arg StopRunningTimerParams) error {
	_, err := q.db.Exec(ctx, stopRunningTimer, arg.EndedAt, arg.UserID)
	return err
}

const stopTimer = `-- name: StopTimer :one
UPDATE time_entries SET
    ended_at = $1,
    seconds  = GREATEST(EXTRACT(EPOCH FROM ($1::timestamptz - started_at))::int, 0)
WHERE id = $2 AND ended_at IS NULL
RETURNING id, workspace_id, card_id, user_id, started_at, ended_at, seconds, note, manual, created_at
`

type StopTimerParams struct {
	EndedAt *time.Time
	ID      uuid.UUID
}

func (q *Queries) StopTimer(ctx context.Context, arg StopTimerParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, stopTimer, arg.EndedAt, arg.ID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Seconds,
		&i.Note,
		&i.Manual,
		&i.CreatedAt,
	)
	return i, err
}
