// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
)

type Querier interface {
	CardActivity(ctx context.Context, arg CardActivityParams) ([]Activity, error)
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
}

var _ Querier = (*Queries)(nil)
