// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cardActivity = `-- name: CardActivity :many
SELECT id, workspace_id, project_id, card_id, actor_id, kind, data, at FROM activity
WHERE card_id = $1 AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type CardActivityParams struct {
	CardID uuid.NullUUID
	Before pgtype.Int8
	Lim    int32
}

func (q *Queries) CardActivity(ctx context.Context, arg CardActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, cardActivity, arg.CardID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.CardID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity (workspace_id, project_id, card_id, actor_id, kind, data)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertActivityParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.NullUUID
	CardID      uuid.NullUUID
	ActorID     uuid.NullUUID
	Kind        string
	Data        []byte
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.CardID,
		arg.ActorID,
		arg.Kind,
		arg.Data,
	)
	return err
}
