// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDelivery = `-- name: ClaimDelivery :one
INSERT INTO github_deliveries (delivery_id) VALUES ($1) ON CONFLICT DO NOTHING RETURNING delivery_id
`

func (q *Queries) ClaimDelivery(ctx context.Context, deliveryID string) (string, error) {
	row := q.db.QueryRow(ctx, claimDelivery, deliveryID)
	var delivery_id string
	err := row.Scan(&delivery_id)
	return delivery_id, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM github_connections WHERE workspace_id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, workspaceID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM github_repos WHERE id = $1 AND workspace_id = $2
`

type DeleteRepoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteRepo(ctx context.Context, arg DeleteRepoParams) error {
	_, err := q.db.Exec(ctx, deleteRepo, arg.ID, arg.WorkspaceID)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT workspace_id, connected_by, account_login, token_enc, webhook_secret_enc, enabled, pr_opened_to_review, pr_merged_to_done, sync_issues, comment_on_pr, created_at, updated_at FROM github_connections WHERE workspace_id = $1
`

func (q *Queries) GetConnection(ctx context.Context, workspaceID uuid.UUID) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getConnection, workspaceID)
	var i GithubConnection
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConnectedBy,
		&i.AccountLogin,
		&i.TokenEnc,
		&i.WebhookSecretEnc,
		&i.Enabled,
		&i.PrOpenedToReview,
		&i.PrMergedToDone,
		&i.SyncIssues,
		&i.CommentOnPr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, workspace_id, project_id, full_name, hook_id, created_at FROM github_repos WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id uuid.UUID) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FullName,
		&i.HookID,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, workspace_id, project_id, full_name, hook_id, created_at FROM github_repos WHERE lower(full_name) = lower($1)
`

func (q *Queries) GetRepoByName(ctx context.Context, lower string) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, getRepoByName, lower)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FullName,
		&i.HookID,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByProject = `-- name: GetRepoByProject :one
SELECT id, workspace_id, project_id, full_name, hook_id, created_at FROM github_repos WHERE project_id = $1
`

func (q *Queries) GetRepoByProject(ctx context.Context, projectID uuid.UUID) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, getRepoByProject, projectID)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FullName,
		&i.HookID,
		&i.CreatedAt,
	)
	return i, err
}

const insertRepo = `-- name: InsertRepo :one
INSERT INTO github_repos (workspace_id, project_id, full_name, hook_id) VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, project_id, full_name, hook_id, created_at
`

type InsertRepoParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	FullName    string
	HookID      pgtype.Int8
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, insertRepo,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FullName,
		arg.HookID,
	)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FullName,
		&i.HookID,
		&i.CreatedAt,
	)
	return i, err
}

const linksForCard = `-- name: LinksForCard :many
SELECT l.id, l.card_id, l.repo_id, l.kind, l.number, l.title, l.state, l.url, l.author, l.updated_at, r.full_name FROM github_links l JOIN github_repos r ON r.id = l.repo_id
WHERE l.card_id = $1 ORDER BY l.kind DESC, l.number
`

type LinksForCardRow struct {
	ID        uuid.UUID
	CardID    uuid.UUID
	RepoID    uuid.UUID
	Kind      string
	Number    int32
	Title     string
	State     string
	Url       string
	Author    string
	UpdatedAt time.Time
	FullName  string
}

func (q *Queries) LinksForCard(ctx context.Context, cardID uuid.UUID) ([]LinksForCardRow, error) {
	rows, err := q.db.Query(ctx, linksForCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinksForCardRow{}
	for rows.Next() {
		var i LinksForCardRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.RepoID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Url,
			&i.Author,
			&i.UpdatedAt,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linksForRef = `-- name: LinksForRef :many
SELECT id, card_id, repo_id, kind, number, title, state, url, author, updated_at FROM github_links WHERE repo_id = $1 AND kind = $2 AND number = $3
`

type LinksForRefParams struct {
	RepoID uuid.UUID
	Kind   string
	Number int32
}

func (q *Queries) LinksForRef(ctx context.Context, arg LinksForRefParams) ([]GithubLink, error) {
	rows, err := q.db.Query(ctx, linksForRef, arg.RepoID, arg.Kind, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubLink{}
	for rows.Next() {
		var i GithubLink
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.RepoID,
			&i.Kind,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Url,
			&i.Author,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, workspace_id, project_id, full_name, hook_id, created_at FROM github_repos WHERE workspace_id = $1 ORDER BY full_name
`

func (q *Queries) ListRepos(ctx context.Context, workspaceID uuid.UUID) ([]GithubRepo, error) {
	rows, err := q.db.Query(ctx, listRepos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepo{}
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.FullName,
			&i.HookID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDeliveries = `-- name: PruneDeliveries :exec
DELETE FROM github_deliveries WHERE received_at < $1
`

func (q *Queries) PruneDeliveries(ctx context.Context, receivedAt time.Time) error {
	_, err := q.db.Exec(ctx, pruneDeliveries, receivedAt)
	return err
}

const setLinkState = `-- name: SetLinkState :exec
UPDATE github_links SET state = $4, updated_at = now() WHERE repo_id = $1 AND kind = $2 AND number = $3
`

type SetLinkStateParams struct {
	RepoID uuid.UUID
	Kind   string
	Number int32
	State  string
}

func (q *Queries) SetLinkState(ctx context.Context, arg SetLinkStateParams) error {
	_, err := q.db.Exec(ctx, setLinkState,
		arg.RepoID,
		arg.Kind,
		arg.Number,
		arg.State,
	)
	return err
}

const updateRules = `-- name: UpdateRules :one
UPDATE github_connections
SET enabled = $2, pr_opened_to_review = $3, pr_merged_to_done = $4, sync_issues = $5, comment_on_pr = $6, updated_at = now()
WHERE workspace_id = $1
RETURNING workspace_id, connected_by, account_login, token_enc, webhook_secret_enc, enabled, pr_opened_to_review, pr_merged_to_done, sync_issues, comment_on_pr, created_at, updated_at
`

type UpdateRulesParams struct {
	WorkspaceID      uuid.UUID
	Enabled          bool
	PrOpenedToReview bool
	PrMergedToDone   bool
	SyncIssues       bool
	CommentOnPr      bool
}

func (q *Queries) UpdateRules(ctx context.Context, arg UpdateRulesParams) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, updateRules,
		arg.WorkspaceID,
		arg.Enabled,
		arg.PrOpenedToReview,
		arg.PrMergedToDone,
		arg.SyncIssues,
		arg.CommentOnPr,
	)
	var i GithubConnection
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConnectedBy,
		&i.AccountLogin,
		&i.TokenEnc,
		&i.WebhookSecretEnc,
		&i.Enabled,
		&i.PrOpenedToReview,
		&i.PrMergedToDone,
		&i.SyncIssues,
		&i.CommentOnPr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnection = `-- name: UpsertConnection :one

INSERT INTO github_connections (workspace_id, connected_by, account_login, token_enc, webhook_secret_enc)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id) DO UPDATE
SET connected_by = EXCLUDED.connected_by, account_login = EXCLUDED.account_login, token_enc = EXCLUDED.token_enc,
    webhook_secret_enc = EXCLUDED.webhook_secret_enc, enabled = true, updated_at = now()
RETURNING workspace_id, connected_by, account_login, token_enc, webhook_secret_enc, enabled, pr_opened_to_review, pr_merged_to_done, sync_issues, comment_on_pr, created_at, updated_at
`

type UpsertConnectionParams struct {
	WorkspaceID      uuid.UUID
	ConnectedBy      uuid.UUID
	AccountLogin     string
	TokenEnc         []byte
	WebhookSecretEnc []byte
}

// github module queries (sqlc).
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, upsertConnection,
		arg.WorkspaceID,
		arg.ConnectedBy,
		arg.AccountLogin,
		arg.TokenEnc,
		arg.WebhookSecretEnc,
	)
	var i GithubConnection
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConnectedBy,
		&i.AccountLogin,
		&i.TokenEnc,
		&i.WebhookSecretEnc,
		&i.Enabled,
		&i.PrOpenedToReview,
		&i.PrMergedToDone,
		&i.SyncIssues,
		&i.CommentOnPr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLink = `-- name: UpsertLink :one
INSERT INTO github_links (card_id, repo_id, kind, number, title, state, url, author)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (repo_id, kind, number, card_id) DO UPDATE
SET title = EXCLUDED.title, state = EXCLUDED.state, url = EXCLUDED.url, author = EXCLUDED.author, updated_at = now()
RETURNING id, card_id, repo_id, kind, number, title, state, url, author, updated_at
`

type UpsertLinkParams struct {
	CardID uuid.UUID
	RepoID uuid.UUID
	Kind   string
	Number int32
	Title  string
	State  string
	Url    string
	Author string
}

func (q *Queries) UpsertLink(ctx context.Context, arg UpsertLinkParams) (GithubLink, error) {
	row := q.db.QueryRow(ctx, upsertLink,
		arg.CardID,
		arg.RepoID,
		arg.Kind,
		arg.Number,
		arg.Title,
		arg.State,
		arg.Url,
		arg.Author,
	)
	var i GithubLink
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.RepoID,
		&i.Kind,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Url,
		&i.Author,
		&i.UpdatedAt,
	)
	return i, err
}
