// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeUserToken = `-- name: ConsumeUserToken :one
UPDATE user_tokens SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

type ConsumeUserTokenParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeUserToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO user_identities (user_id, provider, provider_user_id, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, provider_user_id) DO NOTHING
`

type CreateIdentityParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          *string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent *string
	Ip        *string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserTokenParams struct {
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, user_id, provider, provider_user_id, email, created_at FROM user_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.ProviderUserID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, ip, created_at FROM refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserTokens = `-- name: InvalidateUserTokens :exec
UPDATE user_tokens SET used_at = now() WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateUserTokensParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUserTokens, arg.UserID, arg.Purpose)
	return err
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT provider FROM user_identities WHERE user_id = $1 ORDER BY provider
`

func (q *Queries) ListIdentityProviders(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listIdentityProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT family_id,
       min(created_at)::timestamptz AS started_at,
       max(created_at)::timestamptz AS last_seen_at,
       (array_agg(user_agent ORDER BY created_at DESC))[1]::text AS user_agent,
       (array_agg(ip ORDER BY created_at DESC))[1]::text AS ip
FROM refresh_tokens
WHERE user_id = $1
GROUP BY family_id
HAVING bool_or(revoked_at IS NULL AND expires_at > now() AND replaced_by IS NULL)
ORDER BY max(created_at) DESC
`

type ListUserSessionsRow struct {
	FamilyID   uuid.UUID
	StartedAt  time.Time
	LastSeenAt time.Time
	UserAgent  string
	Ip         string
}

// One row per sign-in (a family of rotated refresh tokens) that is still usable.
func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.UserAgent,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens SET revoked_at = now(), replaced_by = $1 WHERE id = $2
`

type MarkRefreshTokenRotatedParams struct {
	ReplacedBy uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.ReplacedBy, arg.ID)
	return err
}

const revokeOtherUserRefreshTokens = `-- name: RevokeOtherUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND family_id <> $2 AND revoked_at IS NULL
`

type RevokeOtherUserRefreshTokensParams struct {
	UserID       uuid.UUID
	KeepFamilyID uuid.UUID
}

func (q *Queries) RevokeOtherUserRefreshTokens(ctx context.Context, arg RevokeOtherUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserRefreshTokens, arg.UserID, arg.KeepFamilyID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const revokeUserRefreshFamily = `-- name: RevokeUserRefreshFamily :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND family_id = $2 AND revoked_at IS NULL
`

type RevokeUserRefreshFamilyParams struct {
	UserID   uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) RevokeUserRefreshFamily(ctx context.Context, arg RevokeUserRefreshFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshFamily, arg.UserID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}
