// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (uuid.UUID, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (uuid.UUID, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetIdentity(ctx context.Context, arg GetIdentityParams) (UserIdentity, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error
	ListIdentityProviders(ctx context.Context, userID uuid.UUID) ([]string, error)
	MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error
	RevokeOtherUserRefreshTokens(ctx context.Context, arg RevokeOtherUserRefreshTokensParams) error
	RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error
	RevokeUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
